// frontend-vite/src/pages/calendar.tsx
import { useEffect, useState, useMemo, useCallback } from 'react';
import { calendarAPI } from '@/services/api';
import { PageHeader, SectionLabel } from '@/components/ui/page-helpers';
import { Icon } from '@/components/ui/icon';

interface CalendarEvent {
  id: number;
  title: string;
  type: string;
  status: string;
  start_date: string;
  end_date: string;
  location?: string;
  tags?: string;
}

const TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  hackathon:  { bg: 'rgba(45,212,191,0.15)',  text: 'var(--teal, #2dd4bf)',   border: 'rgba(45,212,191,0.4)' },
  innovation: { bg: 'rgba(96,165,250,0.15)',   text: 'var(--blue, #60a5fa)',   border: 'rgba(96,165,250,0.4)' },
  research:   { bg: 'rgba(167,139,250,0.15)',  text: 'var(--purple, #a78bfa)', border: 'rgba(167,139,250,0.4)' },
  business_plan: { bg: 'rgba(52,211,153,0.15)', text: 'var(--green, #34d399)', border: 'rgba(52,211,153,0.4)' },
  ai_innovation: { bg: 'rgba(251,113,133,0.15)', text: 'var(--red, #fb7185)', border: 'rgba(251,113,133,0.4)' },
  data_science: { bg: 'rgba(251,146,60,0.15)', text: 'var(--orange, #fb923c)', border: 'rgba(251,146,60,0.4)' },
};

const TYPE_LABELS: Record<string, string> = {
  hackathon: '黑客松',
  innovation: '创新赛',
  research: '研究赛',
  business_plan: '商业计划赛',
  ai_innovation: 'AI创新赛',
  data_science: '数据科学赛',
};

const STATUS_LABELS: Record<string, string> = {
  draft: '草稿',
  published: '已发布',
  ongoing: '进行中',
  completed: '已完成',
  cancelled: '已取消',
};

const WEEKDAYS = ['一', '二', '三', '四', '五', '六', '日'];

export function CalendarPage() {
  const [currentMonth, setCurrentMonth] = useState(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  });
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [selectedDay, setSelectedDay] = useState<string | null>(null);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    setLoading(true);
    calendarAPI.list(currentMonth)
      .then(res => {
        setEvents(res.events || []);
        setTotal(res.total || 0);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [currentMonth]);

  // Parse currentMonth into year and month.
  const [year, month] = currentMonth.split('-').map(Number);

  // Navigate months.
  const prevMonth = useCallback(() => {
    const d = new Date(year, month - 2, 1);
    setCurrentMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
    setSelectedDay(null);
  }, [year, month]);

  const nextMonth = useCallback(() => {
    const d = new Date(year, month, 1);
    setCurrentMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`);
    setSelectedDay(null);
  }, [year, month]);

  // Export calendar as iCal (.ics) file
  const handleExportICS = useCallback(async () => {
    setExporting(true);
    try {
      const blob = await calendarAPI.exportICS();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `ssgl_calendar_${new Date().toISOString().slice(0, 10)}.ics`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('iCal export failed:', err);
    } finally {
      setExporting(false);
    }
  }, []);

  const monthLabel = `${year}年${month}月`;

  // Build calendar grid.
  const calendarDays = useMemo(() => {
    const firstDay = new Date(year, month - 1, 1);
    // getDay() returns 0=Sun. We want Mon=0.
    let startWeekday = firstDay.getDay() - 1;
    if (startWeekday < 0) startWeekday = 6; // Sunday -> 6

    const daysInMonth = new Date(year, month, 0).getDate();
    const days: { date: string; day: number; inMonth: boolean }[] = [];

    // Previous month padding.
    const prevDays = new Date(year, month - 1, 0).getDate();
    for (let i = startWeekday - 1; i >= 0; i--) {
      const d = prevDays - i;
      const m = month - 1 || 12;
      const y = month === 1 ? year - 1 : year;
      days.push({ date: `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: false });
    }

    // Current month.
    for (let d = 1; d <= daysInMonth; d++) {
      days.push({ date: `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: true });
    }

    // Next month padding (fill to complete rows of 7).
    const remainder = days.length % 7;
    if (remainder !== 0) {
      const fill = 7 - remainder;
      for (let d = 1; d <= fill; d++) {
        const m = month + 1 > 12 ? 1 : month + 1;
        const y = month + 1 > 12 ? year + 1 : year;
        days.push({ date: `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: false });
      }
    }

    return days;
  }, [year, month]);

  // Map events to dates.
  const eventsByDate = useMemo(() => {
    const map = new Map<string, CalendarEvent[]>();
    for (const evt of events) {
      const start = new Date(evt.start_date);
      const end = new Date(evt.end_date);
      // Mark every day from start to end.
      const cursor = new Date(start);
      while (cursor <= end) {
        const key = cursor.toISOString().slice(0, 10);
        if (!map.has(key)) map.set(key, []);
        map.get(key)!.push(evt);
        cursor.setDate(cursor.getDate() + 1);
      }
    }
    return map;
  }, [events]);

  // Today's date string.
  const todayStr = new Date().toISOString().slice(0, 10);

  // Selected day events.
  const selectedEvents = selectedDay ? eventsByDate.get(selectedDay) || [] : [];

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <PageHeader
        title="赛事日历"
        subtitle={`${monthLabel} · ${total} 个赛事`}
        actions={
          <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>
            <button
              onClick={handleExportICS}
              disabled={exporting}
              style={{
                height: 32, padding: '0 12px', borderRadius: 8, border: '1px solid var(--teal)',
                background: 'var(--teal-bg)', color: 'var(--teal)', cursor: exporting ? 'wait' : 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 12, fontWeight: 600, gap: 4, opacity: exporting ? 0.6 : 1,
              }}
            >
              <Icon name="download" size={12} /> {exporting ? '导出中…' : 'iCal 订阅'}
            </button>
            <button
              onClick={() => {
                const now = new Date();
                setCurrentMonth(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`);
                setSelectedDay(new Date().toISOString().slice(0, 10));
              }}
              style={{
                height: 32, padding: '0 12px', borderRadius: 8, border: '1px solid var(--amber)',
                background: 'var(--amber-bg)', color: 'var(--amber)', cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 12, fontWeight: 600, gap: 4,
              }}
            >
              <Icon name="target" size={12} /> 今天
            </button>
            <button
              onClick={prevMonth}
              style={{
                width: 32, height: 32, borderRadius: 8, border: '1px solid var(--border)',
                background: 'var(--surface-2)', color: 'var(--text)', cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}
            >
              <Icon name="chevron-left" size={14} />
            </button>
            <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 14, minWidth: 100, textAlign: 'center' }}>
              {monthLabel}
            </span>
            <button
              onClick={nextMonth}
              style={{
                width: 32, height: 32, borderRadius: 8, border: '1px solid var(--border)',
                background: 'var(--surface-2)', color: 'var(--text)', cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}
            >
              <Icon name="chevron-right" size={14} />
            </button>
          </div>
        }
      />

      {/* Legend */}
      <div className="card anim-in" style={{ padding: '10px 16px', marginBottom: 16, display: 'flex', gap: 16, alignItems: 'center', flexWrap: 'wrap' }}>
        <SectionLabel label="类型图例" />
        {Object.entries(TYPE_COLORS).map(([type, colors]) => (
          <div key={type} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <div style={{ width: 10, height: 10, borderRadius: 3, background: colors.text }} />
            <span style={{ fontSize: 12, color: 'var(--text-3)' }}>{TYPE_LABELS[type] || type}</span>
          </div>
        ))}
      </div>

      {/* Calendar Grid */}
      <div className="card anim-in d1" style={{ overflow: 'hidden' }}>
        {/* Weekday header */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', borderBottom: '1px solid var(--border)' }}>
          {WEEKDAYS.map(wd => (
            <div key={wd} style={{
              padding: '10px 0', textAlign: 'center', fontSize: 11, fontWeight: 700,
              letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--text-3)',
            }}>{wd}</div>
          ))}
        </div>

        {/* Day cells */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)' }}>
          {calendarDays.map(({ date, day, inMonth }) => {
            const dayEvents = eventsByDate.get(date) || [];
            const isToday = date === todayStr;
            const isSelected = date === selectedDay;

            return (
              <div
                key={date}
                onClick={() => setSelectedDay(isSelected ? null : date)}
                style={{
                  minHeight: 90,
                  padding: 6,
                  borderRight: '1px solid var(--border)',
                  borderBottom: '1px solid var(--border)',
                  cursor: 'pointer',
                  background: isSelected ? 'var(--surface-2)' : isToday ? 'var(--amber-bg)' : 'transparent',
                  transition: 'background 0.15s',
                  opacity: inMonth ? 1 : 0.35,
                  position: 'relative',
                }}
              >
                <div style={{
                  fontSize: 12, fontWeight: isToday ? 800 : 500,
                  color: isToday ? 'var(--amber)' : 'var(--text)',
                  marginBottom: 4,
                  width: 22, height: 22, borderRadius: 6,
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  background: isToday ? 'var(--amber)' : 'transparent',
                }}>
                  <span style={{ color: isToday ? '#0F1523' : undefined }}>{day}</span>
                </div>

                {/* Event chips */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                  {dayEvents.slice(0, 3).map(evt => {
                    const colors = TYPE_COLORS[evt.type] || TYPE_COLORS.hackathon;
                    return (
                      <div
                        key={evt.id}
                        title={evt.title}
                        style={{
                          fontSize: 10, fontWeight: 600, padding: '1px 5px', borderRadius: 3,
                          background: colors.bg, color: colors.text,
                          borderLeft: `2px solid ${colors.border}`,
                          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                        }}
                      >
                        {evt.title}
                      </div>
                    );
                  })}
                  {dayEvents.length > 3 && (
                    <div style={{ fontSize: 9, color: 'var(--text-3)', paddingLeft: 5 }}>
                      +{dayEvents.length - 3} 更多
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Day Detail Panel */}
      {selectedDay && selectedEvents.length > 0 && (
        <div className="card anim-in d2" style={{ marginTop: 16, padding: 20 }}>
          <SectionLabel label={`${selectedDay} 赛事详情`} count={selectedEvents.length} />
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {selectedEvents.map(evt => {
              const colors = TYPE_COLORS[evt.type] || TYPE_COLORS.hackathon;
              return (
                <div key={evt.id} style={{
                  padding: 14, borderRadius: 8,
                  background: 'var(--surface-2)', border: '1px solid var(--border)',
                  display: 'flex', gap: 14, alignItems: 'flex-start',
                }}>
                  <div style={{
                    width: 4, height: '100%', minHeight: 40, borderRadius: 2,
                    background: colors.text, flexShrink: 0,
                  }} />
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
                      <span style={{ fontFamily: 'var(--font-display)', fontSize: 15, fontWeight: 700, color: 'var(--text)' }}>
                        {evt.title}
                      </span>
                      <span style={{
                        fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 4,
                        background: colors.bg, color: colors.text,
                      }}>
                        {TYPE_LABELS[evt.type] || evt.type}
                      </span>
                      <span style={{
                        fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 4,
                        background: 'var(--surface-3)', color: 'var(--text-3)',
                      }}>
                        {STATUS_LABELS[evt.status] || evt.status}
                      </span>
                    </div>
                    <div style={{ display: 'flex', gap: 16, fontSize: 12, color: 'var(--text-3)' }}>
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><Icon name="calendar" size={12} />{new Date(evt.start_date).toLocaleDateString('zh-CN')} — {new Date(evt.end_date).toLocaleDateString('zh-CN')}</span>
                      {evt.location && <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><Icon name="map-pin" size={12} />{evt.location}</span>}
                      {evt.tags && <span style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}><Icon name="tag" size={12} />{evt.tags}</span>}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// frontend-vue/src/views/ssgl/calendar/index.vue
<template>
  <section class="ssgl-page" data-page="Calendar">
    <SSGLPageHeader
      title="赛事日历"
      :subtitle="`${monthLabel} · ${events.length} 个赛事`"
    >
      <template #actions>
        <ElButton size="small" :loading="exporting" @click="handleExportICS">iCal 订阅</ElButton>
        <ElButton size="small" @click="goToToday">今天</ElButton>
        <ElButton :icon="ArrowLeft" size="small" circle @click="prevMonth" />
        <span class="month-label">{{ monthLabel }}</span>
        <ElButton :icon="ArrowRight" size="small" circle @click="nextMonth" />
      </template>
    </SSGLPageHeader>

    <!-- Legend -->
    <div class="legend-bar">
      <span v-for="(colors, type) in TYPE_COLORS" :key="type" class="legend-item">
        <span class="legend-dot" :style="{ background: colors.text }" />
        {{ TYPE_LABELS[type as string] || type }}
      </span>
    </div>

    <!-- Calendar Grid -->
    <ElCard v-loading="loading" shadow="never" class="calendar-card">
      <!-- Weekday Header -->
      <div class="calendar-weekdays">
        <div v-for="wd in WEEKDAYS" :key="wd" class="weekday-cell">{{ wd }}</div>
      </div>

      <!-- Day Cells -->
      <div class="calendar-grid">
        <div
          v-for="{ date, day, inMonth } in calendarDays"
          :key="date"
          class="day-cell"
          :class="{
            'is-today': date === todayStr,
            'is-selected': date === selectedDay,
            'is-other': !inMonth,
          }"
          @click="toggleDay(date)"
        >
          <div class="day-number" :class="{ 'is-today-num': date === todayStr }">{{ day }}</div>
          <div class="day-events">
            <div
              v-for="evt in (eventsByDate[date] || []).slice(0, 3)"
              :key="evt.id"
              class="event-chip"
              :style="getEventStyle(evt)"
              :title="evt.title"
            >
              {{ evt.title }}
            </div>
            <div v-if="(eventsByDate[date] || []).length > 3" class="event-more">
              +{{ eventsByDate[date].length - 3 }} 更多
            </div>
          </div>
        </div>
      </div>
    </ElCard>

    <!-- Selected Day Detail -->
    <ElCard v-if="selectedDay && selectedDayEvents.length > 0" shadow="never" class="day-detail-card">
      <h4 class="day-detail-title">{{ selectedDay }} 赛事详情</h4>
      <div class="day-detail-list">
        <div v-for="evt in selectedDayEvents" :key="evt.id" class="day-detail-item">
          <div class="detail-accent" :style="{ background: getEventColor(evt.type) }" />
          <div class="detail-content">
            <div class="detail-title-row">
              <span class="detail-title">{{ evt.title }}</span>
              <ElTag size="small" :style="getEventTagStyle(evt)" effect="plain">
                {{ TYPE_LABELS[evt.type] || evt.type }}
              </ElTag>
              <SSGLStatusTag :status="evt.status" />
            </div>
            <div class="detail-meta">
              <span>{{ formatDate(evt.start_date) }} — {{ formatDate(evt.end_date) }}</span>
              <span v-if="evt.location">{{ evt.location }}</span>
              <span v-if="evt.tags">{{ evt.tags }}</span>
            </div>
          </div>
        </div>
      </div>
    </ElCard>
  </section>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted, watch } from 'vue'
  import { ElMessage } from 'element-plus'
  import { ArrowLeft, ArrowRight } from '@element-plus/icons-vue'
  import { calendarAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import SSGLStatusTag from '@/components/ssgl/SSGLStatusTag.vue'
  import type { CalendarEvent } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Calendar' })

  const WEEKDAYS = ['一', '二', '三', '四', '五', '六', '日']

  const TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
    hackathon:     { bg: 'rgba(45,212,191,0.15)',  text: '#2dd4bf', border: 'rgba(45,212,191,0.4)' },
    innovation:    { bg: 'rgba(96,165,250,0.15)',   text: '#60a5fa', border: 'rgba(96,165,250,0.4)' },
    research:      { bg: 'rgba(167,139,250,0.15)',  text: '#a78bfa', border: 'rgba(167,139,250,0.4)' },
    business_plan: { bg: 'rgba(52,211,153,0.15)',   text: '#34d399', border: 'rgba(52,211,153,0.4)' },
    ai_innovation: { bg: 'rgba(251,113,133,0.15)',  text: '#fb7185', border: 'rgba(251,113,133,0.4)' },
    data_science:  { bg: 'rgba(251,146,60,0.15)',   text: '#fb923c', border: 'rgba(251,146,60,0.4)' },
  }

  const TYPE_LABELS: Record<string, string> = {
    hackathon: '黑客松',
    innovation: '创新赛',
    research: '研究赛',
    business_plan: '商业计划赛',
    ai_innovation: 'AI创新赛',
    data_science: '数据科学赛',
  }

  const now = new Date()
  const currentMonth = ref(`${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`)
  const events = ref<CalendarEvent[]>([])
  const total = ref(0)
  const loading = ref(false)
  const selectedDay = ref<string | null>(null)
  const exporting = ref(false)

  const [year, month] = currentMonth.value.split('-').map(Number)
  const yearRef = computed(() => Number(currentMonth.value.split('-')[0]))
  const monthRef = computed(() => Number(currentMonth.value.split('-')[1]))

  const monthLabel = computed(() => `${yearRef.value}年${monthRef.value}月`)
  const todayStr = new Date().toISOString().slice(0, 10)

  const calendarDays = computed(() => {
    const y = yearRef.value
    const m = monthRef.value
    const firstDay = new Date(y, m - 1, 1)
    let startWeekday = firstDay.getDay() - 1
    if (startWeekday < 0) startWeekday = 6

    const daysInMonth = new Date(y, m, 0).getDate()
    const days: { date: string; day: number; inMonth: boolean }[] = []

    const prevDays = new Date(y, m - 1, 0).getDate()
    for (let i = startWeekday - 1; i >= 0; i--) {
      const d = prevDays - i
      const pm = m - 1 || 12
      const py = m === 1 ? y - 1 : y
      days.push({ date: `${py}-${String(pm).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: false })
    }

    for (let d = 1; d <= daysInMonth; d++) {
      days.push({ date: `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: true })
    }

    const remainder = days.length % 7
    if (remainder !== 0) {
      const fill = 7 - remainder
      for (let d = 1; d <= fill; d++) {
        const nm = m + 1 > 12 ? 1 : m + 1
        const ny = m + 1 > 12 ? y + 1 : y
        days.push({ date: `${ny}-${String(nm).padStart(2, '0')}-${String(d).padStart(2, '0')}`, day: d, inMonth: false })
      }
    }

    return days
  })

  const eventsByDate = computed(() => {
    const map: Record<string, CalendarEvent[]> = {}
    for (const evt of events.value) {
      const start = new Date(evt.start_date)
      const end = new Date(evt.end_date)
      const cursor = new Date(start)
      while (cursor <= end) {
        const key = cursor.toISOString().slice(0, 10)
        if (!map[key]) map[key] = []
        map[key].push(evt)
        cursor.setDate(cursor.getDate() + 1)
      }
    }
    return map
  })

  const selectedDayEvents = computed(() => {
    if (!selectedDay.value) return []
    return eventsByDate.value[selectedDay.value] || []
  })

  function getEventColor(type: string) {
    return TYPE_COLORS[type]?.text || '#2dd4bf'
  }

  function getEventStyle(evt: CalendarEvent) {
    const colors = TYPE_COLORS[evt.type] || TYPE_COLORS.hackathon
    return {
      background: colors.bg,
      color: colors.text,
      borderLeft: `2px solid ${colors.border}`,
    }
  }

  function getEventTagStyle(evt: CalendarEvent) {
    const colors = TYPE_COLORS[evt.type] || TYPE_COLORS.hackathon
    return {
      background: colors.bg,
      color: colors.text,
      borderColor: colors.border,
    }
  }

  function formatDate(s?: string) {
    if (!s) return '—'
    return new Date(s).toLocaleDateString('zh-CN')
  }

  function toggleDay(date: string) {
    selectedDay.value = selectedDay.value === date ? null : date
  }

  function navigateMonth(offset: number) {
    const d = new Date(yearRef.value, monthRef.value - 1 + offset, 1)
    currentMonth.value = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
    selectedDay.value = null
  }

  function prevMonth() { navigateMonth(-1) }
  function nextMonth() { navigateMonth(1) }

  function goToToday() {
    const n = new Date()
    currentMonth.value = `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, '0')}`
    selectedDay.value = todayStr
  }

  async function loadEvents() {
    loading.value = true
    try {
      const res = await calendarAPI.list(currentMonth.value)
      events.value = res.events || []
      total.value = res.total || 0
    } catch {
      ElMessage.error('加载日历数据失败')
    } finally {
      loading.value = false
    }
  }

  async function handleExportICS() {
    exporting.value = true
    try {
      const blob = await calendarAPI.exportICS()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `ssgl_calendar_${new Date().toISOString().slice(0, 10)}.ics`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch {
      ElMessage.error('iCal 导出失败')
    } finally {
      exporting.value = false
    }
  }

  watch(currentMonth, loadEvents)
  onMounted(loadEvents)
</script>

<style scoped lang="scss">
  .month-label {
    font-size: 14px;
    font-weight: 700;
    min-width: 80px;
    text-align: center;
    display: inline-block;
  }

  .legend-bar {
    display: flex;
    gap: 16px;
    align-items: center;
    flex-wrap: wrap;
    padding: 10px 16px;
    margin-bottom: 12px;
    border-radius: 8px;
    background: var(--el-fill-color-lighter);
    border: 1px solid var(--el-border-color-lighter);
  }

  .legend-item {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: var(--art-gray-600);
  }

  .legend-dot {
    width: 10px;
    height: 10px;
    border-radius: 3px;
  }

  .calendar-card {
    overflow: hidden;
    margin-bottom: 16px;
  }

  .calendar-weekdays {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
    border-bottom: 1px solid var(--el-border-color-lighter);
  }

  .weekday-cell {
    padding: 10px 0;
    text-align: center;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: var(--art-gray-500);
  }

  .calendar-grid {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
  }

  .day-cell {
    min-height: 88px;
    padding: 6px;
    border-right: 1px solid var(--el-border-color-lighter);
    border-bottom: 1px solid var(--el-border-color-lighter);
    cursor: pointer;
    transition: background 0.15s;

    &:hover {
      background: var(--el-fill-color-light);
    }

    &.is-today {
      background: rgba(255, 193, 7, 0.08);
    }

    &.is-selected {
      background: var(--el-fill-color);
    }

    &.is-other {
      opacity: 0.35;
    }

    &:nth-child(7n) {
      border-right: none;
    }
  }

  .day-number {
    font-size: 12px;
    font-weight: 500;
    color: var(--art-gray-800);
    margin-bottom: 4px;
    width: 22px;
    height: 22px;
    border-radius: 6px;
    display: flex;
    align-items: center;
    justify-content: center;

    &.is-today-num {
      font-weight: 800;
      color: #fff;
      background: var(--el-color-warning);
    }
  }

  .day-events {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .event-chip {
    font-size: 10px;
    font-weight: 600;
    padding: 1px 5px;
    border-radius: 3px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .event-more {
    font-size: 9px;
    color: var(--art-gray-500);
    padding-left: 5px;
  }

  .day-detail-card {
    margin-top: 16px;
  }

  .day-detail-title {
    margin: 0 0 12px;
    font-size: 14px;
    font-weight: 600;
    color: var(--art-gray-800);
  }

  .day-detail-list {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .day-detail-item {
    display: flex;
    gap: 12px;
    padding: 12px;
    border-radius: 8px;
    background: var(--el-fill-color-lighter);
    border: 1px solid var(--el-border-color-lighter);
  }

  .detail-accent {
    width: 4px;
    min-height: 40px;
    border-radius: 2px;
    flex-shrink: 0;
  }

  .detail-content {
    flex: 1;
  }

  .detail-title-row {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 6px;
    flex-wrap: wrap;
  }

  .detail-title {
    font-size: 15px;
    font-weight: 700;
    color: var(--art-gray-900);
  }

  .detail-meta {
    display: flex;
    gap: 16px;
    font-size: 12px;
    color: var(--art-gray-500);
    flex-wrap: wrap;
  }
</style>
