// frontend-vite/src/pages/feedback.tsx
import { useEffect, useState } from 'react';
import { feedbackAPI, competitionsAPI } from '@/services/api';
import type { CompetitionFeedback, FeedbackSummary } from '@/services/api';
import { Icon } from '@/components/ui/icon';
import { Stars, PageHeader, SectionLabel } from '@/components/ui/page-helpers';
import { toast } from '@/components/ui/toast';
import type { Competition } from '@/types';

// ── Rating Bar Chart ─────────────────────────────────────────
function RatingBar({ label, value, max = 5 }: { label: string; value: number; max?: number }) {
  const pct = (value / max) * 100;
  return (
    <div className="flex items-center gap-3 text-sm">
      <span className="w-20 text-gray-400 text-right">{label}</span>
      <div className="flex-1 h-3 bg-gray-800 rounded-full overflow-hidden">
        <div
          className="h-full rounded-full transition-all duration-500"
          style={{
            width: `${pct}%`,
            background: pct >= 80 ? '#10b981' : pct >= 60 ? '#f59e0b' : '#ef4444',
          }}
        />
      </div>
      <span className="w-10 text-gray-300 font-mono">{value.toFixed(1)}</span>
    </div>
  );
}

// ── Rating Distribution ──────────────────────────────────────
function RatingDistribution({ dist }: { dist: Record<number, number> }) {
  const total = Object.values(dist).reduce((a, b) => a + b, 0);
  return (
    <div className="space-y-2">
      {[5, 4, 3, 2, 1].map((r) => {
        const count = dist[r] || 0;
        const pct = total > 0 ? (count / total) * 100 : 0;
        return (
          <div key={r} className="flex items-center gap-2 text-sm">
            <span className="text-yellow-400 w-12">{r} ★</span>
            <div className="flex-1 h-4 bg-gray-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-yellow-500 rounded-full transition-all"
                style={{ width: `${pct}%` }}
              />
            </div>
            <span className="w-16 text-gray-400 text-right">{count} ({pct.toFixed(0)}%)</span>
          </div>
        );
      })}
    </div>
  );
}

// ── Skill Tags ───────────────────────────────────────────────
function SkillTags({ skills }: { skills: Array<{ skill: string; count: number }> }) {
  if (!skills || skills.length === 0) return <span className="text-gray-500 text-sm">暂无技能标签</span>;
  return (
    <div className="flex flex-wrap gap-2">
      {skills.map((s, i) => (
        <span
          key={i}
          className="px-3 py-1 rounded-full text-xs font-medium bg-indigo-500/20 text-indigo-300 border border-indigo-500/30"
        >
          {s.skill} <span className="text-indigo-400">×{s.count}</span>
        </span>
      ))}
    </div>
  );
}

// ── Star Input ───────────────────────────────────────────────
function StarInput({ value, onChange, label }: { value: number; onChange: (v: number) => void; label: string }) {
  return (
    <div className="flex items-center gap-3">
      <span className="text-sm text-gray-400 w-24">{label}</span>
      <div className="flex gap-1">
        {[1, 2, 3, 4, 5].map((star) => (
          <button
            key={star}
            onClick={() => onChange(star)}
            className="text-xl transition-transform hover:scale-125"
            style={{ color: star <= value ? '#f59e0b' : '#4b5563' }}
          >
            ★
          </button>
        ))}
      </div>
      {value > 0 && <span className="text-xs text-gray-500">{value}/5</span>}
    </div>
  );
}

// ── Main Page ────────────────────────────────────────────────
export default function FeedbackPage() {
  const [competitions, setCompetitions] = useState<Competition[]>([]);
  const [selectedComp, setSelectedComp] = useState<number | null>(null);
  const [summary, setSummary] = useState<FeedbackSummary | null>(null);
  const [feedbacks, setFeedbacks] = useState<CompetitionFeedback[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(false);

  // Form state
  const [overall, setOverall] = useState(0);
  const [content, setContent] = useState(0);
  const [org, setOrg] = useState(0);
  const [fairness, setFairness] = useState(0);
  const [learning, setLearning] = useState(0);
  const [comment, setComment] = useState('');
  const [anonymous, setAnonymous] = useState(false);
  const [skills, setSkills] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    competitionsAPI.list().then((r) => setCompetitions(r.competitions || [])).catch(() => {});
  }, []);

  useEffect(() => {
    if (!selectedComp) return;
    setLoading(true);
    Promise.all([
      feedbackAPI.summary(selectedComp),
      feedbackAPI.listByCompetition(selectedComp),
    ]).then(([s, f]) => {
      setSummary(s);
      setFeedbacks(f.feedbacks || []);
    }).catch(() => {
      toast.error('加载反馈数据失败');
    }).finally(() => setLoading(false));
  }, [selectedComp]);

  const submitFeedback = async () => {
    if (!selectedComp || !overall) {
      toast.error('请至少填写综合评分');
      return;
    }
    setSubmitting(true);
    try {
      await feedbackAPI.submit(selectedComp, {
        competition_id: selectedComp,
        overall_rating: overall,
        content_rating: content || undefined,
        org_rating: org || undefined,
        fairness_rating: fairness || undefined,
        learning_value: learning || undefined,
        comment: comment || undefined,
        anonymous,
        skills: skills ? skills.split(',').map(s => s.trim()).filter(Boolean) : undefined,
      });
      toast.success('反馈提交成功！');
      setShowForm(false);
      setOverall(0); setContent(0); setOrg(0); setFairness(0); setLearning(0);
      setComment(''); setAnonymous(false); setSkills('');
      // Refresh
      if (selectedComp) {
        const [s, f] = await Promise.all([
          feedbackAPI.summary(selectedComp),
          feedbackAPI.listByCompetition(selectedComp),
        ]);
        setSummary(s);
        setFeedbacks(f.feedbacks || []);
      }
    } catch {
      toast.error('提交失败（可能已提交过反馈）');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="p-6 space-y-6">
      <PageHeader title="赛事反馈评价" subtitle="查看和提交赛事评价反馈" icon="📝" />

      {/* Competition Selector */}
      <div className="flex items-center gap-4">
        <SectionLabel value="选择赛事" />
        <select
          className="bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white min-w-[300px]"
          value={selectedComp || ''}
          onChange={(e) => setSelectedComp(Number(e.target.value) || null)}
        >
          <option value="">请选择赛事...</option>
          {competitions.map((c) => (
            <option key={c.id} value={c.id}>{c.title}</option>
          ))}
        </select>
        {selectedComp && (
          <button
            onClick={() => setShowForm(!showForm)}
            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg text-white text-sm transition"
          >
            {showForm ? '取消' : '✨ 提交反馈'}
          </button>
        )}
      </div>

      {/* Feedback Form */}
      {showForm && selectedComp && (
        <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 space-y-4">
          <h3 className="text-lg font-semibold text-white">📝 提交赛事反馈</h3>
          <StarInput label="综合评分*" value={overall} onChange={setOverall} />
          <StarInput label="赛事内容" value={content} onChange={setContent} />
          <StarInput label="组织安排" value={org} onChange={setOrg} />
          <StarInput label="公平性" value={fairness} onChange={setFairness} />
          <StarInput label="学习价值" value={learning} onChange={setLearning} />

          <div className="space-y-2">
            <label className="text-sm text-gray-400">评语</label>
            <textarea
              value={comment}
              onChange={(e) => setComment(e.target.value)}
              className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white h-24 resize-none"
              placeholder="分享您的参赛体验..."
            />
          </div>

          <div className="flex items-center gap-4">
            <div className="flex-1">
              <label className="text-sm text-gray-400">获得技能（逗号分隔）</label>
              <input
                value={skills}
                onChange={(e) => setSkills(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-4 py-2 text-white"
                placeholder="Go, PostgreSQL, 团队协作"
              />
            </div>
            <label className="flex items-center gap-2 text-sm text-gray-400 mt-5">
              <input
                type="checkbox"
                checked={anonymous}
                onChange={(e) => setAnonymous(e.target.checked)}
                className="rounded"
              />
              匿名提交
            </label>
          </div>

          <button
            onClick={submitFeedback}
            disabled={submitting || !overall}
            className="px-6 py-2 bg-green-600 hover:bg-green-700 disabled:opacity-50 rounded-lg text-white font-medium transition"
          >
            {submitting ? '提交中...' : '提交反馈'}
          </button>
        </div>
      )}

      {/* Summary Dashboard */}
      {selectedComp && !loading && summary && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Rating Overview */}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 space-y-4">
            <h3 className="text-lg font-semibold text-white flex items-center gap-2">
              <Icon name="chart" /> 反馈概览
            </h3>
            {summary.total_feedbacks === 0 ? (
              <p className="text-gray-500">暂无反馈数据</p>
            ) : (
              <>
                <div className="text-center py-4">
                  <div className="text-5xl font-bold text-yellow-400">{summary.avg_overall.toFixed(1)}</div>
                  <div className="text-gray-400 text-sm mt-1">综合评分 ({summary.total_feedbacks} 份反馈)</div>
                  <div className="mt-2">
                    <Stars value={Math.round(summary.avg_overall)} />
                  </div>
                </div>
                <div className="space-y-3">
                  <RatingBar label="赛事内容" value={summary.avg_content} />
                  <RatingBar label="组织安排" value={summary.avg_org} />
                  <RatingBar label="公平性" value={summary.avg_fairness} />
                  <RatingBar label="学习价值" value={summary.avg_learning_value} />
                </div>
              </>
            )}
          </div>

          {/* Rating Distribution + Skills */}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-white mb-4">⭐ 评分分布</h3>
              <RatingDistribution dist={summary.rating_distribution || {}} />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white mb-3">🎯 热门技能</h3>
              <SkillTags skills={summary.top_skills || []} />
            </div>
          </div>

          {/* Recent Comments */}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 lg:col-span-2">
            <h3 className="text-lg font-semibold text-white mb-4">💬 最近评语</h3>
            {(!summary.recent_comments || summary.recent_comments.length === 0) ? (
              <p className="text-gray-500">暂无评语</p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {summary.recent_comments.map((c, i) => (
                  <div key={i} className="bg-gray-800 rounded-lg p-4 border border-gray-700">
                    <div className="flex items-center justify-between mb-2">
                      <Stars value={c.rating} />
                      <span className="text-xs text-gray-500">{c.date}</span>
                    </div>
                    <p className="text-gray-300 text-sm">{c.comment || '(无评语)'}</p>
                    {c.anonymous && <span className="text-xs text-gray-500 mt-2 block">匿名用户</span>}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Feedback List */}
      {selectedComp && feedbacks.length > 0 && (
        <div className="bg-gray-900 border border-gray-700 rounded-xl p-6">
          <h3 className="text-lg font-semibold text-white mb-4">📋 全部反馈 ({feedbacks.length})</h3>
          <div className="space-y-3">
            {feedbacks.map((fb) => (
              <div key={fb.id} className="bg-gray-800 rounded-lg p-4 border border-gray-700/50 flex items-start gap-4">
                <div className="text-center">
                  <div className="text-2xl font-bold text-yellow-400">{fb.overall_rating}</div>
                  <div className="text-xs text-gray-500">综合</div>
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-white text-sm font-medium">
                      {fb.anonymous ? '匿名用户' : (fb.student_name || `用户${fb.student_id}`)}
                    </span>
                    <span className="text-xs text-gray-500">{new Date(fb.created_at).toLocaleDateString()}</span>
                  </div>
                  {fb.comment && <p className="text-gray-300 text-sm">{fb.comment}</p>}
                  <div className="flex gap-4 mt-2 text-xs text-gray-500">
                    {fb.content_rating > 0 && <span>内容 {fb.content_rating}★</span>}
                    {fb.org_rating > 0 && <span>组织 {fb.org_rating}★</span>}
                    {fb.fairness_rating > 0 && <span>公平 {fb.fairness_rating}★</span>}
                    {fb.learning_value > 0 && <span>学习 {fb.learning_value}★</span>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {selectedComp && !loading && feedbacks.length === 0 && (
        <div className="text-center py-12 text-gray-500">
          <p className="text-4xl mb-4">📭</p>
          <p>暂无反馈数据，成为第一个提交反馈的人吧！</p>
        </div>
      )}
    </div>
  );
}

// frontend-vue/src/views/ssgl/feedback/index.vue
<template>
  <section class="ssgl-page" data-page="Feedback">
    <SSGLPageHeader title="赛事反馈评价" subtitle="查看和提交赛事评价反馈" />

    <!-- Competition Selector -->
    <div class="flex items-center gap-4 mb-4">
      <span class="text-sm text-gray-500 font-medium whitespace-nowrap">选择赛事</span>
      <ElSelect
        v-model="selectedCompId"
        placeholder="请选择赛事..."
        style="min-width: 300px"
        @change="handleCompChange"
      >
        <ElOption
          v-for="c in competitions"
          :key="c.id"
          :label="c.title"
          :value="c.id"
        />
      </ElSelect>
      <ElButton v-if="selectedCompId" type="primary" @click="showForm = !showForm">
        {{ showForm ? '取消' : '提交反馈' }}
      </ElButton>
    </div>

    <!-- Feedback Form -->
    <ElCard v-if="showForm && selectedCompId" shadow="never" class="mb-4">
      <template #header>
        <span class="font-semibold">提交赛事反馈</span>
      </template>

      <ElForm :model="form" label-width="100px" @submit.prevent="submitFeedback">
        <ElFormItem label="综合评分*" required>
          <ElRate v-model="form.overall" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
        </ElFormItem>
        <ElFormItem label="赛事内容">
          <ElRate v-model="form.content" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
        </ElFormItem>
        <ElFormItem label="组织安排">
          <ElRate v-model="form.org" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
        </ElFormItem>
        <ElFormItem label="公平性">
          <ElRate v-model="form.fairness" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
        </ElFormItem>
        <ElFormItem label="学习价值">
          <ElRate v-model="form.learning" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
        </ElFormItem>
        <ElFormItem label="评语">
          <ElInput
            v-model="form.comment"
            type="textarea"
            :rows="3"
            placeholder="分享您的参赛体验..."
          />
        </ElFormItem>
        <ElRow :gutter="16">
          <ElCol :span="16">
            <ElFormItem label="获得技能">
              <ElInput v-model="form.skills" placeholder="Go, PostgreSQL, 团队协作（逗号分隔）" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="匿名提交">
              <ElSwitch v-model="form.anonymous" />
            </ElFormItem>
          </ElCol>
        </ElRow>
        <ElFormItem>
          <ElButton type="success" :loading="submitting" :disabled="!form.overall" @click="submitFeedback">
            {{ submitting ? '提交中...' : '提交反馈' }}
          </ElButton>
        </ElFormItem>
      </ElForm>
    </ElCard>

    <!-- Loading -->
    <div v-if="dataLoading" class="text-center py-12 text-gray-400">
      <ElIcon class="is-loading" :size="24"><Loading /></ElIcon>
      <div class="mt-2">加载中...</div>
    </div>

    <!-- Summary Dashboard -->
    <template v-if="selectedCompId && !dataLoading && summary">
      <ElRow :gutter="16" class="mb-4">
        <!-- Rating Overview -->
        <ElCol :span="12">
          <ElCard shadow="never">
            <template #header>
              <span class="font-semibold">反馈概览</span>
            </template>

            <div v-if="summary.total_feedbacks === 0" class="text-center py-8 text-gray-400">
              暂无反馈数据
            </div>

            <template v-else>
              <div class="text-center py-4">
                <div class="text-5xl font-bold text-amber-500">{{ summary.avg_overall.toFixed(1) }}</div>
                <div class="text-sm text-gray-400 mt-1">综合评分 ({{ summary.total_feedbacks }} 份反馈)</div>
                <div class="mt-2">
                  <ElRate :model-value="Math.round(summary.avg_overall)" disabled :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
                </div>
              </div>

              <div class="space-y-3 mt-4">
                <div v-for="bar in ratingBars" :key="bar.label">
                  <div class="flex items-center gap-3 text-sm">
                    <span class="w-20 text-gray-400 text-right">{{ bar.label }}</span>
                    <div class="flex-1 h-3 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                      <div
                        class="h-full rounded-full transition-all duration-500"
                        :style="{ width: bar.pct + '%', background: barColor(bar.pct) }"
                      />
                    </div>
                    <span class="w-10 text-gray-500 font-mono text-right">{{ bar.value.toFixed(1) }}</span>
                  </div>
                </div>
              </div>
            </template>
          </ElCard>
        </ElCol>

        <!-- Distribution + Skills -->
        <ElCol :span="12">
          <ElCard shadow="never">
            <template #header>
              <span class="font-semibold">评分分布 & 热门技能</span>
            </template>

            <!-- Rating Distribution -->
            <div class="mb-6">
              <div class="space-y-2">
                <div v-for="r in [5, 4, 3, 2, 1]" :key="r" class="flex items-center gap-2 text-sm">
                  <span class="w-8 text-amber-500 text-right">{{ r }}★</span>
                  <div class="flex-1 h-4 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
                    <div
                      class="h-full bg-amber-500 rounded-full transition-all"
                      :style="{ width: distributionPct(r) + '%' }"
                    />
                  </div>
                  <span class="w-20 text-gray-400 text-right">
                    {{ distributionCount(r) }} ({{ distributionPct(r).toFixed(0) }}%)
                  </span>
                </div>
              </div>
            </div>

            <!-- Skills -->
            <div>
              <div class="text-sm font-semibold text-gray-500 mb-2">热门技能</div>
              <div v-if="!summary.top_skills?.length" class="text-sm text-gray-400">暂无技能标签</div>
              <div v-else class="flex flex-wrap gap-2">
                <ElTag
                  v-for="(s, i) in summary.top_skills"
                  :key="i"
                  type="info"
                  effect="plain"
                  round
                >
                  {{ s.skill }} <span class="ml-1 text-primary">×{{ s.count }}</span>
                </ElTag>
              </div>
            </div>
          </ElCard>
        </ElCol>
      </ElRow>

      <!-- Recent Comments -->
      <ElCard v-if="summary.recent_comments?.length" shadow="never" class="mb-4">
        <template #header>
          <span class="font-semibold">最近评语</span>
        </template>
        <ElRow :gutter="16">
          <ElCol v-for="(c, i) in summary.recent_comments" :key="i" :span="12" class="mb-3">
            <div class="p-4 rounded-lg bg-gray-50 dark:bg-gray-800 border">
              <div class="flex items-center justify-between mb-2">
                <ElRate :model-value="c.rating" disabled size="small" :colors="['#f59e0b', '#f59e0b', '#f59e0b']" />
                <span class="text-xs text-gray-400">{{ c.date }}</span>
              </div>
              <div class="text-sm text-gray-600 dark:text-gray-300">{{ c.comment || '(无评语)' }}</div>
              <div v-if="c.anonymous" class="text-xs text-gray-400 mt-2">匿名用户</div>
            </div>
          </ElCol>
        </ElRow>
      </ElCard>
    </template>

    <!-- Feedback List -->
    <ElCard v-if="selectedCompId && feedbacks.length > 0" shadow="never">
      <template #header>
        <span class="font-semibold">全部反馈 ({{ feedbacks.length }})</span>
      </template>
      <div class="space-y-3">
        <div
          v-for="fb in feedbacks"
          :key="fb.id"
          class="p-4 rounded-lg border border-gray-100 dark:border-gray-700 flex items-start gap-4"
        >
          <div class="text-center flex-shrink-0">
            <div class="text-2xl font-bold text-amber-500">{{ fb.overall_rating }}</div>
            <div class="text-xs text-gray-400">综合</div>
          </div>
          <div class="flex-1 min-w-0">
            <div class="flex items-center gap-2 mb-1">
              <span class="font-medium text-sm">
                {{ fb.anonymous ? '匿名用户' : (fb.student_name || `用户${fb.student_id}`) }}
              </span>
              <span class="text-xs text-gray-400">{{ formatDate(fb.created_at) }}</span>
            </div>
            <div v-if="fb.comment" class="text-sm text-gray-600 dark:text-gray-300 mb-2">{{ fb.comment }}</div>
            <div class="flex gap-4 text-xs text-gray-400">
              <span v-if="fb.content_rating > 0">内容 {{ fb.content_rating }}★</span>
              <span v-if="fb.org_rating > 0">组织 {{ fb.org_rating }}★</span>
              <span v-if="fb.fairness_rating > 0">公平 {{ fb.fairness_rating }}★</span>
              <span v-if="fb.learning_value > 0">学习 {{ fb.learning_value }}★</span>
            </div>
          </div>
        </div>
      </div>
    </ElCard>

    <!-- Empty state when competition selected but no feedback -->
    <div
      v-if="selectedCompId && !dataLoading && feedbacks.length === 0"
      class="text-center py-12 text-gray-400"
    >
      <ElIcon :size="48"><FolderOpened /></ElIcon>
      <div class="mt-3">暂无反馈数据，成为第一个提交反馈的人吧！</div>
    </div>
  </section>
</template>

<script setup lang="ts">
  import { Loading, FolderOpened } from '@element-plus/icons-vue'
  import { feedbackAPI, competitionsAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import type { Competition, CompetitionFeedback, FeedbackSummary } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Feedback' })

  const competitions = ref<Competition[]>([])
  const selectedCompId = ref<number | null>(null)
  const summary = ref<FeedbackSummary | null>(null)
  const feedbacks = ref<CompetitionFeedback[]>([])
  const dataLoading = ref(false)
  const showForm = ref(false)
  const submitting = ref(false)

  const form = reactive({
    overall: 0,
    content: 0,
    org: 0,
    fairness: 0,
    learning: 0,
    comment: '',
    anonymous: false,
    skills: '',
  })

  const ratingBars = computed(() => {
    if (!summary.value) return []
    return [
      { label: '赛事内容', value: summary.value.avg_content, pct: (summary.value.avg_content / 5) * 100 },
      { label: '组织安排', value: summary.value.avg_org, pct: (summary.value.avg_org / 5) * 100 },
      { label: '公平性', value: summary.value.avg_fairness, pct: (summary.value.avg_fairness / 5) * 100 },
      { label: '学习价值', value: summary.value.avg_learning_value, pct: (summary.value.avg_learning_value / 5) * 100 },
    ]
  })

  const barColor = (pct: number) => {
    if (pct >= 80) return '#10b981'
    if (pct >= 60) return '#f59e0b'
    return '#ef4444'
  }

  const distributionCount = (r: number) => {
    return summary.value?.rating_distribution?.[r] || 0
  }

  const distributionPct = (r: number) => {
    if (!summary.value?.rating_distribution) return 0
    const total = Object.values(summary.value.rating_distribution).reduce((a, b) => a + b, 0)
    if (total === 0) return 0
    return ((summary.value.rating_distribution[r] || 0) / total) * 100
  }

  const formatDate = (d: string) => {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('zh-CN')
  }

  const loadCompetitions = async () => {
    try {
      const res = await competitionsAPI.list()
      competitions.value = res.competitions || []
    } catch { /* ignore */ }
  }

  const handleCompChange = async () => {
    if (!selectedCompId.value) {
      summary.value = null
      feedbacks.value = []
      return
    }
    dataLoading.value = true
    try {
      const [s, f] = await Promise.all([
        feedbackAPI.summary(selectedCompId.value),
        feedbackAPI.listByCompetition(selectedCompId.value),
      ])
      summary.value = s as FeedbackSummary
      feedbacks.value = (f as any).feedbacks || []
    } catch {
      ElMessage.error('加载反馈数据失败')
    } finally {
      dataLoading.value = false
    }
  }

  const resetForm = () => {
    form.overall = 0
    form.content = 0
    form.org = 0
    form.fairness = 0
    form.learning = 0
    form.comment = ''
    form.anonymous = false
    form.skills = ''
  }

  const submitFeedback = async () => {
    if (!selectedCompId.value || !form.overall) {
      return ElMessage.warning('请至少填写综合评分')
    }
    submitting.value = true
    try {
      await feedbackAPI.submit(selectedCompId.value, {
        competition_id: selectedCompId.value,
        overall_rating: form.overall,
        content_rating: form.content || undefined,
        org_rating: form.org || undefined,
        fairness_rating: form.fairness || undefined,
        learning_value: form.learning || undefined,
        comment: form.comment || undefined,
        anonymous: form.anonymous,
        skills: form.skills ? form.skills.split(',').map(s => s.trim()).filter(Boolean) : undefined,
      })
      ElMessage.success('反馈提交成功！')
      showForm.value = false
      resetForm()
      // Refresh data
      await handleCompChange()
    } catch {
      ElMessage.error('提交失败（可能已提交过反馈）')
    } finally {
      submitting.value = false
    }
  }

  onMounted(loadCompetitions)
</script>
