// frontend-vite/src/pages/stats.tsx
import { useEffect, useState } from 'react';
import { statsAPI } from '@/services/api';
import { StatCard } from '@/components/ui/stat-card';
import { DonutChart } from '@/components/ui/charts';
import { Avatar, Stars, ProgressBar, PageHeader, SectionLabel } from '@/components/ui/page-helpers';
import { Icon } from '@/components/ui/icon';
import type { StatsOverview, TeacherStat } from '@/types';

interface CompetitionStat {
  id: number;
  title: string;
  status: string;
  team_count: number;
  award_count: number;
  pre_plan_count: number;
}

interface TrendPoint {
  month: string;
  competitions: number;
  teams: number;
  awards: number;
  pre_plans: number;
  prize_amount: number;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const STATUS_LABELS: Record<string, { label: string; color: string; bg: string }> = {
  draft: { label: '草稿', color: 'var(--text-3)', bg: 'var(--surface-2)' },
  published: { label: '已发布', color: 'var(--teal)', bg: 'var(--teal-bg)' },
  ongoing: { label: '进行中', color: 'var(--green)', bg: 'var(--green-bg)' },
  ended: { label: '已结束', color: 'var(--amber)', bg: 'var(--amber-bg)' },
  cancelled: { label: '已取消', color: 'var(--red)', bg: 'var(--red-bg)' },
};

export function StatsPage() {
  const [overview, setOverview] = useState<StatsOverview | null>(null);
  const [teachers, setTeachers] = useState<TeacherStat[]>([]);
  const [competitions, setCompetitions] = useState<CompetitionStat[]>([]);
  const [trends, setTrends] = useState<TrendPoint[]>([]);
  const [typeDistribution, setTypeDistribution] = useState<{ types: { type: string; count: number }[] }>({ types: [] });
  const [recentActivity, setRecentActivity] = useState<{ activities: { action: string; description: string; time: string; icon: string }[] }>({ activities: [] });
  const [studentStats, setStudentStats] = useState<{ total_students: number; students_with_teams: number; students_with_awards: number; avg_team_size: number; top_students: { id: number; name: string; team_count: number; award_count: number; pre_plan_count: number }[] } | null>(null);
  const [engagement, setEngagement] = useState<Record<string, number> | null>(null);
  const [popularity, setPopularity] = useState<{ competitions: { id: number; title: string; type: string; team_count: number; student_count: number; registration_count: number; preplan_count: number; award_count: number; popularity_score: number; rank: number }[]; total: number; formula: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([
      statsAPI.overview(), statsAPI.teachers(), statsAPI.competitions(), statsAPI.trends(),
      statsAPI.typeDistribution(), statsAPI.recentActivity(10), statsAPI.students(),
      statsAPI.engagement().catch(() => null),
      statsAPI.popularity(10).catch(() => null),
    ])
      .then(([o, t, c, tr, td, ra, ss, eg, pop]) => {
        setOverview(o);
        setTeachers(t.teachers || []);
        setCompetitions((c as Record<string, unknown>).competitions as CompetitionStat[] || []);
        setTrends((tr as Record<string, unknown>).trends as TrendPoint[] || []);
        setTypeDistribution(td as { types: { type: string; count: number }[] });
        setRecentActivity(ra as { activities: { action: string; description: string; time: string; icon: string }[] });
        setStudentStats(ss as typeof studentStats);
        setEngagement(eg as Record<string, number> | null);
        setPopularity(pop as typeof popularity);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const handleExport = async (type: 'overview' | 'competitions' | 'teams' | 'full') => {
    setExporting(type);
    try {
      let blob: Blob;
      let filename: string;
      if (type === 'overview') {
        blob = await statsAPI.exportOverview();
        filename = `平台统计_${new Date().toISOString().slice(0, 10)}.csv`;
      } else if (type === 'competitions') {
        blob = await statsAPI.exportCompetitions();
        filename = `赛事明细_${new Date().toISOString().slice(0, 10)}.csv`;
      } else if (type === 'full') {
        blob = await statsAPI.exportFull();
        filename = `全量数据_${new Date().toISOString().slice(0, 10)}.csv`;
      } else {
        blob = await statsAPI.exportTeams();
        filename = `团队数据_${new Date().toISOString().slice(0, 10)}.csv`;
      }
      downloadBlob(blob, filename);
    } catch (e) {
      console.error('Export failed:', e);
    } finally {
      setExporting(null);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 }}>
        <PageHeader title="统计分析" subtitle="平台数据全景 · 实时更新"/>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-ghost btn-sm" onClick={() => handleExport('overview')} disabled={exporting === 'overview'}>
            <Icon name="download" size={14}/> {exporting === 'overview' ? '导出中…' : '导出总览'}
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => handleExport('competitions')} disabled={exporting === 'competitions'}>
            <Icon name="download" size={14}/> {exporting === 'competitions' ? '导出中…' : '导出赛事明细'}
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => handleExport('teams')} disabled={exporting === 'teams'}>
            <Icon name="download" size={14}/> {exporting === 'teams' ? '导出中…' : '导出团队数据'}
          </button>
          <button className="btn btn-ghost btn-sm" onClick={() => handleExport('full')} disabled={exporting === 'full'}>
            <Icon name="download" size={14}/> {exporting === 'full' ? '导出中…' : '全量导出'}
          </button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5,1fr)', gap: 12, marginBottom: 20 }}>
        <div className="anim-in d1"><StatCard label="赛事总数" value={overview?.total_competitions || 0} icon="trophy" color="var(--amber)"/></div>
        <div className="anim-in d2"><StatCard label="参赛团队" value={overview?.total_teams || 0} icon="users" color="var(--teal)"/></div>
        <div className="anim-in d3"><StatCard label="参赛人数" value={overview?.total_users || 0} icon="compass" color="var(--purple)"/></div>
        <div className="anim-in d4"><StatCard label="已发奖项" value={overview?.total_awards || 0} icon="gift" color="var(--green)"/></div>
        <div className="anim-in d5"><StatCard label="进行中" value={overview?.ongoing_competitions || 0} icon="sparkles" color="var(--teal)"/></div>
      </div>

      {/* Trends Area Chart */}
      {trends.length > 0 && (
        <div className="card anim-in d2" style={{ padding: 22, marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
            <SectionLabel label="平台增长趋势"/>
            <span style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{trends.length} 个月</span>
          </div>
          <TrendChart data={trends} />
        </div>
      )}

      {/* Engagement Metrics */}
      {engagement && (
        <div className="card anim-in d2" style={{ overflow: 'hidden', marginBottom: 16 }}>
          <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <SectionLabel label="平台参与度指标"/>
            <span style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>实时</span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 1, background: 'var(--border)' }}>
            {[
              { label: '组队率', value: `${(engagement.team_formation_rate || 0).toFixed(1)}%`, desc: `${engagement.students_with_teams || 0}/${engagement.total_students || 0} 学生`, color: 'var(--teal)' },
              { label: 'AI 评审率', value: `${(engagement.ai_review_rate || 0).toFixed(1)}%`, desc: `${engagement.reviewed_pre_plans || 0}/${engagement.total_pre_plans || 0} 预案`, color: 'var(--purple)' },
              { label: '赛事完成率', value: `${(engagement.completion_rate || 0).toFixed(1)}%`, desc: `${engagement.published_competitions || 0} 已发布`, color: 'var(--amber)' },
              { label: '平均团队规模', value: (engagement.avg_team_size || 0).toFixed(1), desc: `${engagement.total_teams || 0} 个团队`, color: 'var(--green)' },
              { label: '平均预案评分', value: (engagement.avg_pre_plan_score || 0).toFixed(1), desc: 'AI 评审均分', color: 'var(--red)' },
              { label: '进行中赛事', value: String(engagement.active_competitions || 0), desc: `共 ${engagement.total_competitions || 0} 个`, color: 'var(--teal)' },
            ].map((item) => (
              <div key={item.label} style={{ padding: '18px 16px', background: 'var(--surface)', textAlign: 'center' }}>
                <div style={{ fontSize: 11, color: 'var(--text-3)', marginBottom: 8, fontWeight: 600, letterSpacing: '0.05em' }}>{item.label}</div>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: 24, fontWeight: 700, color: item.color, lineHeight: 1 }}>{item.value}</div>
                <div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 6 }}>{item.desc}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Competition Popularity Index */}
      {popularity && popularity.competitions && popularity.competitions.length > 0 && (
        <div className="card anim-in d2" style={{ overflow: 'hidden', marginBottom: 16 }}>
          <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <SectionLabel label="赛事热度指数"/>
              <span style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>Top {popularity.total}</span>
            </div>
            <span style={{ fontSize: 10, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{popularity.formula}</span>
          </div>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--border)', color: 'var(--text-3)', fontSize: 11, fontWeight: 600, letterSpacing: '0.05em' }}>
                  <th style={{ padding: '10px 16px', textAlign: 'left' }}>排名</th>
                  <th style={{ padding: '10px 16px', textAlign: 'left' }}>赛事名称</th>
                  <th style={{ padding: '10px 12px', textAlign: 'center' }}>团队</th>
                  <th style={{ padding: '10px 12px', textAlign: 'center' }}>报名</th>
                  <th style={{ padding: '10px 12px', textAlign: 'center' }}>预案</th>
                  <th style={{ padding: '10px 12px', textAlign: 'center' }}>奖项</th>
                  <th style={{ padding: '10px 16px', textAlign: 'right' }}>热度分</th>
                </tr>
              </thead>
              <tbody>
                {popularity.competitions.map((c) => (
                  <tr key={c.id} style={{ borderBottom: '1px solid var(--border)' }}>
                    <td style={{ padding: '10px 16px' }}>
                      <span style={{
                        display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: 24, height: 24, borderRadius: 6,
                        fontSize: 12, fontWeight: 700,
                        background: c.rank <= 3 ? (c.rank === 1 ? 'rgba(245,158,11,0.15)' : c.rank === 2 ? 'rgba(192,192,192,0.12)' : 'rgba(205,127,50,0.12)') : 'var(--surface-2)',
                        color: c.rank === 1 ? 'var(--amber)' : c.rank === 2 ? '#c0c0c0' : c.rank === 3 ? '#cd7f32' : 'var(--text-3)',
                      }}>{c.rank}</span>
                    </td>
                    <td style={{ padding: '10px 16px', fontWeight: 500, color: 'var(--text)', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.title}</td>
                    <td style={{ padding: '10px 12px', textAlign: 'center', fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--teal)' }}>{c.team_count}</td>
                    <td style={{ padding: '10px 12px', textAlign: 'center', fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--purple)' }}>{c.registration_count}</td>
                    <td style={{ padding: '10px 12px', textAlign: 'center', fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--green)' }}>{c.preplan_count}</td>
                    <td style={{ padding: '10px 12px', textAlign: 'center', fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--amber)' }}>{c.award_count}</td>
                    <td style={{ padding: '10px 16px', textAlign: 'right' }}>
                      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 16, fontWeight: 700, color: 'var(--text)' }}>{c.popularity_score}</span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: '1.6fr 1fr', gap: 16, marginBottom: 16 }}>
        <div className="card anim-in d2" style={{ padding: 22 }}>
          <SectionLabel label="赛事概览"/>
          <div style={{ marginBottom: 14 }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 32, fontWeight: 700, color: 'var(--text)' }}>{overview?.total_competitions || 0}</span>
            <span style={{ fontSize: 12, color: 'var(--text-3)', marginLeft: 8 }}>个赛事</span>
          </div>
          <DonutChart segments={[
            { label: '进行中', value: overview?.ongoing_competitions || 0 },
            { label: '总团队', value: overview?.total_teams || 0 },
            { label: '总用户', value: overview?.total_users || 0 },
          ]}/>
        </div>

        <div className="card anim-in d3" style={{ padding: 22 }}>
          <SectionLabel label="用户分布"/>
          <div style={{ marginBottom: 16 }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 24, fontWeight: 700, color: 'var(--text)' }}>{overview?.total_users || 0}</span>
            <span style={{ fontSize: 12, color: 'var(--text-3)', marginLeft: 8 }}>总用户</span>
          </div>
          {[
            { label: '学生', value: overview?.total_students || 0, color: 'var(--purple)' },
            { label: '教师', value: overview?.total_teachers || 0, color: 'var(--teal)' },
          ].map(({ label, value, color }) => (
            <div key={label} style={{ marginBottom: 12 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5 }}>
                <span style={{ fontSize: 12, color: 'var(--text-2)' }}>{label}</span>
                <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 600, color }}>{value}</span>
              </div>
              <ProgressBar value={value} max={overview?.total_users || 1} color={color} height={7}/>
            </div>
          ))}
        </div>
      </div>

      {/* Competition detail timeline */}
      {competitions.length > 0 && (
        <div className="card anim-in d4" style={{ overflow: 'hidden', marginBottom: 16 }}>
          <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <SectionLabel label="赛事生命周期"/>
            <span style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{competitions.length} 个赛事</span>
          </div>
          <div style={{ padding: 16, display: 'flex', flexDirection: 'column', gap: 10 }}>
            {competitions.map((comp, i) => {
              const st = STATUS_LABELS[comp.status] || STATUS_LABELS.draft;
              const totalActivity = comp.team_count + comp.pre_plan_count + comp.award_count;
              return (
                <div key={comp.id} className={`anim-in d${Math.min(i + 1, 5)}`} style={{
                  display: 'grid', gridTemplateColumns: '1fr 100px 80px 80px 80px', alignItems: 'center',
                  padding: '10px 14px', borderRadius: 10, background: 'var(--surface)',
                  border: '1px solid var(--border)', gap: 12,
                }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <span style={{
                      fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 10,
                      color: st.color, background: st.bg,
                    }}>{st.label}</span>
                    <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>{comp.title}</span>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 700, color: 'var(--teal)' }}>{comp.team_count}</span>
                    <div style={{ fontSize: 10, color: 'var(--text-3)' }}>团队</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 700, color: 'var(--purple)' }}>{comp.pre_plan_count}</span>
                    <div style={{ fontSize: 10, color: 'var(--text-3)' }}>预案</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 700, color: 'var(--amber)' }}>{comp.award_count}</span>
                    <div style={{ fontSize: 10, color: 'var(--text-3)' }}>奖项</div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'flex-end' }}>
                    <ProgressBar value={totalActivity} max={Math.max(...competitions.map(c => c.team_count + c.pre_plan_count + c.award_count), 1)} color="var(--green)" height={4}/>
                    <span style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', minWidth: 30, textAlign: 'right' }}>{totalActivity}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Type Distribution + Recent Activity */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
        {/* Type Distribution */}
        {typeDistribution.types.length > 0 && (
          <div className="card anim-in d5" style={{ padding: 22 }}>
            <SectionLabel label="赛事类型分布"/>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 12 }}>
              {typeDistribution.types.map((t, i) => {
                const maxCount = Math.max(...typeDistribution.types.map(x => x.count), 1);
                const typeLabels: Record<string, { label: string; color: string }> = {
                  hackathon: { label: '黑客松', color: 'var(--teal)' },
                  innovation: { label: '创新创业', color: 'var(--amber)' },
                  research: { label: '科研竞赛', color: 'var(--purple)' },
                  business_plan: { label: '商业计划', color: 'var(--green)' },
                  ai_innovation: { label: 'AI创新', color: 'var(--blue)' },
                  data_science: { label: '数据科学', color: 'var(--red)' },
                };
                const info = typeLabels[t.type] || { label: t.type, color: 'var(--text-3)' };
                return (
                  <div key={t.type} className={`anim-in d${Math.min(i + 1, 3)}`}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                      <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-2)' }}>{info.label}</span>
                      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700, color: info.color }}>{t.count}</span>
                    </div>
                    <ProgressBar value={t.count} max={maxCount} color={info.color} height={8}/>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Recent Activity */}
        {recentActivity.activities.length > 0 && (
          <div className="card anim-in d5" style={{ padding: 22 }}>
            <SectionLabel label="最近动态"/>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginTop: 8 }}>
              {recentActivity.activities.slice(0, 8).map((a, i) => (
                <div key={i} className={`anim-in d${Math.min(i + 1, 5)}`} style={{
                  display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px',
                  background: 'var(--surface)', borderRadius: 8, fontSize: 12,
                }}>
                  <span style={{ fontSize: 14 }}>{a.icon || '📌'}</span>
                  <span style={{ flex: 1, color: 'var(--text)', fontWeight: 500 }}>{a.description}</span>
                  <span style={{ color: 'var(--text-3)', fontSize: 11, fontFamily: 'var(--font-mono)', whiteSpace: 'nowrap' }}>{a.time}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Top Students */}
      {studentStats && studentStats.top_students && studentStats.top_students.length > 0 && (
        <div className="card anim-in d5" style={{ overflow: 'hidden', marginBottom: 16 }}>
          <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <SectionLabel label="学生排行榜 Top 10"/>
            <div style={{ display: 'flex', gap: 16, fontSize: 12, color: 'var(--text-3)' }}>
              <span>总学生: <strong style={{ color: 'var(--text)' }}>{studentStats.total_students}</strong></span>
              <span>已组队: <strong style={{ color: 'var(--teal)' }}>{studentStats.students_with_teams}</strong></span>
              <span>已获奖: <strong style={{ color: 'var(--amber)' }}>{studentStats.students_with_awards}</strong></span>
            </div>
          </div>
          <table className="forge-table">
            <thead><tr><th>排名</th><th>学生</th><th>团队数</th><th>获奖数</th><th>预案数</th><th>综合分</th></tr></thead>
            <tbody>
              {studentStats.top_students.map((s, i) => {
                const score = s.award_count * 10 + s.team_count * 3 + s.pre_plan_count;
                return (
                  <tr key={s.id}>
                    <td><span style={{ width: 24, height: 24, borderRadius: 6, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', background: i === 0 ? 'var(--amber-bg)' : i === 1 ? 'var(--surface-2)' : i === 2 ? 'var(--teal-bg)' : 'transparent', fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700, color: i === 0 ? 'var(--amber)' : i === 1 ? 'var(--text-2)' : i === 2 ? 'var(--teal)' : 'var(--text-3)' }}>{i + 1}</span></td>
                    <td><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Avatar name={s.name} size={26} index={i}/><span style={{ fontWeight: 600 }}>{s.name}</span></div></td>
                    <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--teal)' }}>{s.team_count}</span></td>
                    <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--amber)' }}>{s.award_count}</span></td>
                    <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--purple)' }}>{s.pre_plan_count}</span></td>
                    <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--green)' }}>{score}</span></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Teacher leaderboard */}
      {teachers.length > 0 && (
        <div className="card anim-in d6" style={{ overflow: 'hidden' }}>
          <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)' }}>
            <SectionLabel label="教师指导排行"/>
          </div>
          <table className="forge-table">
            <thead><tr><th>排名</th><th>教师</th><th>所属院系</th><th>指导数</th><th>获奖率</th><th>学生评分</th></tr></thead>
            <tbody>
              {[...teachers].sort((a, b) => b.avg_rating - a.avg_rating).map((t, i) => (
                <tr key={t.id}>
                  <td><span style={{ width: 24, height: 24, borderRadius: 6, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', background: i === 0 ? 'var(--amber-bg)' : i === 1 ? 'var(--surface-2)' : 'transparent', fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700, color: i === 0 ? 'var(--amber)' : i === 1 ? 'var(--text-2)' : 'var(--text-3)' }}>{i + 1}</span></td>
                  <td><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><Avatar name={t.name} size={26} index={i}/><span style={{ fontWeight: 600 }}>{t.name}</span></div></td>
                  <td style={{ color: 'var(--text-3)' }}>{t.dept}</td>
                  <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 700, color: 'var(--teal)' }}>{t.guided}</span><span style={{ fontSize: 11, color: 'var(--text-3)' }}> 队</span></td>
                  <td><div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><ProgressBar value={t.win_rate * 100} max={100} color="var(--green)" height={5}/><span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 600, color: 'var(--green)', whiteSpace: 'nowrap' }}>{(t.win_rate * 100).toFixed(0)}%</span></div></td>
                  <td><div style={{ display: 'flex', alignItems: 'center', gap: 6 }}><Stars value={t.avg_rating}/><span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 600, color: 'var(--amber)' }}>{t.avg_rating}</span></div></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

/** Simple SVG area chart for trends data */
function TrendChart({ data }: { data: TrendPoint[] }) {
  const W = 700, H = 200, PAD = 40;
  const chartW = W - PAD * 2;
  const chartH = H - PAD * 2;

  // Data series config
  const series = [
    { key: 'teams' as const, label: '团队', color: 'var(--teal)' },
    { key: 'competitions' as const, label: '赛事', color: 'var(--amber)' },
    { key: 'awards' as const, label: '奖项', color: 'var(--green)' },
  ];

  const maxVal = Math.max(1, ...data.flatMap(d => series.map(s => d[s.key])));

  const toX = (i: number) => PAD + (i / Math.max(data.length - 1, 1)) * chartW;
  const toY = (v: number) => PAD + chartH - (v / maxVal) * chartH;

  return (
    <div style={{ overflowX: 'auto' }}>
      <svg viewBox={`0 0 ${W} ${H}`} style={{ width: '100%', height: 200 }}>
        {/* Grid lines */}
        {[0, 0.25, 0.5, 0.75, 1].map(pct => {
          const y = PAD + chartH * (1 - pct);
          const val = Math.round(maxVal * pct);
          return (
            <g key={pct}>
              <line x1={PAD} y1={y} x2={W - PAD} y2={y} stroke="var(--border)" strokeWidth={0.5} />
              <text x={PAD - 6} y={y + 4} textAnchor="end" fontSize={9} fill="var(--text-3)" fontFamily="var(--font-mono)">{val}</text>
            </g>
          );
        })}

        {/* X axis labels */}
        {data.map((d, i) => (
          i % Math.max(1, Math.floor(data.length / 6)) === 0 && (
            <text key={i} x={toX(i)} y={H - 4} textAnchor="middle" fontSize={9} fill="var(--text-3)" fontFamily="var(--font-mono)">
              {d.month.slice(5)}
            </text>
          )
        ))}

        {/* Area fills + lines */}
        {series.map(s => {
          const linePath = data.map((d, i) => `${i === 0 ? 'M' : 'L'} ${toX(i)} ${toY(d[s.key])}`).join(' ');
          const areaPath = `${linePath} L ${toX(data.length - 1)} ${PAD + chartH} L ${PAD} ${PAD + chartH} Z`;
          return (
            <g key={s.key}>
              <path d={areaPath} fill={s.color} opacity={0.08} />
              <path d={linePath} fill="none" stroke={s.color} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" />
              {/* Dots */}
              {data.map((d, i) => (
                <circle key={i} cx={toX(i)} cy={toY(d[s.key])} r={2.5} fill={s.color} />
              ))}
            </g>
          );
        })}
      </svg>

      {/* Legend */}
      <div style={{ display: 'flex', gap: 20, justifyContent: 'center', marginTop: 8 }}>
        {series.map(s => (
          <div key={s.key} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <div style={{ width: 12, height: 3, borderRadius: 2, background: s.color }} />
            <span style={{ fontSize: 11, color: 'var(--text-3)' }}>{s.label}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// frontend-vue/src/views/ssgl/stats/index.vue
<template>
  <section class="ssgl-page" data-page="Stats">
    <div v-if="loading" class="ssgl-loading">
      <ElIcon class="is-loading" :size="32"><Loading /></ElIcon>
    </div>

    <template v-else>
      <SSGLPageHeader title="统计分析" subtitle="平台数据全景 · 实时更新">
        <template #actions>
          <ElDropdown @command="handleExport">
            <ElButton :loading="!!exporting">
              <ElIcon><Download /></ElIcon>
              导出数据
            </ElButton>
            <template #dropdown>
              <ElDropdownMenu>
                <ElDropdownItem command="overview">导出总览</ElDropdownItem>
                <ElDropdownItem command="competitions">导出赛事明细</ElDropdownItem>
                <ElDropdownItem command="teams">导出团队数据</ElDropdownItem>
                <ElDropdownItem command="full">全量导出</ElDropdownItem>
              </ElDropdownMenu>
            </template>
          </ElDropdown>
        </template>
      </SSGLPageHeader>

      <!-- Overview Cards -->
      <ElRow :gutter="12" class="ssgl-mb-16">
        <ElCol :span="4" v-for="(card, i) in overviewCards" :key="i">
          <SSGLStatCard :label="card.label" :value="card.value" />
        </ElCol>
      </ElRow>

      <!-- Engagement Metrics -->
      <ElCard v-if="engagement" shadow="never" class="ssgl-mb-16">
        <template #header><span class="card-title">平台参与度指标</span></template>
        <ElRow :gutter="1">
          <ElCol v-for="item in engagementItems" :key="item.label" :span="4">
            <div class="engagement-cell">
              <div class="engagement-label">{{ item.label }}</div>
              <div class="engagement-value" :style="{ color: item.color }">{{ item.value }}</div>
              <div class="engagement-desc">{{ item.desc }}</div>
            </div>
          </ElCol>
        </ElRow>
      </ElCard>

      <!-- Popularity Index -->
      <ElCard v-if="popularity.length > 0" shadow="never" class="ssgl-mb-16">
        <template #header>
          <div class="card-header-row">
            <span class="card-title">赛事热度指数 Top {{ popularity.length }}</span>
            <span class="card-subtitle">{{ popularityFormula }}</span>
          </div>
        </template>
        <ElTable :data="popularity" stripe size="small">
          <ElTableColumn label="排名" width="60" align="center">
            <template #default="{ row }">
              <span class="rank-badge" :class="{ 'rank-top': row.rank <= 3 }">{{ row.rank }}</span>
            </template>
          </ElTableColumn>
          <ElTableColumn prop="title" label="赛事名称" show-overflow-tooltip />
          <ElTableColumn prop="team_count" label="团队" width="80" align="center" />
          <ElTableColumn prop="registration_count" label="报名" width="80" align="center" />
          <ElTableColumn prop="preplan_count" label="预案" width="80" align="center" />
          <ElTableColumn prop="award_count" label="奖项" width="80" align="center" />
          <ElTableColumn label="热度分" width="100" align="right">
            <template #default="{ row }">
              <span class="score-value">{{ row.popularity_score }}</span>
            </template>
          </ElTableColumn>
        </ElTable>
      </ElCard>

      <!-- Competition Lifecycle -->
      <ElCard v-if="competitions.length > 0" shadow="never" class="ssgl-mb-16">
        <template #header><span class="card-title">赛事生命周期 ({{ competitions.length }} 个赛事)</span></template>
        <div v-for="comp in competitions" :key="comp.id" class="lifecycle-item">
          <div class="lifecycle-header">
            <ElTag :type="statusTagType(comp.status)" size="small">{{ statusLabel(comp.status) }}</ElTag>
            <span class="lifecycle-title">{{ comp.title }}</span>
            <span class="lifecycle-stats">
              <span class="stat-teal">{{ comp.team_count }} 团队</span>
              <span class="stat-purple">{{ comp.pre_plan_count }} 预案</span>
              <span class="stat-amber">{{ comp.award_count }} 奖项</span>
            </span>
          </div>
        </div>
      </ElCard>

      <!-- Type Distribution + Recent Activity -->
      <ElRow :gutter="16" class="ssgl-mb-16">
        <ElCol :span="12">
          <ElCard v-if="typeDistribution.length > 0" shadow="never">
            <template #header><span class="card-title">赛事类型分布</span></template>
            <div v-for="t in typeDistribution" :key="t.type" class="type-item">
              <div class="type-header">
                <span class="type-label">{{ typeLabels[t.type] || t.type }}</span>
                <span class="type-count" :style="{ color: typeColors[t.type] || 'var(--art-gray-500)' }">{{ t.count }}</span>
              </div>
              <ElProgress :percentage="Math.round((t.count / maxTypeCount) * 100)" :stroke-width="8" :show-text="false" />
            </div>
          </ElCard>
        </ElCol>
        <ElCol :span="12">
          <ElCard v-if="recentActivities.length > 0" shadow="never">
            <template #header><span class="card-title">最近动态</span></template>
            <div v-for="(a, i) in recentActivities.slice(0, 8)" :key="i" class="activity-item">
              <span class="activity-detail">{{ a.detail }}</span>
              <span class="activity-time">{{ a.created_at }}</span>
            </div>
          </ElCard>
        </ElCol>
      </ElRow>

      <!-- Top Students -->
      <ElCard v-if="topStudents.length > 0" shadow="never" class="ssgl-mb-16">
        <template #header>
          <div class="card-header-row">
            <span class="card-title">学生排行榜 Top 10</span>
            <span class="card-subtitle">
              总学生: {{ studentStatsData?.total_students }} &middot;
              已组队: {{ studentStatsData?.students_with_teams }} &middot;
              已获奖: {{ studentStatsData?.students_with_awards }}
            </span>
          </div>
        </template>
        <ElTable :data="topStudents" stripe size="small">
          <ElTableColumn label="排名" width="60" align="center">
            <template #default="{ $index }">
              <span class="rank-badge" :class="{ 'rank-top': $index < 3 }">{{ $index + 1 }}</span>
            </template>
          </ElTableColumn>
          <ElTableColumn prop="name" label="学生" />
          <ElTableColumn prop="team_count" label="团队数" width="80" align="center" />
          <ElTableColumn prop="award_count" label="获奖数" width="80" align="center" />
          <ElTableColumn prop="pre_plan_count" label="预案数" width="80" align="center" />
          <ElTableColumn label="综合分" width="100" align="right">
            <template #default="{ row }">
              <span class="score-value">{{ row.award_count * 10 + row.team_count * 3 + row.pre_plan_count }}</span>
            </template>
          </ElTableColumn>
        </ElTable>
      </ElCard>

      <!-- Teacher Leaderboard -->
      <ElCard v-if="teachers.length > 0" shadow="never">
        <template #header><span class="card-title">教师评价排行</span></template>
        <ElTable :data="sortedTeachers" stripe size="small">
          <ElTableColumn label="排名" width="60" align="center">
            <template #default="{ $index }">
              <span class="rank-badge" :class="{ 'rank-top': $index < 3 }">{{ $index + 1 }}</span>
            </template>
          </ElTableColumn>
          <ElTableColumn prop="name" label="教师" />
          <ElTableColumn label="评价数" width="80" align="center">
            <template #default="{ row }">{{ row.evaluation_count }}</template>
          </ElTableColumn>
          <ElTableColumn label="教学质量" width="90" align="center">
            <template #default="{ row }">{{ row.avg_teaching?.toFixed(1) }}</template>
          </ElTableColumn>
          <ElTableColumn label="沟通交流" width="90" align="center">
            <template #default="{ row }">{{ row.avg_communication?.toFixed(1) }}</template>
          </ElTableColumn>
          <ElTableColumn label="可及性" width="90" align="center">
            <template #default="{ row }">{{ row.avg_availability?.toFixed(1) }}</template>
          </ElTableColumn>
          <ElTableColumn label="综合评分" width="100" align="right">
            <template #default="{ row }">
              <span class="score-value">{{ row.avg_overall?.toFixed(1) }}</span>
            </template>
          </ElTableColumn>
        </ElTable>
      </ElCard>
    </template>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Download } from '@element-plus/icons-vue'
import { statsAPI } from '@/api/ssgl'
import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
import SSGLStatCard from '@/components/ssgl/SSGLStatCard.vue'
import type {
  StatsOverview,
  TeacherStat,
  CompetitionStat,
  TrendPoint,
  TypeDistributionItem,
  ActivityItem,
  StudentStats,
  EngagementStats,
} from '@/types/ssgl'

defineOptions({ name: 'SSGL_Stats' })

const loading = ref(true)
const exporting = ref<string | null>(null)
const overview = ref<StatsOverview | null>(null)
const teachers = ref<TeacherStat[]>([])
const competitions = ref<CompetitionStat[]>([])
const trends = ref<TrendPoint[]>([])
const typeDistribution = ref<TypeDistributionItem[]>([])
const recentActivities = ref<ActivityItem[]>([])
const studentStatsData = ref<StudentStats | null>(null)
const engagement = ref<EngagementStats | null>(null)
const popularity = ref<Array<{
  id: number; title: string; type: string; team_count: number
  student_count: number; registration_count: number; preplan_count: number
  award_count: number; popularity_score: number; rank: number
}>>([])
const popularityFormula = ref('')

const topStudents = computed(() => studentStatsData.value?.top_students || [])
const sortedTeachers = computed(() => [...teachers.value].sort((a, b) => b.avg_overall - a.avg_overall))

const overviewCards = computed(() => [
  { label: '赛事总数', value: overview.value?.total_competitions ?? 0 },
  { label: '参赛团队', value: overview.value?.total_teams ?? 0 },
  { label: '参赛人数', value: overview.value?.total_users ?? 0 },
  { label: '已发奖项', value: overview.value?.total_awards ?? 0 },
  { label: '进行中', value: overview.value?.ongoing_competitions ?? 0 },
])

const engagementItems = computed(() => {
  if (!engagement.value) return []
  const e = engagement.value
  return [
    { label: '组队率', value: `${(e.team_formation_rate || 0).toFixed(1)}%`, desc: `${e.students_with_teams || 0}/${e.total_students || 0} 学生`, color: 'var(--el-color-primary)' },
    { label: 'AI 评审率', value: `${(e.ai_review_rate || 0).toFixed(1)}%`, desc: `${e.reviewed_pre_plans || 0}/${e.total_pre_plans || 0} 预案`, color: '#a855f7' },
    { label: '赛事完成率', value: `${(e.completion_rate || 0).toFixed(1)}%`, desc: `${e.published_competitions || 0} 已发布`, color: '#f59e0b' },
    { label: '平均团队规模', value: (e.avg_team_size || 0).toFixed(1), desc: `${e.total_teams || 0} 个团队`, color: '#22c55e' },
    { label: '平均预案评分', value: (e.avg_pre_plan_score || 0).toFixed(1), desc: 'AI 评审均分', color: '#ef4444' },
    { label: '进行中赛事', value: String(e.active_competitions || 0), desc: `共 ${e.total_competitions || 0} 个`, color: '#3b82f6' },
  ]
})

const maxTypeCount = computed(() => Math.max(...typeDistribution.value.map((t) => t.count), 1))

const typeLabels: Record<string, string> = {
  hackathon: '黑客松', innovation: '创新创业', research: '科研竞赛',
  business_plan: '商业计划', ai_innovation: 'AI创新', data_science: '数据科学',
}

const typeColors: Record<string, string> = {
  hackathon: '#14b8a6', innovation: '#f59e0b', research: '#a855f7',
  business_plan: '#22c55e', ai_innovation: '#3b82f6', data_science: '#ef4444',
}

function statusLabel(status: string) {
  const map: Record<string, string> = { draft: '草稿', published: '已发布', ongoing: '进行中', ended: '已结束', cancelled: '已取消' }
  return map[status] || status
}

function statusTagType(status: string) {
  const map: Record<string, string> = { ongoing: 'success', published: 'warning', ended: 'info', cancelled: 'danger', draft: 'info' }
  return map[status] || 'info'
}

async function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

async function handleExport(type: string) {
  exporting.value = type
  try {
    let blob: Blob
    let filename: string
    if (type === 'overview') {
      blob = await statsAPI.exportOverview()
      filename = `平台统计_${new Date().toISOString().slice(0, 10)}.csv`
    } else if (type === 'competitions') {
      blob = await statsAPI.exportCompetitions()
      filename = `赛事明细_${new Date().toISOString().slice(0, 10)}.csv`
    } else if (type === 'full') {
      blob = await statsAPI.exportFull()
      filename = `全量数据_${new Date().toISOString().slice(0, 10)}.csv`
    } else {
      blob = await statsAPI.exportTeams()
      filename = `团队数据_${new Date().toISOString().slice(0, 10)}.csv`
    }
    downloadBlob(blob, filename)
  } catch (e) {
    console.error('Export failed:', e)
  } finally {
    exporting.value = null
  }
}

onMounted(async () => {
  try {
    const [o, t, c, tr, td, ra, ss, eg, pop] = await Promise.all([
      statsAPI.overview(),
      statsAPI.teachers(),
      statsAPI.competitions(),
      statsAPI.trends(),
      statsAPI.typeDistribution(),
      statsAPI.recentActivity(10),
      statsAPI.students(),
      statsAPI.engagement().catch(() => null),
      statsAPI.popularity(10).catch(() => null),
    ])
    overview.value = o
    teachers.value = t.teachers || []
    competitions.value = c.competitions || []
    trends.value = tr.trends || []
    typeDistribution.value = td.types || []
    recentActivities.value = ra.activities || []
    studentStatsData.value = ss
    engagement.value = eg
    if (pop) {
      popularity.value = pop.competitions || []
      popularityFormula.value = pop.formula || ''
    }
  } catch (e) {
    console.error('Stats fetch error:', e)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped lang="scss">
.ssgl-loading {
  display: flex;
  height: 100%;
  align-items: center;
  justify-content: center;
}

.ssgl-mb-16 {
  margin-bottom: 16px;
}

.card-title {
  font-weight: 600;
  font-size: 14px;
}

.card-subtitle {
  font-size: 11px;
  color: var(--art-gray-500);
  font-family: var(--el-font-family-monospace);
}

.card-header-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.engagement-cell {
  text-align: center;
  padding: 16px 8px;
  border-right: 1px solid var(--el-border-color-lighter);

  &:last-child {
    border-right: none;
  }
}

.engagement-label {
  font-size: 11px;
  color: var(--art-gray-500);
  margin-bottom: 8px;
  font-weight: 600;
}

.engagement-value {
  font-size: 22px;
  font-weight: 700;
  font-family: var(--el-font-family-monospace);
}

.engagement-desc {
  font-size: 11px;
  color: var(--art-gray-500);
  margin-top: 4px;
}

.rank-badge {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 700;
  font-family: var(--el-font-family-monospace);
  background: var(--art-gray-100);
  color: var(--art-gray-500);
}

.rank-top {
  background: var(--el-color-primary-light-9);
  color: var(--el-color-primary);
}

.score-value {
  font-family: var(--el-font-family-monospace);
  font-weight: 700;
  font-size: 14px;
}

.lifecycle-item {
  padding: 10px 0;
  border-bottom: 1px solid var(--el-border-color-lighter);

  &:last-child {
    border-bottom: none;
  }
}

.lifecycle-header {
  display: flex;
  align-items: center;
  gap: 10px;
}

.lifecycle-title {
  font-size: 13px;
  font-weight: 600;
  flex: 1;
}

.lifecycle-stats {
  display: flex;
  gap: 12px;
  font-size: 12px;
  font-family: var(--el-font-family-monospace);
}

.stat-teal { color: var(--el-color-primary); }
.stat-purple { color: #a855f7; }
.stat-amber { color: #f59e0b; }

.type-item {
  margin-bottom: 12px;
}

.type-header {
  display: flex;
  justify-content: space-between;
  margin-bottom: 4px;
}

.type-label {
  font-size: 12px;
  font-weight: 600;
  color: var(--art-gray-700);
}

.type-count {
  font-size: 12px;
  font-weight: 700;
  font-family: var(--el-font-family-monospace);
}

.activity-item {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 0;
  border-bottom: 1px solid var(--el-border-color-lighter);

  &:last-child {
    border-bottom: none;
  }
}

.activity-detail {
  flex: 1;
  font-size: 12px;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.activity-time {
  font-size: 11px;
  color: var(--art-gray-500);
  font-family: var(--el-font-family-monospace);
  white-space: nowrap;
}
</style>
