// frontend-vite/src/pages/points.tsx
import { useEffect, useState } from 'react';
import { pointsAPI, type AchievementPoint, type PointsSummary, type PointsLeaderboardEntry } from '@/services/api';
import { Icon } from '@/components/ui/icon';
import { Spinner } from '@/components/ui/spinner';
import { useRole } from '@/hooks/use-role';

const reasonLabels: Record<string, { label: string; icon: string; color: string }> = {
  competition_register: { label: '赛事报名', icon: '📝', color: 'var(--teal)' },
  team_join: { label: '加入团队', icon: '👥', color: 'var(--purple)' },
  preplan_submit: { label: '提交预案', icon: '📄', color: 'var(--amber)' },
  award_received: { label: '获得奖项', icon: '🏆', color: '#f59e0b' },
  evaluation_given: { label: '评价导师', icon: '⭐', color: 'var(--green)' },
  ai_review: { label: 'AI 评审', icon: '🤖', color: '#6366f1' },
  milestone_complete: { label: '里程碑完成', icon: '🎯', color: 'var(--teal)' },
  manual_award: { label: '管理员奖励', icon: '🎁', color: 'var(--amber)' },
  competition_win: { label: '赛事获奖', icon: '🏅', color: '#f59e0b' },
  test: { label: '测试', icon: '🧪', color: 'var(--text-3)' },
};

export function PointsPage() {
  const role = useRole();
  const [summary, setSummary] = useState<PointsSummary | null>(null);
  const [history, setHistory] = useState<AchievementPoint[]>([]);
  const [leaderboard, setLeaderboard] = useState<PointsLeaderboardEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<'overview' | 'history' | 'leaderboard'>('overview');

  useEffect(() => {
    Promise.all([
      pointsAPI.me().catch(() => null),
      pointsAPI.list().catch(() => ({ points: [], total: 0, count: 0 })),
      pointsAPI.leaderboard(20).catch(() => ({ leaderboard: [], count: 0 })),
    ]).then(([sumRes, histRes, lbRes]) => {
      setSummary(sumRes);
      setHistory(histRes.points);
      setLeaderboard(lbRes.leaderboard);
    }).finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '60vh', alignItems: 'center', justifyContent: 'center', gap: 12 }}>
        <Spinner size={28} />
        <span style={{ color: 'var(--text-3)', fontSize: 14 }}>加载积分数据…</span>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <header style={{ marginBottom: 24 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
          <div style={{ width: 32, height: 32, borderRadius: 8, background: 'var(--amber-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--amber)' }}>
            <Icon name="star" size={16} />
          </div>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: 'var(--text)', letterSpacing: '-0.02em' }}>积分成就</h1>
          <span className="badge badge-amber">Achievement Points</span>
        </div>
        <p style={{ fontSize: 13, color: 'var(--text-3)' }}>参与赛事活动获取积分，查看排行榜和积分历史</p>
      </header>

      {/* Summary Cards */}
      {summary && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginBottom: 24 }}>
          <div className="card anim-in d1" style={{ padding: 20, textAlign: 'center' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-3)', marginBottom: 8, letterSpacing: '0.05em' }}>总积分</div>
            <div style={{ fontSize: 36, fontWeight: 800, color: 'var(--amber)' }}>{summary.total_points}</div>
          </div>
          <div className="card anim-in d2" style={{ padding: 20, textAlign: 'center' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-3)', marginBottom: 8, letterSpacing: '0.05em' }}>当前排名</div>
            <div style={{ fontSize: 36, fontWeight: 800, color: 'var(--purple)' }}>#{summary.rank}</div>
          </div>
          <div className="card anim-in d3" style={{ padding: 20, textAlign: 'center' }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-3)', marginBottom: 8, letterSpacing: '0.05em' }}>积分来源</div>
            <div style={{ fontSize: 36, fontWeight: 800, color: 'var(--teal)' }}>{summary.breakdown.length}</div>
          </div>
        </div>
      )}

      {/* Breakdown */}
      {summary && summary.breakdown.length > 0 && (
        <div className="card anim-in d4" style={{ padding: 20, marginBottom: 24 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text)', marginBottom: 14 }}>积分构成</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: 10 }}>
            {summary.breakdown.map((b, i) => {
              const meta = reasonLabels[b.reason] || { label: b.reason, icon: '📌', color: 'var(--text-3)' };
              const maxTotal = Math.max(...summary.breakdown.map(x => x.total), 1);
              const pct = (b.total / maxTotal) * 100;
              return (
                <div key={i} style={{ padding: '12px 14px', borderRadius: 10, background: 'var(--surface)', border: '1px solid var(--border)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                    <span style={{ fontSize: 16 }}>{meta.icon}</span>
                    <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text)' }}>{meta.label}</span>
                    <span style={{ marginLeft: 'auto', fontSize: 14, fontWeight: 700, color: meta.color }}>+{b.total}</span>
                  </div>
                  <div style={{ height: 4, borderRadius: 2, background: 'var(--surface-2)', overflow: 'hidden' }}>
                    <div style={{ height: '100%', width: `${pct}%`, borderRadius: 2, background: meta.color, transition: 'width 0.5s ease' }} />
                  </div>
                  <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 4 }}>{b.count} 次</div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Tabs */}
      <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}>
        {([['overview', '积分总览'], ['history', '积分明细'], ['leaderboard', '排行榜']] as const).map(([key, label]) => (
          <button key={key} className={`btn ${tab === key ? 'btn-primary' : 'btn-ghost'}`} onClick={() => setTab(key as typeof tab)}>
            {label}
          </button>
        ))}
      </div>

      {/* Tab Content */}
      {tab === 'overview' && summary && (
        <div className="card" style={{ padding: 20 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)', marginBottom: 12 }}>积分规则</div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 10 }}>
            {[
              { action: '赛事报名', points: 25, icon: '📝' },
              { action: '加入团队', points: 10, icon: '👥' },
              { action: '提交预案', points: 30, icon: '📄' },
              { action: 'AI 评审通过', points: 20, icon: '🤖' },
              { action: '获得奖项', points: 50, icon: '🏆' },
              { action: '评价导师', points: 5, icon: '⭐' },
            ].map((r, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderRadius: 8, background: 'var(--surface)', border: '1px solid var(--border)' }}>
                <span style={{ fontSize: 20 }}>{r.icon}</span>
                <span style={{ fontSize: 13, color: 'var(--text)', flex: 1 }}>{r.action}</span>
                <span style={{ fontSize: 14, fontWeight: 700, color: 'var(--amber)' }}>+{r.points}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {tab === 'history' && (
        <div className="card" style={{ padding: 20 }}>
          {history.length === 0 ? (
            <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)' }}>
              <div style={{ fontSize: 32, marginBottom: 8 }}>📊</div>
              <div>暂无积分记录</div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {history.map((p) => {
                const meta = reasonLabels[p.reason] || { label: p.reason, icon: '📌', color: 'var(--text-3)' };
                return (
                  <div key={p.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 14px', borderRadius: 8, background: 'var(--surface)', border: '1px solid var(--border)' }}>
                    <span style={{ fontSize: 20 }}>{meta.icon}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>{meta.label}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-3)' }}>{new Date(p.created_at).toLocaleString('zh-CN')}</div>
                    </div>
                    <span style={{ fontSize: 16, fontWeight: 700, color: 'var(--green)' }}>+{p.points}</span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}

      {tab === 'leaderboard' && (
        <div className="card" style={{ padding: 20 }}>
          {leaderboard.length === 0 ? (
            <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)' }}>
              <div style={{ fontSize: 32, marginBottom: 8 }}>🏆</div>
              <div>暂无排行数据</div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              {leaderboard.map((entry, idx) => {
                const isTop3 = idx < 3;
                const medals = ['🥇', '🥈', '🥉'];
                return (
                  <div key={entry.user_id} style={{
                    display: 'flex', alignItems: 'center', gap: 12, padding: '12px 16px', borderRadius: 10,
                    background: isTop3 ? 'rgba(245,158,11,0.06)' : 'var(--surface)',
                    border: `1px solid ${isTop3 ? 'rgba(245,158,11,0.2)' : 'var(--border)'}`,
                  }}>
                    <div style={{
                      width: 32, height: 32, borderRadius: 8,
                      background: isTop3 ? 'var(--amber-bg)' : 'var(--surface-2)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontSize: isTop3 ? 18 : 13, fontWeight: 700,
                      color: isTop3 ? 'var(--amber)' : 'var(--text-3)',
                    }}>
                      {isTop3 ? medals[idx] : `#${idx + 1}`}
                    </div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--text)' }}>{entry.name}</div>
                      <div style={{ fontSize: 11, color: 'var(--text-3)' }}>@{entry.username}</div>
                    </div>
                    <div style={{ fontSize: 18, fontWeight: 800, color: 'var(--amber)', fontFamily: 'var(--font-mono)' }}>
                      {entry.total_points}
                    </div>
                    <span style={{ fontSize: 11, color: 'var(--text-3)' }}>分</span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// frontend-vue/src/views/ssgl/points/index.vue
<template>
  <section class="ssgl-page" data-page="Points">
    <div v-if="loading" class="ssgl-loading">
      <ElIcon class="is-loading" :size="32"><Loading /></ElIcon>
    </div>

    <template v-else>
      <SSGLPageHeader title="积分成就" subtitle="参与赛事活动获取积分，查看排行榜和积分历史" />

      <!-- Summary Cards -->
      <ElRow :gutter="16" class="ssgl-mb-16">
        <ElCol :span="8">
          <ElCard shadow="never" class="summary-card">
            <div class="summary-label">总积分</div>
            <div class="summary-value amber">{{ summary?.total_points ?? 0 }}</div>
          </ElCard>
        </ElCol>
        <ElCol :span="8">
          <ElCard shadow="never" class="summary-card">
            <div class="summary-label">当前排名</div>
            <div class="summary-value purple">#{{ summary?.rank ?? 0 }}</div>
          </ElCard>
        </ElCol>
        <ElCol :span="8">
          <ElCard shadow="never" class="summary-card">
            <div class="summary-label">积分来源</div>
            <div class="summary-value teal">{{ summary?.breakdown?.length ?? 0 }}</div>
          </ElCard>
        </ElCol>
      </ElRow>

      <!-- Breakdown -->
      <ElCard v-if="summary?.breakdown?.length" shadow="never" class="ssgl-mb-16">
        <template #header><span class="card-title">积分构成</span></template>
        <ElRow :gutter="12">
          <ElCol v-for="b in summary.breakdown" :key="b.reason" :span="6">
            <ElCard shadow="hover" class="breakdown-card">
              <div class="breakdown-header">
                <span class="breakdown-label">{{ reasonLabels[b.reason]?.label || b.reason }}</span>
                <span class="breakdown-value" :style="{ color: reasonLabels[b.reason]?.color || '#909399' }">+{{ b.total }}</span>
              </div>
              <ElProgress :percentage="Math.round((b.total / maxBreakdownTotal) * 100)" :stroke-width="4" :show-text="false" />
              <div class="breakdown-count">{{ b.count }} 次</div>
            </ElCard>
          </ElCol>
        </ElRow>
      </ElCard>

      <!-- Tabs -->
      <ElTabs v-model="activeTab" class="ssgl-mb-16">
        <ElTabPane label="积分规则" name="overview">
          <ElCard shadow="never">
            <ElRow :gutter="12">
              <ElCol v-for="rule in pointsRules" :key="rule.action" :span="8">
                <div class="rule-item">
                  <span class="rule-action">{{ rule.action }}</span>
                  <span class="rule-points">+{{ rule.points }}</span>
                </div>
              </ElCol>
            </ElRow>
          </ElCard>
        </ElTabPane>

        <ElTabPane label="积分明细" name="history">
          <ElCard shadow="never">
            <div v-if="history.length === 0" class="ssgl-empty">暂无积分记录</div>
            <div v-else class="history-list">
              <div v-for="p in history" :key="p.id" class="history-item">
                <div class="history-info">
                  <div class="history-label">{{ reasonLabels[p.reason]?.label || p.reason }}</div>
                  <div class="history-time">{{ new Date(p.created_at).toLocaleString('zh-CN') }}</div>
                </div>
                <span class="history-points">+{{ p.points }}</span>
              </div>
            </div>
          </ElCard>
        </ElTabPane>

        <ElTabPane label="排行榜" name="leaderboard">
          <ElCard shadow="never">
            <div v-if="leaderboard.length === 0" class="ssgl-empty">暂无排行数据</div>
            <div v-else class="leaderboard-list">
              <div v-for="(entry, idx) in leaderboard" :key="entry.user_id" class="leaderboard-item" :class="{ 'leaderboard-top': idx < 3 }">
                <div class="leaderboard-rank" :class="{ 'rank-top3': idx < 3 }">
                  <span v-if="idx < 3">
                    <ElIcon :size="18"><Medal /></ElIcon>
                  </span>
                  <span v-else>#{{ idx + 1 }}</span>
                </div>
                <div class="leaderboard-info">
                  <div class="leaderboard-name">{{ entry.name }}</div>
                  <div class="leaderboard-username">@{{ entry.username }}</div>
                </div>
                <div class="leaderboard-score">{{ entry.total_points }}</div>
                <span class="leaderboard-unit">分</span>
              </div>
            </div>
          </ElCard>
        </ElTabPane>
      </ElTabs>
    </template>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Medal } from '@element-plus/icons-vue'
import { pointsAPI } from '@/api/ssgl'
import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
import type { AchievementPoint, PointsSummary, PointsLeaderboardEntry } from '@/types/ssgl'

defineOptions({ name: 'SSGL_Points' })

const loading = ref(true)
const activeTab = ref('overview')
const summary = ref<PointsSummary | null>(null)
const history = ref<AchievementPoint[]>([])
const leaderboard = ref<PointsLeaderboardEntry[]>([])

const reasonLabels: Record<string, { label: string; color: string }> = {
  competition_register: { label: '赛事报名', color: '#14b8a6' },
  team_join: { label: '加入团队', color: '#a855f7' },
  preplan_submit: { label: '提交预案', color: '#f59e0b' },
  award_received: { label: '获得奖项', color: '#f59e0b' },
  evaluation_given: { label: '评价导师', color: '#22c55e' },
  ai_review: { label: 'AI 评审', color: '#6366f1' },
  milestone_complete: { label: '里程碑完成', color: '#14b8a6' },
  manual_award: { label: '管理员奖励', color: '#f59e0b' },
  competition_win: { label: '赛事获奖', color: '#f59e0b' },
  test: { label: '测试', color: '#909399' },
}

const maxBreakdownTotal = computed(() => Math.max(...(summary.value?.breakdown || []).map((b) => b.total), 1))

const pointsRules = [
  { action: '赛事报名', points: 25 },
  { action: '加入团队', points: 10 },
  { action: '提交预案', points: 30 },
  { action: 'AI 评审通过', points: 20 },
  { action: '获得奖项', points: 50 },
  { action: '评价导师', points: 5 },
]

onMounted(async () => {
  try {
    const [sumRes, histRes, lbRes] = await Promise.all([
      pointsAPI.me().catch(() => ({ total_points: 0, rank: 0, breakdown: [] })),
      pointsAPI.list().catch(() => ({ points: [], total: 0, count: 0 })),
      pointsAPI.leaderboard(20).catch(() => ({ leaderboard: [], count: 0 })),
    ])
    summary.value = sumRes
    history.value = histRes.points || []
    leaderboard.value = lbRes.leaderboard || []
  } catch (e) {
    console.error('Points fetch error:', e)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped lang="scss">
.ssgl-loading {
  display: flex;
  height: 100%;
  align-items: center;
  justify-content: center;
}

.ssgl-mb-16 {
  margin-bottom: 16px;
}

.ssgl-empty {
  padding: 40px 0;
  text-align: center;
  color: var(--art-gray-500);
}

.card-title {
  font-weight: 600;
  font-size: 14px;
}

.summary-card {
  text-align: center;

  :deep(.el-card__body) {
    padding: 20px;
  }
}

.summary-label {
  font-size: 11px;
  font-weight: 600;
  color: var(--art-gray-500);
  margin-bottom: 8px;
  letter-spacing: 0.05em;
}

.summary-value {
  font-size: 36px;
  font-weight: 800;
  font-family: var(--el-font-family-monospace);

  &.amber { color: #f59e0b; }
  &.purple { color: #a855f7; }
  &.teal { color: #14b8a6; }
}

.breakdown-card {
  margin-bottom: 12px;

  :deep(.el-card__body) {
    padding: 12px 14px;
  }
}

.breakdown-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 8px;
}

.breakdown-label {
  font-size: 12px;
  font-weight: 600;
}

.breakdown-value {
  font-size: 14px;
  font-weight: 700;
  font-family: var(--el-font-family-monospace);
}

.breakdown-count {
  font-size: 10px;
  color: var(--art-gray-500);
  margin-top: 4px;
}

.rule-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 14px;
  border-radius: 8px;
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-lighter);
  margin-bottom: 8px;
}

.rule-action {
  font-size: 13px;
}

.rule-points {
  font-size: 14px;
  font-weight: 700;
  color: #f59e0b;
  font-family: var(--el-font-family-monospace);
}

.history-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.history-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 10px 14px;
  border-radius: 8px;
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-lighter);
}

.history-info {
  flex: 1;
}

.history-label {
  font-size: 13px;
  font-weight: 600;
}

.history-time {
  font-size: 11px;
  color: var(--art-gray-500);
}

.history-points {
  font-size: 16px;
  font-weight: 700;
  color: #22c55e;
  font-family: var(--el-font-family-monospace);
}

.leaderboard-list {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.leaderboard-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px 16px;
  border-radius: 10px;
  background: var(--el-fill-color-lighter);
  border: 1px solid var(--el-border-color-lighter);

  &.leaderboard-top {
    background: rgba(245, 158, 11, 0.06);
    border-color: rgba(245, 158, 11, 0.2);
  }
}

.leaderboard-rank {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background: var(--el-fill-color);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 13px;
  font-weight: 700;
  color: var(--art-gray-500);

  &.rank-top3 {
    background: var(--el-color-primary-light-9);
    color: var(--el-color-primary);
  }
}

.leaderboard-info {
  flex: 1;
}

.leaderboard-name {
  font-size: 14px;
  font-weight: 600;
}

.leaderboard-username {
  font-size: 11px;
  color: var(--art-gray-500);
}

.leaderboard-score {
  font-size: 18px;
  font-weight: 800;
  color: #f59e0b;
  font-family: var(--el-font-family-monospace);
}

.leaderboard-unit {
  font-size: 11px;
  color: var(--art-gray-500);
}
</style>
