// frontend-vue/src/views/ssgl/competitions/index.vue
<template>
  <section class="ssgl-page" data-page="Competitions">
    <SSGLPageHeader
      :title="role === 'student' ? '赛事大厅' : '赛事管理'"
      :subtitle="`共 ${competitions.length} 个赛事`"
    >
      <template v-if="canManage" #actions>
        <ElButton type="primary" :icon="Plus" @click="openCreate">创建赛事</ElButton>
        <ElButton :icon="Download" @click="showImport = !showImport">批量导入</ElButton>
      </template>
    </SSGLPageHeader>

    <!-- Batch Import Panel -->
    <ElCard v-if="canManage && showImport" shadow="never" class="import-card">
      <h4>批量导入赛事</h4>
      <p class="import-hint">输入 JSON 数组，每项包含 title、type、start_date、end_date 等字段。</p>
      <ElInput
        v-model="importJson"
        type="textarea"
        :rows="5"
        placeholder='[{"title":"示例赛事","type":"hackathon","start_date":"2026-07-01","end_date":"2026-08-01"}]'
      />
      <div class="import-actions">
        <ElButton :loading="importing" @click="handleBatchImport">开始导入</ElButton>
        <span v-if="importResult" :class="importResult.error_count > 0 ? 'text-warning' : 'text-success'">
          成功 {{ importResult.created_count }} 个，失败 {{ importResult.error_count }} 个
        </span>
      </div>
    </ElCard>

    <!-- Filters -->
    <div class="filter-bar">
      <ElRadioGroup v-model="statusFilter" size="small">
        <ElRadioButton value="all">全部</ElRadioButton>
        <ElRadioButton value="ongoing">进行中</ElRadioButton>
        <ElRadioButton value="published">报名中</ElRadioButton>
        <ElRadioButton value="completed">已结束</ElRadioButton>
        <ElRadioButton value="draft">草稿</ElRadioButton>
      </ElRadioGroup>
      <ElSelect v-model="typeFilter" placeholder="所有类型" clearable size="small" style="width: 140px">
        <ElOption value="all" label="所有类型" />
        <ElOption value="hackathon" label="Hackathon" />
        <ElOption value="innovation" label="创新赛" />
        <ElOption value="research" label="研究赛" />
        <ElOption value="business_plan" label="商业计划赛" />
        <ElOption value="ai_innovation" label="AI创新赛" />
        <ElOption value="data_science" label="数据科学赛" />
      </ElSelect>
      <ElInput
        v-model="search"
        :prefix-icon="Search"
        placeholder="搜索赛事名称…"
        clearable
        size="small"
        style="max-width: 240px"
      />
    </div>

    <!-- Table -->
    <ElTable v-loading="loading" :data="filtered" stripe border style="width: 100%">
      <ElTableColumn prop="title" label="赛事名称" min-width="180" show-overflow-tooltip />
      <ElTableColumn prop="type" label="类型" width="120">
        <template #default="{ row }">
          <ElTag size="small" :type="typeTagMap[row.type] || 'info'" effect="plain">
            {{ typeLabels[row.type] || row.type }}
          </ElTag>
        </template>
      </ElTableColumn>
      <ElTableColumn prop="status" label="状态" width="100">
        <template #default="{ row }">
          <SSGLStatusTag :status="row.status" />
        </template>
      </ElTableColumn>
      <ElTableColumn label="队伍人数" width="110" align="center">
        <template #default="{ row }">
          {{ row.min_team_size }}-{{ row.max_team_size }}人
        </template>
      </ElTableColumn>
      <ElTableColumn prop="teams_count" label="已报名" width="80" align="center" />
      <ElTableColumn label="报名截止" width="120">
        <template #default="{ row }">
          {{ formatDate(row.registration_deadline) }}
        </template>
      </ElTableColumn>
      <ElTableColumn label="起止时间" width="200">
        <template #default="{ row }">
          {{ formatDate(row.start_date) }} ~ {{ formatDate(row.end_date) }}
        </template>
      </ElTableColumn>
      <ElTableColumn prop="location" label="地点" width="120" show-overflow-tooltip />
      <ElTableColumn prop="prize" label="奖金" width="100" show-overflow-tooltip />
      <ElTableColumn label="操作" width="200" fixed="right">
        <template #default="{ row }">
          <ElButton v-if="canManage && row.status === 'draft'" type="success" link size="small" @click="handlePublish(row)">
            发布
          </ElButton>
          <ElButton v-if="canManage" type="primary" link size="small" @click="openEdit(row)">编辑</ElButton>
          <ElButton v-if="canManage" type="danger" link size="small" @click="handleDelete(row)">删除</ElButton>
        </template>
      </ElTableColumn>
    </ElTable>

    <!-- Create / Edit Dialog -->
    <ElDialog
      v-model="dialogVisible"
      :title="isEditing ? '编辑赛事' : '创建赛事'"
      width="620px"
      destroy-on-close
    >
      <ElForm ref="formRef" :model="form" label-width="100px" :rules="formRules">
        <ElFormItem label="赛事名称" prop="title" required>
          <ElInput v-model="form.title" placeholder="例如：2026 校园创新马拉松" />
        </ElFormItem>
        <ElRow :gutter="16">
          <ElCol :span="8">
            <ElFormItem label="类型" prop="type" required>
              <ElSelect v-model="form.type" style="width: 100%">
                <ElOption v-for="opt in TYPE_OPTIONS" :key="opt.value" :value="opt.value" :label="opt.label" />
              </ElSelect>
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="最小人数" prop="min_team_size">
              <ElInputNumber v-model="form.min_team_size" :min="1" :max="99" style="width: 100%" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="最大人数" prop="max_team_size">
              <ElInputNumber v-model="form.max_team_size" :min="1" :max="99" style="width: 100%" />
            </ElFormItem>
          </ElCol>
        </ElRow>
        <ElFormItem label="赛事简介">
          <ElInput v-model="form.description" type="textarea" :rows="3" placeholder="一句话介绍赛事主题与目标" />
        </ElFormItem>
        <ElRow :gutter="16">
          <ElCol :span="8">
            <ElFormItem label="报名截止">
              <ElDatePicker v-model="form.registration_deadline" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width: 100%" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="开始时间" prop="start_date" required>
              <ElDatePicker v-model="form.start_date" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width: 100%" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="结束时间" prop="end_date" required>
              <ElDatePicker v-model="form.end_date" type="datetime" value-format="YYYY-MM-DDTHH:mm:ssZ" style="width: 100%" />
            </ElFormItem>
          </ElCol>
        </ElRow>
        <ElRow :gutter="16">
          <ElCol :span="8">
            <ElFormItem label="地点">
              <ElInput v-model="form.location" placeholder="线上 / 教学楼…" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="奖金">
              <ElInput v-model="form.prize" placeholder="如 ¥50,000" />
            </ElFormItem>
          </ElCol>
          <ElCol :span="8">
            <ElFormItem label="标签">
              <ElInput v-model="form.tags" placeholder="逗号分隔" />
            </ElFormItem>
          </ElCol>
        </ElRow>
      </ElForm>
      <template #footer>
        <ElButton @click="dialogVisible = false">取消</ElButton>
        <ElButton type="primary" :loading="submitting" @click="handleSubmit">
          {{ isEditing ? '保存' : '创建' }}
        </ElButton>
      </template>
    </ElDialog>
  </section>
</template>

<script setup lang="ts">
  import { ref, reactive, computed, onMounted } from 'vue'
  import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
  import { Plus, Download, Search } from '@element-plus/icons-vue'
  import { competitionsAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import SSGLStatusTag from '@/components/ssgl/SSGLStatusTag.vue'
  import { useUserStore } from '@/store/modules/user'
  import type { Competition } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Competitions' })

  const userStore = useUserStore()
  const role = computed(() => userStore.info.role || '')
  const canManage = computed(() => ['teacher', 'admin'].includes(role.value))

  // State
  const loading = ref(false)
  const competitions = ref<Competition[]>([])
  const statusFilter = ref('all')
  const typeFilter = ref('all')
  const search = ref('')

  // Dialog
  const dialogVisible = ref(false)
  const isEditing = ref(false)
  const editingId = ref<number | null>(null)
  const submitting = ref(false)
  const formRef = ref<FormInstance>()

  // Import
  const showImport = ref(false)
  const importJson = ref('')
  const importing = ref(false)
  const importResult = ref<{ created_count: number; error_count: number; errors: Array<{ index: number; title: string; message: string }> } | null>(null)

  const TYPE_OPTIONS = [
    { value: 'hackathon', label: 'Hackathon' },
    { value: 'innovation', label: '创新赛' },
    { value: 'research', label: '研究赛' },
    { value: 'business_plan', label: '商业计划赛' },
    { value: 'ai_innovation', label: 'AI创新赛' },
    { value: 'data_science', label: '数据科学赛' },
  ]

  const typeLabels: Record<string, string> = {
    hackathon: 'Hackathon',
    innovation: '创新赛',
    research: '研究赛',
    business_plan: '商业计划赛',
    ai_innovation: 'AI创新赛',
    data_science: '数据科学赛',
  }

  const typeTagMap: Record<string, '' | 'success' | 'warning' | 'info' | 'danger'> = {
    hackathon: 'warning',
    innovation: '',
    research: 'success',
    business_plan: 'info',
    ai_innovation: 'danger',
    data_science: 'success',
  }

  const emptyForm = () => ({
    title: '',
    type: 'hackathon' as Competition['type'],
    description: '',
    max_team_size: 4,
    min_team_size: 1,
    registration_deadline: '',
    start_date: '',
    end_date: '',
    location: '',
    prize: '',
    tags: '',
  })

  const form = reactive(emptyForm())

  const formRules: FormRules = {
    title: [{ required: true, message: '请填写赛事名称', trigger: 'blur' }],
    type: [{ required: true, message: '请选择类型', trigger: 'change' }],
    start_date: [{ required: true, message: '请选择开始时间', trigger: 'change' }],
    end_date: [{ required: true, message: '请选择结束时间', trigger: 'change' }],
  }

  const filtered = computed(() => {
    return competitions.value
      .filter(c => {
        if (statusFilter.value !== 'all' && c.status !== statusFilter.value) return false
        if (typeFilter.value !== 'all' && typeFilter.value && c.type !== typeFilter.value) return false
        if (search.value && !c.title.includes(search.value)) return false
        return true
      })
      .sort((a, b) => {
        const order = ['ongoing', 'published', 'completed', 'draft', 'cancelled']
        return order.indexOf(a.status) - order.indexOf(b.status)
      })
  })

  function formatDate(s?: string) {
    if (!s) return '—'
    return new Date(s).toLocaleDateString('zh-CN')
  }

  async function loadCompetitions() {
    loading.value = true
    try {
      const res = await competitionsAPI.list()
      competitions.value = res.competitions || []
    } catch {
      ElMessage.error('加载赛事列表失败')
    } finally {
      loading.value = false
    }
  }

  function openCreate() {
    isEditing.value = false
    editingId.value = null
    Object.assign(form, emptyForm())
    dialogVisible.value = true
  }

  function openEdit(comp: Competition) {
    isEditing.value = true
    editingId.value = comp.id
    Object.assign(form, {
      title: comp.title,
      type: comp.type,
      description: comp.description || '',
      max_team_size: comp.max_team_size || 4,
      min_team_size: comp.min_team_size || 1,
      registration_deadline: comp.registration_deadline || '',
      start_date: comp.start_date || '',
      end_date: comp.end_date || '',
      location: comp.location || '',
      prize: comp.prize || '',
      tags: comp.tags || '',
    })
    dialogVisible.value = true
  }

  async function handleSubmit() {
    try {
      await formRef.value?.validate()
    } catch {
      return
    }

    submitting.value = true
    try {
      const payload = { ...form }
      if (isEditing.value && editingId.value) {
        const res = await competitionsAPI.update(editingId.value, payload)
        const idx = competitions.value.findIndex(c => c.id === editingId.value)
        if (idx >= 0) competitions.value[idx] = res.competition
        ElMessage.success('赛事已更新')
      } else {
        const res = await competitionsAPI.create(payload)
        competitions.value.unshift(res.competition)
        ElMessage.success('赛事已创建（草稿）')
      }
      dialogVisible.value = false
    } catch (err: any) {
      ElMessage.error(err?.response?.data?.error || '操作失败')
    } finally {
      submitting.value = false
    }
  }

  async function handlePublish(comp: Competition) {
    try {
      const res = await competitionsAPI.publish(comp.id)
      const idx = competitions.value.findIndex(c => c.id === comp.id)
      if (idx >= 0) competitions.value[idx] = res.competition
      ElMessage.success('赛事已发布')
    } catch (err: any) {
      ElMessage.error(err?.response?.data?.error || '发布失败')
    }
  }

  async function handleDelete(comp: Competition) {
    try {
      await ElMessageBox.confirm(`确认删除赛事「${comp.title}」？此操作不可撤销。`, '确认删除', {
        confirmButtonText: '删除',
        cancelButtonText: '取消',
        type: 'warning',
      })
      await competitionsAPI.delete(comp.id)
      competitions.value = competitions.value.filter(c => c.id !== comp.id)
      ElMessage.success('赛事已删除')
    } catch (err: any) {
      if (err !== 'cancel') {
        ElMessage.error(err?.response?.data?.error || '删除失败')
      }
    }
  }

  async function handleBatchImport() {
    let parsed: Record<string, unknown>[]
    try {
      parsed = JSON.parse(importJson.value)
      if (!Array.isArray(parsed)) {
        ElMessage.error('请输入 JSON 数组')
        return
      }
    } catch {
      ElMessage.error('JSON 格式错误')
      return
    }

    importing.value = true
    importResult.value = null
    try {
      const res = await competitionsAPI.batchImport(parsed)
      importResult.value = res
      if (res.created_count > 0) {
        ElMessage.success(`成功导入 ${res.created_count} 个赛事`)
        await loadCompetitions()
      }
      if (res.error_count > 0) {
        ElMessage.warning(`${res.error_count} 个赛事导入失败`)
      }
    } catch {
      ElMessage.error('导入失败')
    } finally {
      importing.value = false
    }
  }

  onMounted(loadCompetitions)
</script>

<style scoped lang="scss">
  .filter-bar {
    display: flex;
    gap: 12px;
    align-items: center;
    flex-wrap: wrap;
    margin-bottom: 16px;
  }

  .import-card {
    margin-bottom: 16px;

    h4 {
      margin: 0 0 8px;
      font-size: 15px;
      font-weight: 600;
    }

    .import-hint {
      margin: 0 0 12px;
      font-size: 13px;
      color: var(--art-gray-600);
    }

    .import-actions {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-top: 12px;
    }
  }

  .text-success {
    color: var(--el-color-success);
    font-size: 13px;
  }

  .text-warning {
    color: var(--el-color-warning);
    font-size: 13px;
  }
</style>

// frontend-vite/src/pages/competitions.tsx
import { useEffect, useState } from 'react';
import { competitionsAPI } from '@/services/api';
import { useRole } from '@/hooks/use-role';
import { StatusBadge, TypeBadge } from '@/components/ui/badge';
import { Icon } from '@/components/ui/icon';
import { PageHeader } from '@/components/ui/page-helpers';
import { EmptyState } from '@/components/ui/empty-state';
import type { Competition } from '@/types';
import { Modal } from '@/components/ui/modal';
import { Button } from '@/components/ui/button';
import { FormModal, Field, TextInput, TextArea, NumberInput, Select, DateTimeInput } from '@/components/ui/form';
import { toast } from '@/components/ui/toast';
import { getApiError } from '@/lib/form-utils';
import { TeamForm } from '@/pages/teams';

const TYPE_ICONS: Record<string, string> = { hackathon: 'trophy', innovation: 'zap', research: 'target' };
const STATUS_ORDER = ['ongoing', 'published', 'completed', 'draft', 'cancelled'];

const TYPE_OPTIONS = [
  { value: 'hackathon', label: 'Hackathon' },
  { value: 'innovation', label: '创新赛' },
  { value: 'research', label: '研究赛' },
];

type CompFormState = {
  title: string; type: string; description: string;
  max_team_size: string; min_team_size: string;
  registration_deadline: string; start_date: string; end_date: string;
  location: string; prize: string; tags: string;
};

function emptyCompForm(): CompFormState {
  return { title: '', type: 'hackathon', description: '', max_team_size: '4', min_team_size: '1', registration_deadline: '', start_date: '', end_date: '', location: '', prize: '', tags: '' };
}

function CompetitionForm({ onClose, initial, onSaved, onDeleted }: {
  onClose: () => void;
  initial: Competition | null;
  onSaved: (comp: Competition, isNew: boolean) => void;
  onDeleted: (id: number) => void;
}) {
  const isEdit = !!initial;
  const [form, setForm] = useState<CompFormState>(() => initial ? {
    title: initial.title, type: initial.type, description: initial.description || '',
    max_team_size: String(initial.max_team_size || 4), min_team_size: String(initial.min_team_size || 1),
    registration_deadline: initial.registration_deadline || '', start_date: initial.start_date || '', end_date: initial.end_date || '',
    location: initial.location || '', prize: initial.prize || '', tags: initial.tags || '',
  } : emptyCompForm());
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const set = (k: keyof CompFormState) => (v: string) => setForm((f) => ({ ...f, [k]: v }));

  const submit = async () => {
    if (!form.title.trim()) { setError('请填写赛事名称'); return; }
    if (!form.start_date || !form.end_date) { setError('请填写开始与结束时间'); return; }
    setSubmitting(true); setError(null);
    const payload = {
      title: form.title.trim(),
      type: form.type as Competition['type'],
      description: form.description,
      max_team_size: Number(form.max_team_size) || 1,
      min_team_size: Number(form.min_team_size) || 1,
      registration_deadline: form.registration_deadline,
      start_date: form.start_date,
      end_date: form.end_date,
      location: form.location,
      prize: form.prize,
      tags: form.tags,
    };
    try {
      const res = isEdit
        ? await competitionsAPI.update(initial!.id, payload)
        : await competitionsAPI.create(payload);
      toast.success(isEdit ? '赛事已更新' : '赛事已创建（草稿）');
      onSaved(res.competition, !isEdit);
      onClose();
    } catch (err) {
      setError(getApiError(err, isEdit ? '更新失败' : '创建失败'));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <FormModal open={true} onClose={onClose} title={isEdit ? '编辑赛事' : '创建赛事'} onSubmit={submit} submitting={submitting} error={error} submitLabel={isEdit ? '保存' : '创建'} width={620}>
      <Field label="赛事名称" required><TextInput value={form.title} onChange={(e) => set('title')(e.target.value)} placeholder="例如：2026 校园创新马拉松" /></Field>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
        <Field label="类型" required><Select value={form.type} onChange={set('type')} options={TYPE_OPTIONS} /></Field>
        <Field label="最小队伍人数" required><NumberInput min={1} value={form.min_team_size} onChange={(e) => set('min_team_size')(e.target.value)} /></Field>
        <Field label="最大队伍人数" required><NumberInput min={1} value={form.max_team_size} onChange={(e) => set('max_team_size')(e.target.value)} /></Field>
      </div>
      <Field label="赛事简介"><TextArea value={form.description} onChange={(e) => set('description')(e.target.value)} placeholder="一句话介绍赛事主题与目标" /></Field>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
        <Field label="报名截止"><DateTimeInput value={form.registration_deadline} onChange={set('registration_deadline')} /></Field>
        <Field label="开始时间" required><DateTimeInput value={form.start_date} onChange={set('start_date')} /></Field>
        <Field label="结束时间" required><DateTimeInput value={form.end_date} onChange={set('end_date')} /></Field>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12 }}>
        <Field label="地点"><TextInput value={form.location} onChange={(e) => set('location')(e.target.value)} placeholder="线上 / 教学楼…" /></Field>
        <Field label="奖金"><TextInput value={form.prize} onChange={(e) => set('prize')(e.target.value)} placeholder="如 ¥50,000" /></Field>
        <Field label="标签"><TextInput value={form.tags} onChange={(e) => set('tags')(e.target.value)} placeholder="逗号分隔" /></Field>
      </div>
      {isEdit && (
        <div style={{ marginTop: 4, paddingTop: 12, borderTop: '1px solid var(--border)' }}>
          <Button type="button" variant="danger" size="sm" onClick={async () => {
            if (!confirm(`确认删除赛事「${initial!.title}」？此操作不可撤销。`)) return;
            try {
              await competitionsAPI.delete(initial!.id);
              toast.success('赛事已删除');
              onDeleted(initial!.id);
              onClose();
            } catch (err) {
              toast.error(getApiError(err, '删除失败'));
            }
          }}>删除赛事</Button>
        </div>
      )}
    </FormModal>
  );
}

export function CompetitionsPage() {
  const role = useRole();
  const [competitions, setCompetitions] = useState<Competition[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [search, setSearch] = useState('');

  useEffect(() => {
    competitionsAPI.list().then(res => setCompetitions(res.competitions || [])).catch(console.error).finally(() => setLoading(false));
  }, []);

  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Competition | null>(null);
  const [detailId, setDetailId] = useState<number | null>(null);
  const [detail, setDetail] = useState<Competition | null>(null);
  const [registerComp, setRegisterComp] = useState<Competition | null>(null);
  const canManage = role === 'teacher' || role === 'admin';

  const handleSaved = (comp: Competition, isNew: boolean) =>
    setCompetitions((prev) => (isNew ? [comp, ...prev] : prev.map((c) => (c.id === comp.id ? comp : c))));
  const handleDeleted = (id: number) =>
    setCompetitions((prev) => prev.filter((c) => c.id !== id));

  const openCreate = () => { setEditing(null); setFormOpen(true); };
  const openEdit = (comp: Competition) => { setEditing(comp); setFormOpen(true); };

  const openDetail = async (comp: Competition) => {
    setDetailId(comp.id); setDetail(comp);
    try {
      const res = await competitionsAPI.get(comp.id);
      setDetail(res.competition);
    } catch { /* 保底用列表项数据 */ }
  };

  const publish = async (comp: Competition) => {
    try {
      const res = await competitionsAPI.publish(comp.id);
      toast.success('赛事已发布');
      handleSaved(res.competition, false);
    } catch (err) {
      toast.error(getApiError(err, '发布失败'));
    }
  };

  const filtered = competitions.filter(c => {
    if (filter !== 'all' && c.status !== filter) return false;
    if (typeFilter !== 'all' && c.type !== typeFilter) return false;
    if (search && !c.title.includes(search)) return false;
    return true;
  }).sort((a, b) => STATUS_ORDER.indexOf(a.status) - STATUS_ORDER.indexOf(b.status));

  const daysLeft = (dateStr: string) => Math.max(0, Math.ceil((new Date(dateStr).getTime() - Date.now()) / 86400000));

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <PageHeader
        title={role === 'student' ? '赛事大厅' : '赛事管理'}
        subtitle={`共 ${competitions.length} 个赛事，${filtered.length} 个符合筛选`}
        actions={canManage ? <Button variant="primary" icon={<Icon name="plus" size={13}/>} onClick={openCreate}>创建赛事</Button> : undefined}
      />

      {/* Filters */}
      <div className="anim-in" style={{ display: 'flex', gap: 10, marginBottom: 20, flexWrap: 'wrap', alignItems: 'center' }}>
        <div style={{ display: 'flex', gap: 4, padding: 4, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)' }}>
          {[
            { k: 'all', l: '全部' }, { k: 'ongoing', l: '进行中' }, { k: 'published', l: '报名中' },
            { k: 'completed', l: '已结束' }, { k: 'draft', l: '草稿' },
          ].map(({ k, l }) => (
            <button key={k} onClick={() => setFilter(k)} style={{
              padding: '5px 12px', borderRadius: 7, fontSize: 12, fontWeight: 600,
              background: filter === k ? 'var(--surface)' : 'transparent',
              color: filter === k ? 'var(--amber)' : 'var(--text-3)',
              border: filter === k ? '1px solid var(--border)' : '1px solid transparent',
              cursor: 'pointer', transition: 'all 0.15s',
              boxShadow: filter === k ? 'var(--shadow-sm)' : 'none',
            }}>{l}</button>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 4, padding: 4, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)' }}>
          {[
            { k: 'all', l: '所有类型' }, { k: 'hackathon', l: 'Hackathon' },
            { k: 'innovation', l: '创新赛' }, { k: 'research', l: '研究赛' },
          ].map(({ k, l }) => (
            <button key={k} onClick={() => setTypeFilter(k)} style={{
              padding: '5px 12px', borderRadius: 7, fontSize: 12, fontWeight: 600,
              background: typeFilter === k ? 'var(--surface)' : 'transparent',
              color: typeFilter === k ? 'var(--teal)' : 'var(--text-3)',
              border: typeFilter === k ? '1px solid var(--border)' : '1px solid transparent',
              cursor: 'pointer', transition: 'all 0.15s',
            }}>{l}</button>
          ))}
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, height: 34, padding: '0 12px', borderRadius: 8, background: 'var(--surface)', border: '1px solid var(--border)', flex: 1, maxWidth: 260 }}>
          <Icon name="search" size={13}/>
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索赛事名称…"
            style={{ border: 'none', outline: 'none', background: 'transparent', fontSize: 13, color: 'var(--text)', width: '100%' }}/>
        </div>
      </div>

      {filtered.length === 0 ? (
        <EmptyState icon="trophy" title="没有符合条件的赛事" desc="尝试调整筛选条件"/>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(340px, 1fr))', gap: 14 }}>
          {filtered.map((comp, i) => {
            const regDays = daysLeft(comp.registration_deadline);
            const endDays = daysLeft(comp.end_date);
            const accent = { hackathon: 'var(--amber)', innovation: 'var(--purple)', research: 'var(--teal)' }[comp.type] || 'var(--amber)';
            const accentBg = { hackathon: 'var(--amber-bg)', innovation: 'var(--purple-bg)', research: 'var(--teal-bg)' }[comp.type] || 'var(--amber-bg)';

            return (
              <div key={comp.id} className={`card anim-in d${Math.min(i + 1, 8)}`}
                style={{ padding: 20, cursor: 'pointer', transition: 'all 0.2s' }}
                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = 'var(--shadow)'; e.currentTarget.style.borderColor = accent; }}
                onMouseLeave={e => { e.currentTarget.style.transform = ''; e.currentTarget.style.boxShadow = ''; e.currentTarget.style.borderColor = 'var(--border)'; }}
              >
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12, marginBottom: 14 }}>
                  <div style={{ width: 40, height: 40, borderRadius: 10, background: accentBg, display: 'flex', alignItems: 'center', justifyContent: 'center', color: accent, flexShrink: 0 }}>
                    <Icon name={TYPE_ICONS[comp.type] || 'trophy'} size={18}/>
                  </div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)', lineHeight: 1.3, marginBottom: 6 }}>{comp.title}</div>
                    <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                      <StatusBadge status={comp.status}/>
                      <TypeBadge type={comp.type}/>
                    </div>
                  </div>
                </div>
                {comp.description && (
                  <p style={{ fontSize: 12, color: 'var(--text-3)', lineHeight: 1.6, marginBottom: 14, display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', overflow: 'hidden' }}>
                    {comp.description}
                  </p>
                )}
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10, marginBottom: 14 }}>
                  {[
                    { icon: 'users', val: `${comp.teams_count || 0} 队`, sub: '已报名' },
                    { icon: 'zap', val: comp.prize || '—', sub: '奖金', color: 'var(--amber)' },
                    { icon: 'clock', val: comp.status === 'ongoing' ? `${endDays}天` : `${regDays}天`, sub: comp.status === 'ongoing' ? '截止倒计时' : '报名截止', color: (comp.status === 'ongoing' ? endDays : regDays) <= 7 ? 'var(--red)' : undefined },
                  ].map(({ icon, val, sub, color }) => (
                    <div key={icon} style={{ textAlign: 'center', padding: '8px 6px', borderRadius: 8, background: 'var(--surface-2)' }}>
                      <div style={{ fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700, color: color || 'var(--text)' }}>{val}</div>
                      <div style={{ fontSize: 10, color: 'var(--text-3)', marginTop: 2 }}>{sub}</div>
                    </div>
                  ))}
                </div>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', paddingTop: 12, borderTop: '1px solid var(--border)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                    <Icon name="compass" size={12}/>
                    <span style={{ fontSize: 11, color: 'var(--text-3)' }}>{comp.location || '线上'}</span>
                  </div>
                  <div style={{ display: 'flex', gap: 8 }}>
                    {role === 'student' && comp.status === 'published' && (
                      <Button variant="primary" size="sm" onClick={() => setRegisterComp(comp)}>报名参加</Button>
                    )}
                    {canManage && comp.status === 'draft' && (
                      <Button variant="teal" size="sm" onClick={() => publish(comp)}>发布</Button>
                    )}
                    {canManage && (
                      <Button variant="outline" size="sm" icon={<Icon name="edit" size={12}/>} onClick={() => openEdit(comp)} />
                    )}
                    <Button variant="ghost" size="sm" iconRight={<Icon name="right" size={12}/>} onClick={() => openDetail(comp)}>详情</Button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {formOpen && (
        <CompetitionForm onClose={() => setFormOpen(false)} initial={editing} onSaved={handleSaved} onDeleted={handleDeleted} />
      )}

      {registerComp && (
        <TeamForm
          onClose={() => setRegisterComp(null)}
          competitions={[registerComp]}
          fixedCompetition={registerComp}
          onCreated={() => { setRegisterComp(null); toast.success('报名成功，已创建团队'); }}
        />
      )}

      <CompetitionDetail comp={detailId ? detail : null} onClose={() => { setDetailId(null); setDetail(null); }} />
    </div>
  );
}

function CompetitionDetail({ comp, onClose }: { comp: Competition | null; onClose: () => void }) {
  if (!comp) return null;
  const fmt = (s?: string) => (s ? new Date(s).toLocaleString('zh-CN') : '—');
  return (
    <Modal open={!!comp} onClose={onClose} title={comp.title} width={620}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
        <div style={{ display: 'flex', gap: 8 }}>
          <StatusBadge status={comp.status} />
          <TypeBadge type={comp.type} />
        </div>
        {comp.description && <p style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.7 }}>{comp.description}</p>}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
          {[
            { k: '报名截止', v: fmt(comp.registration_deadline) },
            { k: '开始时间', v: fmt(comp.start_date) },
            { k: '结束时间', v: fmt(comp.end_date) },
            { k: '地点', v: comp.location || '线上' },
            { k: '奖金', v: comp.prize || '—' },
            { k: '已报名队伍', v: String(comp.teams_count ?? 0) },
          ].map(({ k, v }) => (
            <div key={k} style={{ padding: '10px 12px', borderRadius: 8, background: 'var(--surface-2)' }}>
              <div style={{ fontSize: 11, color: 'var(--text-3)', marginBottom: 3 }}>{k}</div>
              <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>{v}</div>
            </div>
          ))}
        </div>
      </div>
    </Modal>
  );
}
