// frontend-vue/src/views/ssgl/leaderboard/index.vue
<template>
  <section class="ssgl-page" data-page="Leaderboard">
    <div v-if="loading" class="ssgl-loading">
      <ElIcon class="is-loading" :size="32"><Loading /></ElIcon>
    </div>

    <template v-else>
      <SSGLPageHeader title="团队排行榜" subtitle="基于获奖数、参赛数和预案提交综合评分" />

      <!-- Top 3 Podium -->
      <div v-if="entries.length >= 3" class="podium">
        <div v-for="(entry, idx) in podiumOrder" :key="entry.team_id" class="podium-item" :class="`podium-rank-${entry.rank}`">
          <div class="podium-medal" :style="{ color: medalColors[entry.rank - 1] }">
            <ElIcon :size="32"><Medal /></ElIcon>
          </div>
          <div class="podium-team">{{ entry.team_name }}</div>
          <div class="podium-leader">{{ entry.leader_name }}</div>
          <div class="podium-bar" :style="{ height: `${barHeights[entry.rank - 1]}px`, background: `linear-gradient(180deg, ${medalColors[entry.rank - 1]}33, ${medalColors[entry.rank - 1]}11)`, borderColor: `${medalColors[entry.rank - 1]}44` }">
            <div class="podium-score" :style="{ color: medalColors[entry.rank - 1] }">{{ entry.score }}</div>
            <div class="podium-score-label">综合评分</div>
          </div>
        </div>
      </div>

      <!-- Full Table -->
      <ElCard shadow="never">
        <template #header>
          <span class="card-title">完整排名 ({{ entries.length }} 支团队)</span>
        </template>
        <ElTable :data="entries" stripe size="small">
          <ElTableColumn label="排名" width="70" align="center">
            <template #default="{ row }">
              <span v-if="row.rank <= 3" :style="{ color: medalColors[row.rank - 1] }">
                <ElIcon :size="18"><Medal /></ElIcon>
              </span>
              <span v-else class="rank-num">{{ row.rank }}</span>
            </template>
          </ElTableColumn>
          <ElTableColumn prop="team_name" label="团队" />
          <ElTableColumn prop="leader_name" label="队长">
            <template #default="{ row }">{{ row.leader_name || '—' }}</template>
          </ElTableColumn>
          <ElTableColumn prop="competition_count" label="参赛" width="80" align="center" />
          <ElTableColumn prop="award_count" label="获奖" width="80" align="center" />
          <ElTableColumn prop="pre_plan_count" label="预案" width="80" align="center" />
          <ElTableColumn label="评分" width="100" align="right">
            <template #default="{ row }">
              <span class="score-value" :class="{ 'score-positive': row.score > 0 }">{{ row.score }}</span>
            </template>
          </ElTableColumn>
        </ElTable>
        <div v-if="entries.length === 0" class="ssgl-empty">
          <p>暂无团队数据</p>
        </div>
      </ElCard>
    </template>
  </section>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { Medal } from '@element-plus/icons-vue'
import { statsAPI } from '@/api/ssgl'
import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
import type { LeaderboardEntry } from '@/types/ssgl'

defineOptions({ name: 'SSGL_Leaderboard' })

const loading = ref(true)
const entries = ref<LeaderboardEntry[]>([])

const medalColors = ['#f59e0b', '#14b8a6', '#a855f7']
const barHeights = [180, 140, 120]

const podiumOrder = computed(() => {
  if (entries.value.length < 3) return []
  const [first, second, third] = entries.value
  return [
    { ...second, rank: 2 },
    { ...first, rank: 1 },
    { ...third, rank: 3 },
  ]
})

onMounted(async () => {
  try {
    const data = await statsAPI.leaderboard()
    entries.value = data.leaderboard || []
  } catch (e) {
    console.error('Leaderboard fetch error:', e)
  } finally {
    loading.value = false
  }
})
</script>

<style scoped lang="scss">
.ssgl-loading {
  display: flex;
  height: 100%;
  align-items: center;
  justify-content: center;
}

.ssgl-empty {
  padding: 48px 20px;
  text-align: center;
  color: var(--art-gray-500);
}

.card-title {
  font-weight: 600;
  font-size: 14px;
}

.podium {
  display: flex;
  gap: 16px;
  justify-content: center;
  margin-bottom: 32px;
}

.podium-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  width: 160px;
}

.podium-medal {
  display: flex;
  align-items: center;
  justify-content: center;
}

.podium-team {
  font-size: 14px;
  font-weight: 700;
  text-align: center;
}

.podium-leader {
  font-size: 11px;
  color: var(--art-gray-500);
}

.podium-bar {
  width: 100%;
  border-radius: 8px 8px 0 0;
  border: 1px solid;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 4px;
}

.podium-score {
  font-size: 28px;
  font-weight: 700;
  font-family: var(--el-font-family-monospace);
}

.podium-score-label {
  font-size: 10px;
  color: var(--art-gray-500);
}

.rank-num {
  font-family: var(--el-font-family-monospace);
  font-size: 13px;
  font-weight: 700;
  color: var(--art-gray-500);
}

.score-value {
  font-family: var(--el-font-family-monospace);
  font-size: 15px;
  font-weight: 700;
  color: var(--art-gray-400);
}

.score-positive {
  color: var(--el-color-primary);
}
</style>

// frontend-vite/src/pages/leaderboard.tsx
import { useEffect, useState, useRef } from 'react';
import gsap from 'gsap';
import { statsAPI } from '@/services/api';
import { Icon } from '@/components/ui/icon';
import type { LeaderboardEntry } from '@/types';

export function LeaderboardPage() {
  const [entries, setEntries] = useState<LeaderboardEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const gridRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    statsAPI.leaderboard()
      .then(data => setEntries(data.leaderboard || []))
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (loading || !gridRef.current) return;
    const raf = requestAnimationFrame(() => {
      const rows = gridRef.current?.querySelectorAll<HTMLElement>('[data-row]');
      if (!rows?.length) return;
      gsap.set(rows, { opacity: 0, x: -20 });
      gsap.to(rows, { opacity: 1, x: 0, duration: 0.4, stagger: 0.04, ease: 'power3.out' });
    });
    return () => cancelAnimationFrame(raf);
  }, [loading]);

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <div style={{ marginBottom: 28 }}>
        <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 4 }}>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--amber)', letterSpacing: '0.1em', textTransform: 'uppercase' }}>
            ◆ LEADERBOARD
          </span>
        </div>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 28, fontWeight: 700, color: 'var(--text)', letterSpacing: '-0.03em' }}>
          团队<span style={{ color: 'var(--amber)' }}>排行榜</span>
        </h1>
        <p style={{ fontSize: 13, color: 'var(--text-3)', marginTop: 4 }}>
          基于获奖数、参赛数和预案提交综合评分
        </p>
      </div>

      {/* Top 3 Podium */}
      {entries.length >= 3 && (
        <div style={{ display: 'flex', gap: 16, marginBottom: 32, justifyContent: 'center' }}>
          {[entries[1], entries[0], entries[2]].map((entry, i) => {
            const rank = i === 0 ? 2 : i === 1 ? 1 : 3;
            const height = rank === 1 ? 180 : rank === 2 ? 140 : 120;
            const colors = ['var(--teal)', 'var(--amber)', 'var(--purple)'];
            return (
              <div key={entry.team_id} style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8,
                width: 160,
              }}>
                <span style={{ color: colors[rank - 1] }}><Icon name="medal" size={32} /></span>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)', textAlign: 'center' }}>
                  {entry.team_name}
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-3)' }}>
                  {entry.leader_name}
                </div>
                <div style={{
                  width: '100%', height, borderRadius: '8px 8px 0 0',
                  background: `linear-gradient(180deg, ${colors[rank - 1]}33, ${colors[rank - 1]}11)`,
                  border: `1px solid ${colors[rank - 1]}44`,
                  display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 4,
                }}>
                  <div style={{ fontFamily: 'var(--font-mono)', fontSize: 28, fontWeight: 700, color: colors[rank - 1] }}>
                    {entry.score}
                  </div>
                  <div style={{ fontSize: 10, color: 'var(--text-3)' }}>综合评分</div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Full Table */}
      <div ref={gridRef} className="card" style={{ overflow: 'hidden' }}>
        <div style={{ padding: '16px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-3)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
            完整排名 ({entries.length} 支团队)
          </span>
        </div>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: '1px solid var(--border)' }}>
              <th style={{ padding: '12px 16px', textAlign: 'left', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>排名</th>
              <th style={{ padding: '12px 16px', textAlign: 'left', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>团队</th>
              <th style={{ padding: '12px 16px', textAlign: 'left', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>队长</th>
              <th style={{ padding: '12px 16px', textAlign: 'center', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>参赛</th>
              <th style={{ padding: '12px 16px', textAlign: 'center', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>获奖</th>
              <th style={{ padding: '12px 16px', textAlign: 'center', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>预案</th>
              <th style={{ padding: '12px 16px', textAlign: 'right', color: 'var(--text-3)', fontWeight: 600, fontSize: 11, letterSpacing: '0.05em' }}>评分</th>
            </tr>
          </thead>
          <tbody>
            {entries.map((entry) => (
              <tr key={entry.team_id} data-row style={{ borderBottom: '1px solid var(--border)', transition: 'background 0.15s' }}
                onMouseEnter={e => { e.currentTarget.style.background = 'var(--surface-2)'; }}
                onMouseLeave={e => { e.currentTarget.style.background = ''; }}
              >
                <td style={{ padding: '14px 16px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    {entry.rank <= 3 ? (
                      <span style={{ color: entry.rank === 1 ? 'var(--amber)' : entry.rank === 2 ? 'var(--teal)' : 'var(--purple)' }}><Icon name="medal" size={18} /></span>
                    ) : (
                      <span style={{
                        fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700,
                        color: entry.rank <= 10 ? 'var(--amber)' : 'var(--text-3)',
                        width: 28, textAlign: 'center',
                      }}>
                        {entry.rank}
                      </span>
                    )}
                  </div>
                </td>
                <td style={{ padding: '14px 16px', fontWeight: 600, color: 'var(--text)' }}>
                  {entry.team_name}
                </td>
                <td style={{ padding: '14px 16px', color: 'var(--text-2)' }}>
                  {entry.leader_name || '—'}
                </td>
                <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                  <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--teal)' }}>{entry.competition_count}</span>
                </td>
                <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                  <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--amber)' }}>{entry.award_count}</span>
                </td>
                <td style={{ padding: '14px 16px', textAlign: 'center' }}>
                  <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--purple)' }}>{entry.pre_plan_count}</span>
                </td>
                <td style={{ padding: '14px 16px', textAlign: 'right' }}>
                  <span style={{
                    fontFamily: 'var(--font-mono)', fontSize: 15, fontWeight: 700,
                    color: entry.score > 0 ? 'var(--amber)' : 'var(--text-3)',
                  }}>
                    {entry.score}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {entries.length === 0 && (
          <div style={{ padding: '48px 20px', textAlign: 'center', color: 'var(--text-3)' }}>
            <Icon name="trophy" size={32} />
            <p style={{ marginTop: 12, fontSize: 13 }}>暂无团队数据</p>
          </div>
        )}
      </div>
    </div>
  );
}
