// frontend-vue/src/views/ssgl/profile/index.vue
<template>
  <section class="ssgl-page" data-page="Profile">
    <!-- Loading -->
    <div v-if="loading" class="loading-wrap">
      <ElIcon :size="32" class="is-loading"><Loading /></ElIcon>
    </div>

    <!-- Not found -->
    <ElEmpty v-else-if="!profile" description="无法加载用户信息" />

    <!-- Content -->
    <template v-else>
      <!-- Header Card -->
      <div class="profile-header">
        <div class="profile-header__avatar-wrap">
          <ElAvatar v-if="profile.avatar" :size="100" :src="profile.avatar" />
          <div v-else class="avatar-placeholder">
            {{ (profile.name || profile.username).charAt(0).toUpperCase() }}
          </div>
          <ElTag
            class="role-badge"
            :type="roleType(profile.role)"
            effect="dark"
            size="small"
            round
          >
            {{ roleLabels[profile.role] || profile.role }}
          </ElTag>
        </div>
        <div class="profile-header__info">
          <h1 class="profile-header__name">{{ profile.name || profile.username }}</h1>
          <p class="profile-header__username">@{{ profile.username }}</p>
          <p v-if="profile.dept" class="profile-header__detail">
            <ElIcon :size="14"><School /></ElIcon>{{ profile.dept }}
          </p>
          <p v-if="profile.student_id" class="profile-header__detail">
            <ElIcon :size="14"><EditPen /></ElIcon>学号: {{ profile.student_id }}
          </p>
          <p v-if="profile.email" class="profile-header__detail">
            <ElIcon :size="14"><Message /></ElIcon>{{ profile.email }}
          </p>
          <p v-if="profile.phone" class="profile-header__detail">
            <ElIcon :size="14"><Phone /></ElIcon>{{ profile.phone }}
          </p>
          <p class="profile-header__detail">
            <ElIcon :size="14"><Calendar /></ElIcon>注册于 {{ profile.created_at }}
          </p>
          <ElButton size="small" @click="editing = !editing" style="margin-top: 8px">
            <ElIcon v-if="!editing" :size="14"><EditPen /></ElIcon>
            {{ editing ? '取消' : '编辑资料' }}
          </ElButton>
        </div>
      </div>

      <!-- Edit Form -->
      <Transition name="el-zoom-in-top">
        <div v-if="editing" class="edit-card">
          <h3 class="section-title">编辑个人信息</h3>
          <ElForm label-position="top">
            <ElRow :gutter="16">
              <ElCol :xs="24" :sm="12">
                <ElFormItem label="姓名">
                  <ElInput v-model="editForm.name" />
                </ElFormItem>
              </ElCol>
              <ElCol :xs="24" :sm="12">
                <ElFormItem label="邮箱">
                  <ElInput v-model="editForm.email" type="email" />
                </ElFormItem>
              </ElCol>
              <ElCol :xs="24" :sm="12">
                <ElFormItem label="手机">
                  <ElInput v-model="editForm.phone" />
                </ElFormItem>
              </ElCol>
              <ElCol :xs="24" :sm="12">
                <ElFormItem label="院系">
                  <ElInput v-model="editForm.dept" />
                </ElFormItem>
              </ElCol>
            </ElRow>
            <div class="edit-actions">
              <ElButton type="primary" :loading="saving" @click="handleSave">
                <ElIcon v-if="!saving" :size="14"><Check /></ElIcon>
                保存
              </ElButton>
              <Transition name="el-fade-in">
                <span v-if="saveMsg" class="save-msg" :class="saveStatus === 'success' ? 'save-msg--ok' : 'save-msg--err'">
                  <ElIcon :size="14">
                    <CircleCheck v-if="saveStatus === 'success'" />
                    <CircleClose v-else />
                  </ElIcon>
                  {{ saveMsg }}
                </span>
              </Transition>
            </div>
          </ElForm>
        </div>
      </Transition>

      <!-- Stats Grid -->
      <div class="stats-section">
        <h3 class="section-title">我的数据</h3>
        <ElRow :gutter="16">
          <ElCol :xs="12" :sm="6" v-for="s in statCards" :key="s.label">
            <div class="stat-card" :style="{ borderTopColor: s.color }">
              <ElIcon :size="28" :style="{ color: s.color }"><component :is="s.icon" /></ElIcon>
              <span class="stat-card__value" :style="{ color: s.color }">{{ s.value }}</span>
              <span class="stat-card__label">{{ s.label }}</span>
            </div>
          </ElCol>
        </ElRow>
      </div>

      <!-- Quick Actions -->
      <div class="actions-section">
        <h3 class="section-title">快捷操作</h3>
        <div class="actions-grid">
          <ElButton v-if="profile.role === 'student'" @click="router.push('/ssgl/teams')">
            <ElIcon><UserFilled /></ElIcon>我的团队
          </ElButton>
          <ElButton v-if="profile.role === 'student'" @click="router.push('/ssgl/preplans')">
            <ElIcon><Document /></ElIcon>我的预案
          </ElButton>
          <ElButton v-if="profile.role === 'student'" @click="router.push('/ssgl/coach')">
            <ElIcon><Microphone /></ElIcon>答辩教练
          </ElButton>
          <ElButton @click="router.push('/ssgl/competitions')">
            <ElIcon><Trophy /></ElIcon>赛事列表
          </ElButton>
          <ElButton @click="router.push('/ssgl/aitools')">
            <ElIcon><ChatDotRound /></ElIcon>AI 工具箱
          </ElButton>
          <ElButton @click="router.push('/ssgl/leaderboard')">
            <ElIcon><Medal /></ElIcon>排行榜
          </ElButton>
          <ElButton @click="router.push('/ssgl/showcase')">
            <ElIcon><Aim /></ElIcon>成果展示
          </ElButton>
        </div>
      </div>
    </template>
  </section>
</template>

<script setup lang="ts">
  import {
    Loading, School, EditPen, Message, Phone, Calendar, Check,
    CircleCheck, CircleClose, UserFilled, Document, Microphone,
    Trophy, ChatDotRound, Medal, Aim,
  } from '@element-plus/icons-vue'
  import { profileAPI } from '@/api/ssgl'
  import type { UserProfile } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Profile' })

  const router = useRouter()

  const roleLabels: Record<string, string> = {
    student: '学生',
    teacher: '教师',
    admin: '管理员',
  }

  const profile = ref<UserProfile | null>(null)
  const loading = ref(true)
  const editing = ref(false)
  const saving = ref(false)
  const saveMsg = ref('')
  const saveStatus = ref<'success' | 'error' | ''>('')
  const editForm = reactive({ name: '', email: '', phone: '', dept: '' })

  const statCards = computed(() => [
    { label: '参与赛事', value: profile.value?.competition_count ?? 0, icon: Trophy, color: '#f59e0b' },
    { label: '加入团队', value: profile.value?.team_count ?? 0, icon: UserFilled, color: '#4a9eff' },
    { label: '提交预案', value: profile.value?.pre_plan_count ?? 0, icon: Document, color: '#4ade80' },
    { label: '获得奖项', value: profile.value?.award_count ?? 0, icon: Medal, color: '#a78bfa' },
  ])

  function roleType(role: string): '' | 'success' | 'warning' | 'info' | 'danger' {
    if (role === 'admin') return 'danger'
    if (role === 'teacher') return 'warning'
    return 'info'
  }

  async function fetchProfile() {
    try {
      const res = await profileAPI.getMyProfile()
      profile.value = res.profile
      editForm.name = res.profile.name || ''
      editForm.email = res.profile.email || ''
      editForm.phone = res.profile.phone || ''
      editForm.dept = res.profile.dept || ''
    } catch (e) {
      console.error('Failed to fetch profile:', e)
    } finally {
      loading.value = false
    }
  }

  async function handleSave() {
    saving.value = true
    saveMsg.value = ''
    saveStatus.value = ''
    try {
      await profileAPI.updateProfile({ ...editForm })
      saveMsg.value = '保存成功'
      saveStatus.value = 'success'
      const refreshed = await profileAPI.getMyProfile()
      profile.value = refreshed.profile
      editing.value = false
    } catch (e: any) {
      saveMsg.value = e.response?.data?.error || '保存失败'
      saveStatus.value = 'error'
    } finally {
      saving.value = false
    }
  }

  onMounted(fetchProfile)
</script>

<style scoped lang="scss">
  .loading-wrap {
    display: flex;
    height: 200px;
    align-items: center;
    justify-content: center;
  }

  .profile-header {
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 16px;
    padding: 32px;
    display: flex;
    gap: 32px;
    margin-bottom: 24px;

    &__avatar-wrap {
      position: relative;
      flex-shrink: 0;
    }

    &__info {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 6px;
    }

    &__name {
      margin: 0;
      font-size: 28px;
      font-weight: 700;
      color: var(--el-text-color-primary);
    }

    &__username {
      margin: 0;
      font-size: 14px;
      color: var(--el-text-color-secondary);
    }

    &__detail {
      margin: 0;
      font-size: 14px;
      color: var(--el-text-color-regular);
      display: flex;
      align-items: center;
      gap: 6px;
    }
  }

  .avatar-placeholder {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    background: linear-gradient(135deg, #f59e0b, #f59e0b);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 40px;
    font-weight: 700;
    color: #000;
  }

  .role-badge {
    position: absolute;
    bottom: -4px;
    left: 50%;
    transform: translateX(-50%);
  }

  .edit-card {
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 16px;
    padding: 24px;
    margin-bottom: 24px;
  }

  .edit-actions {
    display: flex;
    gap: 12px;
    align-items: center;
  }

  .save-msg {
    font-size: 14px;
    display: inline-flex;
    align-items: center;
    gap: 5px;

    &--ok {
      color: var(--el-color-success);
    }

    &--err {
      color: var(--el-color-danger);
    }
  }

  .section-title {
    margin: 0 0 16px;
    font-size: 18px;
    font-weight: 600;
    color: var(--el-text-color-primary);
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .stats-section {
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 16px;
    padding: 24px;
    margin-bottom: 24px;
  }

  .stat-card {
    background: var(--el-fill-color-light);
    border-radius: 12px;
    padding: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;
    border-top: 3px solid;
    margin-bottom: 16px;

    &__value {
      font-size: 32px;
      font-weight: 700;
    }

    &__label {
      font-size: 13px;
      color: var(--el-text-color-secondary);
    }
  }

  .actions-section {
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    border-radius: 16px;
    padding: 24px;
  }

  .actions-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
  }
</style>

// frontend-vite/src/pages/profile.tsx
import { useEffect, useState, useRef } from 'react';
import gsap from 'gsap';
import { useAuthStore } from '@/stores/auth';
import { profileAPI, type UserProfile } from '@/services/api';
import { useNavigate } from 'react-router-dom';
import { Icon } from '@/components/ui/icon';

const roleLabels: Record<string, string> = {
  student: '学生',
  teacher: '教师',
  admin: '管理员',
};

const roleColors: Record<string, string> = {
  student: 'var(--amber)',
  teacher: 'var(--blue, #4a9eff)',
  admin: 'var(--red, #ff6b6b)',
};

export function ProfilePage() {
  const { user } = useAuthStore();
  const navigate = useNavigate();
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [editForm, setEditForm] = useState({ name: '', email: '', phone: '', dept: '' });
  const [saving, setSaving] = useState(false);
  const [saveMsg, setSaveMsg] = useState('');
  const [saveStatus, setSaveStatus] = useState<'success' | 'error' | ''>('');
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    profileAPI.getMyProfile()
      .then(res => {
        setProfile(res.profile);
        setEditForm({
          name: res.profile.name || '',
          email: res.profile.email || '',
          phone: res.profile.phone || '',
          dept: res.profile.dept || '',
        });
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (loading || !containerRef.current) return;
    const raf = requestAnimationFrame(() => {
      const cards = containerRef.current?.querySelectorAll<HTMLElement>('[data-card]');
      if (!cards?.length) return;
      gsap.set(cards, { opacity: 0, y: 30, scale: 0.95 });
      gsap.to(cards, { opacity: 1, y: 0, scale: 1, duration: 0.5, stagger: 0.08, ease: 'back.out(1.2)' });
    });
    return () => cancelAnimationFrame(raf);
  }, [loading, profile]);

  const handleSave = async () => {
    setSaving(true);
    setSaveMsg('');
    setSaveStatus('');
    try {
      const res = await profileAPI.updateProfile(editForm);
      setSaveMsg('保存成功');
      setSaveStatus('success');
      // Refresh profile
      const refreshed = await profileAPI.getMyProfile();
      setProfile(refreshed.profile);
      setEditing(false);
    } catch (e: any) {
      setSaveMsg(e.response?.data?.error || '保存失败');
      setSaveStatus('error');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  if (!profile) {
    return (
      <div style={{ padding: 48, textAlign: 'center', color: 'var(--text-3)' }}>
        无法加载用户信息
      </div>
    );
  }

  const stats = [
    { label: '参与赛事', value: profile.competition_count, icon: 'trophy', color: 'var(--amber)' },
    { label: '加入团队', value: profile.team_count, icon: 'users', color: 'var(--blue, #4a9eff)' },
    { label: '提交预案', value: profile.pre_plan_count, icon: 'clipboard-list', color: 'var(--green, #4ade80)' },
    { label: '获得奖项', value: profile.award_count, icon: 'award', color: 'var(--purple, #a78bfa)' },
  ];

  return (
    <div ref={containerRef} style={{ padding: '24px', maxWidth: 960, margin: '0 auto' }}>
      {/* Header */}
      <div data-card style={styles.headerCard}>
        <div style={styles.avatarWrap}>
          {profile.avatar ? (
            <img src={profile.avatar} alt={profile.name} style={styles.avatar} />
          ) : (
            <div style={styles.avatarPlaceholder}>
              {(profile.name || profile.username).charAt(0).toUpperCase()}
            </div>
          )}
          <div style={{ ...styles.roleBadge, background: roleColors[profile.role] || 'var(--text-3)' }}>
            {roleLabels[profile.role] || profile.role}
          </div>
        </div>
        <div style={styles.info}>
          <h1 style={styles.name}>{profile.name || profile.username}</h1>
          <p style={styles.username}>@{profile.username}</p>
          {profile.dept && <p style={styles.detail}><Icon name="school" size={14} />{profile.dept}</p>}
          {profile.student_id && <p style={styles.detail}><Icon name="edit" size={14} />学号: {profile.student_id}</p>}
          {profile.email && <p style={styles.detail}><Icon name="mail" size={14} />{profile.email}</p>}
          {profile.phone && <p style={styles.detail}><Icon name="phone" size={14} />{profile.phone}</p>}
          <p style={styles.detail}><Icon name="calendar" size={14} />注册于 {profile.created_at}</p>
          <button
            onClick={() => setEditing(!editing)}
            style={styles.editBtn}
          >
            {editing ? '取消' : <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Icon name="edit" size={14} />编辑资料</span>}
          </button>
        </div>
      </div>

      {/* Edit Form */}
      {editing && (
        <div data-card style={styles.editCard}>
          <h3 style={styles.sectionTitle}>编辑个人信息</h3>
          <div style={styles.formGrid}>
            <label style={styles.label}>
              姓名
              <input
                style={styles.input}
                value={editForm.name}
                onChange={e => setEditForm({ ...editForm, name: e.target.value })}
              />
            </label>
            <label style={styles.label}>
              邮箱
              <input
                style={styles.input}
                type="email"
                value={editForm.email}
                onChange={e => setEditForm({ ...editForm, email: e.target.value })}
              />
            </label>
            <label style={styles.label}>
              手机
              <input
                style={styles.input}
                value={editForm.phone}
                onChange={e => setEditForm({ ...editForm, phone: e.target.value })}
              />
            </label>
            <label style={styles.label}>
              院系
              <input
                style={styles.input}
                value={editForm.dept}
                onChange={e => setEditForm({ ...editForm, dept: e.target.value })}
              />
            </label>
          </div>
          <div style={{ display: 'flex', gap: 12, marginTop: 16 }}>
            <button onClick={handleSave} disabled={saving} style={styles.saveBtn}>
              {saving ? '保存中...' : <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Icon name="save" size={14} />保存</span>}
            </button>
            {saveMsg && (
              <span style={{ alignSelf: 'center', fontSize: 14, display: 'inline-flex', alignItems: 'center', gap: 5, color: saveStatus === 'success' ? 'var(--green)' : 'var(--red)' }}>
                <Icon name={saveStatus === 'success' ? 'circle-check' : 'circle-x'} size={14} />
                {saveMsg}
              </span>
            )}
          </div>
        </div>
      )}

      {/* Stats Grid */}
      <div data-card style={styles.statsSection}>
        <h3 style={styles.sectionTitle}><Icon name="chart" size={18} />我的数据</h3>
        <div style={styles.statsGrid}>
          {stats.map((s, i) => (
            <div key={i} style={{ ...styles.statCard, borderTopColor: s.color }}>
              <span style={{ ...styles.statIcon, color: s.color }}><Icon name={s.icon} size={28} /></span>
              <span style={{ ...styles.statValue, color: s.color }}>{s.value}</span>
              <span style={styles.statLabel}>{s.label}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div data-card style={styles.actionsCard}>
        <h3 style={styles.sectionTitle}><Icon name="rocket" size={18} />快捷操作</h3>
        <div style={styles.actionsGrid}>
          {profile.role === 'student' && (
            <>
              <button onClick={() => navigate('/teams')} style={styles.actionBtn}><Icon name="users" size={14} />我的团队</button>
              <button onClick={() => navigate('/preplans')} style={styles.actionBtn}><Icon name="clipboard-list" size={14} />我的预案</button>
              <button onClick={() => navigate('/coach')} style={styles.actionBtn}><Icon name="mic" size={14} />答辩教练</button>
            </>
          )}
          <button onClick={() => navigate('/competitions')} style={styles.actionBtn}><Icon name="trophy" size={14} />赛事列表</button>
          <button onClick={() => navigate('/aitools')} style={styles.actionBtn}><Icon name="bot" size={14} />AI 工具箱</button>
          <button onClick={() => navigate('/leaderboard')} style={styles.actionBtn}><Icon name="award" size={14} />排行榜</button>
          <button onClick={() => navigate('/showcase')} style={styles.actionBtn}><Icon name="target" size={14} />成果展示</button>
        </div>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  headerCard: {
    background: 'var(--surface-1)',
    border: '1px solid var(--border-1)',
    borderRadius: 16,
    padding: 32,
    display: 'flex',
    gap: 32,
    marginBottom: 24,
  },
  avatarWrap: {
    position: 'relative',
    flexShrink: 0,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: '50%',
    objectFit: 'cover',
    border: '3px solid var(--amber)',
  },
  avatarPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, var(--amber), var(--orange, #f59e0b))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 40,
    fontWeight: 700,
    color: '#000',
  },
  roleBadge: {
    position: 'absolute' as const,
    bottom: -4,
    left: '50%',
    transform: 'translateX(-50%)',
    padding: '2px 12px',
    borderRadius: 12,
    fontSize: 12,
    fontWeight: 600,
    color: '#fff',
    whiteSpace: 'nowrap' as const,
  },
  info: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  name: {
    margin: 0,
    fontSize: 28,
    fontWeight: 700,
    color: 'var(--text-1)',
  },
  username: {
    margin: 0,
    fontSize: 14,
    color: 'var(--text-3)',
  },
  detail: {
    margin: 0,
    fontSize: 14,
    color: 'var(--text-2)',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  editBtn: {
    alignSelf: 'flex-start',
    marginTop: 8,
    padding: '6px 16px',
    borderRadius: 8,
    border: '1px solid var(--border-2)',
    background: 'var(--surface-2)',
    color: 'var(--text-1)',
    cursor: 'pointer',
    fontSize: 14,
  },
  editCard: {
    background: 'var(--surface-1)',
    border: '1px solid var(--border-1)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
  },
  sectionTitle: {
    margin: '0 0 16px',
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--text-1)',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
  },
  label: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 4,
    fontSize: 13,
    color: 'var(--text-2)',
  },
  input: {
    padding: '8px 12px',
    borderRadius: 8,
    border: '1px solid var(--border-2)',
    background: 'var(--surface-2)',
    color: 'var(--text-1)',
    fontSize: 14,
    outline: 'none',
  },
  saveBtn: {
    padding: '8px 20px',
    borderRadius: 8,
    border: 'none',
    background: 'var(--amber)',
    color: '#000',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14,
  },
  statsSection: {
    background: 'var(--surface-1)',
    border: '1px solid var(--border-1)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: 16,
  },
  statCard: {
    background: 'var(--surface-2)',
    borderRadius: 12,
    padding: 20,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: 8,
    borderTop: '3px solid',
  },
  statIcon: {
    display: 'flex',
  },
  statValue: {
    fontSize: 32,
    fontWeight: 700,
  },
  statLabel: {
    fontSize: 13,
    color: 'var(--text-3)',
  },
  actionsCard: {
    background: 'var(--surface-1)',
    border: '1px solid var(--border-1)',
    borderRadius: 16,
    padding: 24,
  },
  actionsGrid: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 12,
  },
  actionBtn: {
    padding: '10px 20px',
    borderRadius: 10,
    border: '1px solid var(--border-2)',
    background: 'var(--surface-2)',
    color: 'var(--text-1)',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    transition: 'all 0.2s',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
};
