// frontend-vue/src/views/ssgl/registrations/index.vue
<template>
  <section class="ssgl-page" data-page="Registrations">
    <SSGLPageHeader title="报名管理" :subtitle="`共 ${total} 条报名记录`" />

    <!-- Stats -->
    <ElRow :gutter="16" class="mb-4">
      <ElCol :span="6" v-for="s in statCards" :key="s.label">
        <ElCard shadow="never">
          <div class="flex items-center gap-3">
            <div class="w-2 h-8 rounded" :style="{ background: s.color }" />
            <div>
              <div class="text-xs text-gray-400 uppercase tracking-wide">{{ s.label }}</div>
              <div class="text-2xl font-bold">{{ s.value }}</div>
            </div>
          </div>
        </ElCard>
      </ElCol>
    </ElRow>

    <!-- Filters -->
    <div class="flex gap-3 mb-4 flex-wrap">
      <ElSelect v-model="statusFilter" placeholder="全部状态" clearable style="width: 150px" @change="loadData(1)">
        <ElOption label="全部状态" value="" />
        <ElOption label="待审核" value="pending" />
        <ElOption label="已通过" value="approved" />
        <ElOption label="已驳回" value="rejected" />
      </ElSelect>
      <ElSelect v-model="compFilter" placeholder="全部赛事" clearable style="width: 220px" @change="loadData(1)">
        <ElOption label="全部赛事" value="" />
        <ElOption v-for="c in competitions" :key="c.id" :label="c.title" :value="String(c.id)" />
      </ElSelect>
    </div>

    <!-- Table -->
    <ElCard shadow="never" v-loading="loading">
      <ElTable :data="regs" stripe style="width: 100%">
        <ElTableColumn prop="id" label="ID" width="70">
          <template #default="{ row }">
            <span class="text-gray-400">#{{ row.id }}</span>
          </template>
        </ElTableColumn>
        <ElTableColumn label="学生" min-width="140">
          <template #default="{ row }">
            <div class="flex items-center gap-2">
              <ElAvatar :size="28">{{ (row.user?.name || '?')[0] }}</ElAvatar>
              <span class="font-medium">{{ row.user?.name || row.user?.username || `用户#${row.user_id}` }}</span>
            </div>
          </template>
        </ElTableColumn>
        <ElTableColumn label="赛事" min-width="200">
          <template #default="{ row }">
            {{ row.competition?.title || `赛事#${row.competition_id}` }}
          </template>
        </ElTableColumn>
        <ElTableColumn label="状态" width="110">
          <template #default="{ row }">
            <SSGLStatusTag :status="row.status" />
          </template>
        </ElTableColumn>
        <ElTableColumn label="备注" min-width="160">
          <template #default="{ row }">
            <span class="text-gray-400">{{ row.remark || '—' }}</span>
          </template>
        </ElTableColumn>
        <ElTableColumn label="时间" width="120">
          <template #default="{ row }">
            <span class="text-gray-400 text-sm">{{ formatDate(row.created_at) }}</span>
          </template>
        </ElTableColumn>
        <ElTableColumn label="操作" width="160" fixed="right">
          <template #default="{ row }">
            <template v-if="row.status === 'pending'">
              <ElButton type="success" link size="small" @click="handleApprove(row.id)">
                通过
              </ElButton>
              <ElButton type="danger" link size="small" @click="openReject(row.id)">
                驳回
              </ElButton>
            </template>
            <span v-else class="text-gray-400">—</span>
          </template>
        </ElTableColumn>
      </ElTable>

      <!-- Pagination -->
      <div v-if="total > pageSize" class="flex justify-center mt-4">
        <ElPagination
          v-model:current-page="page"
          :page-size="pageSize"
          :total="total"
          layout="prev, pager, next"
          @current-change="loadData"
        />
      </div>
    </ElCard>

    <!-- Reject Dialog -->
    <ElDialog v-model="rejectVisible" title="驳回报名" width="420px" destroy-on-close>
      <ElForm @submit.prevent="handleReject">
        <ElFormItem label="驳回原因">
          <ElInput v-model="rejectReason" type="textarea" :rows="3" placeholder="填写驳回原因（可选）" />
        </ElFormItem>
      </ElForm>
      <template #footer>
        <ElButton @click="rejectVisible = false">取消</ElButton>
        <ElButton type="danger" :loading="rejecting" @click="handleReject">确认驳回</ElButton>
      </template>
    </ElDialog>
  </section>
</template>

<script setup lang="ts">
  import { registrationsAPI, competitionsAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import SSGLStatusTag from '@/components/ssgl/SSGLStatusTag.vue'
  import type { CompetitionRegistration, Competition } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Registrations' })

  const loading = ref(false)
  const regs = ref<CompetitionRegistration[]>([])
  const total = ref(0)
  const page = ref(1)
  const pageSize = 20
  const statusFilter = ref('')
  const compFilter = ref('')
  const competitions = ref<Competition[]>([])

  // Reject dialog
  const rejectVisible = ref(false)
  const rejectId = ref<number | null>(null)
  const rejectReason = ref('')
  const rejecting = ref(false)

  const statCards = computed(() => [
    { label: '总计', value: total.value, color: 'var(--el-color-primary)' },
    { label: '待审核', value: regs.value.filter(r => r.status === 'pending').length, color: 'var(--el-color-warning)' },
    { label: '已通过', value: regs.value.filter(r => r.status === 'approved').length, color: 'var(--el-color-success)' },
    { label: '已驳回', value: regs.value.filter(r => r.status === 'rejected').length, color: 'var(--el-color-danger)' },
  ])

  const formatDate = (d: string) => {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('zh-CN')
  }

  const loadData = async (p?: number) => {
    if (p) page.value = p
    loading.value = true
    try {
      const params: Record<string, string> = { page: String(page.value), page_size: String(pageSize) }
      if (statusFilter.value) params.status = statusFilter.value
      if (compFilter.value) params.competition_id = compFilter.value
      const res = await registrationsAPI.list(params)
      regs.value = res.registrations || []
      total.value = res.total || 0
    } catch {
      ElMessage.error('加载报名数据失败')
    } finally {
      loading.value = false
    }
  }

  const loadCompetitions = async () => {
    try {
      const res = await competitionsAPI.list({ page_size: '100' })
      competitions.value = res.competitions || []
    } catch { /* ignore */ }
  }

  const handleApprove = async (id: number) => {
    try {
      await registrationsAPI.approve(id)
      ElMessage.success('已通过报名')
      loadData()
    } catch {
      ElMessage.error('操作失败')
    }
  }

  const openReject = (id: number) => {
    rejectId.value = id
    rejectReason.value = ''
    rejectVisible.value = true
  }

  const handleReject = async () => {
    if (!rejectId.value) return
    rejecting.value = true
    try {
      await registrationsAPI.reject(rejectId.value, rejectReason.value)
      ElMessage.success('已驳回报名')
      rejectVisible.value = false
      loadData()
    } catch {
      ElMessage.error('操作失败')
    } finally {
      rejecting.value = false
    }
  }

  onMounted(() => {
    loadData()
    loadCompetitions()
  })
</script>

// frontend-vite/src/pages/registrations.tsx
import { useEffect, useState } from 'react';
import { registrationsAPI, competitionsAPI } from '@/services/api';
import { PageHeader } from '@/components/ui/page-helpers';
import { EmptyState } from '@/components/ui/empty-state';
import { Icon } from '@/components/ui/icon';
import { Select, TextInput } from '@/components/ui/form';
import { Button } from '@/components/ui/button';
import { toast } from '@/components/ui/toast';
import type { CompetitionRegistration, Competition } from '@/types';

const STATUS_LABELS: Record<string, string> = {
  pending: '待审核',
  approved: '已通过',
  rejected: '已驳回',
  cancelled: '已取消',
};

const STATUS_COLORS: Record<string, string> = {
  pending: 'var(--amber)',
  approved: 'var(--green)',
  rejected: 'var(--red)',
  cancelled: 'var(--text-3)',
};

export function RegistrationsPage() {
  const [regs, setRegs] = useState<CompetitionRegistration[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState('');
  const [compFilter, setCompFilter] = useState('');
  const [competitions, setCompetitions] = useState<Competition[]>([]);
  const [loading, setLoading] = useState(true);
  const [rejectModal, setRejectModal] = useState<{ id: number; reason: string } | null>(null);

  const load = async (p = page) => {
    setLoading(true);
    try {
      const params: Record<string, string> = { page: String(p), page_size: '20' };
      if (statusFilter) params.status = statusFilter;
      if (compFilter) params.competition_id = compFilter;
      const res = await registrationsAPI.list(params);
      setRegs(res.registrations || []);
      setTotal(res.total || 0);
      setPage(p);
    } catch { /* ignore */ }
    setLoading(false);
  };

  useEffect(() => {
    competitionsAPI.list({ page_size: '100' }).then(res => setCompetitions(res.competitions || [])).catch(() => {});
  }, []);

  useEffect(() => { load(1); }, [statusFilter, compFilter]);

  const handleApprove = async (id: number) => {
    try {
      await registrationsAPI.approve(id);
      toast.success('已通过报名');
      load();
    } catch { toast.error('操作失败'); }
  };

  const handleReject = async () => {
    if (!rejectModal) return;
    try {
      await registrationsAPI.reject(rejectModal.id, rejectModal.reason);
      toast.success('已驳回报名');
      setRejectModal(null);
      load();
    } catch { toast.error('操作失败'); }
  };

  const stats = {
    total,
    pending: regs.filter(r => r.status === 'pending').length,
    approved: regs.filter(r => r.status === 'approved').length,
    rejected: regs.filter(r => r.status === 'rejected').length,
  };

  return (
    <div>
      <PageHeader title="报名管理" subtitle={`共 ${total} 条报名记录`} />

      {/* Stats cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
        {[
          { label: '总计', value: total, color: 'var(--teal)' },
          { label: '待审核', value: stats.pending, color: 'var(--amber)' },
          { label: '已通过', value: stats.approved, color: 'var(--green)' },
          { label: '已驳回', value: stats.rejected, color: 'var(--red)' },
        ].map(s => (
          <div key={s.label} style={{
            background: 'var(--surface-1)', borderRadius: 10, padding: '14px 16px',
            border: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 12,
          }}>
            <div style={{ width: 8, height: 32, borderRadius: 4, background: s.color, flexShrink: 0 }} />
            <div>
              <div style={{ fontSize: 11, color: 'var(--text-3)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{s.label}</div>
              <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--text-1)' }}>{s.value}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Filters */}
      <div style={{ display: 'flex', gap: 12, marginBottom: 16, flexWrap: 'wrap' }}>
        <Select value={statusFilter} onChange={setStatusFilter} placeholder="全部状态"
          options={[
            { value: '', label: '全部状态' },
            { value: 'pending', label: '待审核' },
            { value: 'approved', label: '已通过' },
            { value: 'rejected', label: '已驳回' },
          ]} />
        <Select value={compFilter} onChange={setCompFilter} placeholder="全部赛事"
          options={[
            { value: '', label: '全部赛事' },
            ...competitions.map(c => ({ value: String(c.id), label: c.title })),
          ]} />
      </div>

      {/* Table */}
      {loading ? (
        <div style={{ textAlign: 'center', padding: 40, color: 'var(--text-3)' }}>加载中...</div>
      ) : regs.length === 0 ? (
        <EmptyState icon="file" title="暂无报名记录" desc="当学生报名赛事后，记录会显示在这里" />
      ) : (
        <div style={{ background: 'var(--surface-1)', borderRadius: 12, border: '1px solid var(--border)', overflow: 'hidden' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 14 }}>
            <thead>
              <tr style={{ background: 'var(--surface-2)', textAlign: 'left' }}>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>ID</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>学生</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>赛事</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>状态</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>备注</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>时间</th>
                <th style={{ padding: '10px 14px', fontWeight: 600, color: 'var(--text-2)' }}>操作</th>
              </tr>
            </thead>
            <tbody>
              {regs.map(r => (
                <tr key={r.id} style={{ borderTop: '1px solid var(--border)' }}>
                  <td style={{ padding: '10px 14px', color: 'var(--text-3)' }}>#{r.id}</td>
                  <td style={{ padding: '10px 14px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'var(--teal-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                        <Icon name="users" size={14} />
                      </div>
                      <span style={{ fontWeight: 500 }}>{r.user?.name || r.user?.username || `用户#${r.user_id}`}</span>
                    </div>
                  </td>
                  <td style={{ padding: '10px 14px' }}>{r.competition?.title || `赛事#${r.competition_id}`}</td>
                  <td style={{ padding: '10px 14px' }}>
                    <span style={{
                      display: 'inline-flex', alignItems: 'center', gap: 4,
                      padding: '3px 10px', borderRadius: 20, fontSize: 12, fontWeight: 500,
                      background: `${STATUS_COLORS[r.status]}18`, color: STATUS_COLORS[r.status],
                    }}>
                      {STATUS_LABELS[r.status] || r.status}
                    </span>
                  </td>
                  <td style={{ padding: '10px 14px', color: 'var(--text-3)', maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {r.remark || '—'}
                  </td>
                  <td style={{ padding: '10px 14px', color: 'var(--text-3)', fontSize: 13 }}>
                    {new Date(r.created_at).toLocaleDateString('zh-CN')}
                  </td>
                  <td style={{ padding: '10px 14px' }}>
                    {r.status === 'pending' && (
                      <div style={{ display: 'flex', gap: 6 }}>
                        <Button variant="ghost" onClick={() => handleApprove(r.id)}>
                          <Icon name="check" size={14} /> 通过
                        </Button>
                        <Button variant="ghost" onClick={() => setRejectModal({ id: r.id, reason: '' })}>
                          <Icon name="x" size={14} /> 驳回
                        </Button>
                      </div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Pagination */}
          {total > 20 && (
            <div style={{ display: 'flex', justifyContent: 'center', gap: 8, padding: 16 }}>
              <Button variant="ghost" disabled={page <= 1} onClick={() => load(page - 1)}>上一页</Button>
              <span style={{ lineHeight: '32px', color: 'var(--text-3)', fontSize: 13 }}>第 {page} 页 / 共 {Math.ceil(total / 20)} 页</span>
              <Button variant="ghost" disabled={page * 20 >= total} onClick={() => load(page + 1)}>下一页</Button>
            </div>
          )}
        </div>
      )}

      {/* Reject modal */}
      {rejectModal && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}
          onClick={() => setRejectModal(null)}>
          <div style={{ background: 'var(--surface-1)', borderRadius: 14, padding: 24, width: 400, maxWidth: '90vw' }}
            onClick={e => e.stopPropagation()}>
            <h3 style={{ margin: '0 0 16px', fontSize: 16, fontWeight: 600 }}>驳回报名</h3>
            <TextInput value={rejectModal.reason} onChange={e => setRejectModal({ ...rejectModal, reason: e.target.value })} placeholder="驳回原因（可选）" />
            <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end', marginTop: 16 }}>
              <Button variant="ghost" onClick={() => setRejectModal(null)}>取消</Button>
              <Button onClick={handleReject}>确认驳回</Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
