// frontend-vite/src/pages/aitools.tsx
import { useState, useRef } from 'react';
import { aiToolsAPI } from '@/services/api';
import { Icon } from '@/components/ui/icon';
import { Spinner } from '@/components/ui/spinner';

const TOOLS = [
  { id: 'business-plan', name: '商业计划书生成', desc: '输入项目信息，自动生成结构完整的商业计划书草稿', tags: ['文档生成', 'GPT-4'], color: 'teal' },
  { id: 'market-analysis', name: '市场分析报告', desc: '深度分析目标市场规模、竞争格局与切入机会点', tags: ['市场分析', 'RAG'], color: 'amber' },
  { id: 'improvement', name: '项目改进建议', desc: '结合往届优秀项目 AI 对比，给出针对性改进方向', tags: ['AI 建议', '历史对比'], color: 'purple' },
  { id: 'tech-route', name: '技术路线规划', desc: '根据功能需求和团队能力生成技术架构建议', tags: ['技术规划', 'RAG'], color: 'green' },
  { id: 'resource-match', name: '资源整合建议', desc: '分析团队技能差距并推荐补充资源与合作方向', tags: ['资源匹配', 'AI'], color: 'amber' },
  { id: 'pitch-deck', name: '路演PPT大纲', desc: '根据项目信息和答辩时长，生成结构化路演PPT大纲与时间分配', tags: ['路演', '答辩教练'], color: 'purple' },
  { id: 'advisor', name: '赛事顾问', desc: '实时回答赛事规则、评审标准与参赛策略问题', tags: ['问答', 'RAG + LLM'], color: 'teal' },
  { id: 'swot-analysis', name: 'SWOT 分析', desc: '对项目进行优势/劣势/机会/威胁全面分析，含交叉策略矩阵', tags: ['战略分析', 'RAG'], color: 'green' },
  { id: 'competition-report', name: '赛事分析报告', desc: '深度分析赛事评审标准、参赛建议、时间规划与往届优秀项目特征', tags: ['赛事分析', 'RAG'], color: 'teal' },
  { id: 'study-plan', name: '备赛计划生成', desc: '根据赛事特点和团队情况，量身定制周密的备赛计划和学习路径', tags: ['备赛', '个性化'], color: 'green' },
];

const colorMap: Record<string, { accent: string; bg: string; border: string }> = {
  teal:   { accent: 'var(--teal)',   bg: 'var(--teal-bg)',   border: 'var(--teal-border)' },
  amber:  { accent: 'var(--amber)',  bg: 'var(--amber-bg)',  border: 'var(--amber-border)' },
  purple: { accent: 'var(--purple)', bg: 'var(--purple-bg)', border: 'var(--border)' },
  green:  { accent: 'var(--green)',  bg: 'var(--green-bg)',  border: 'var(--border)' },
};

export function AIToolsPage() {
  const [active, setActive] = useState<string | null>(null);
  const [input, setInput] = useState('');
  const [extra, setExtra] = useState('');
  const [output, setOutput] = useState('');
  const [generating, setGenerating] = useState(false);
  const [streaming, setStreaming] = useState(false);
  const outputRef = useRef<HTMLDivElement>(null);

  const generate = async () => {
    if (!active || generating) return;
    setGenerating(true);
    setStreaming(true);
    setOutput('');

    // Use SSE streaming for real-time output
    await aiToolsAPI.callStream(active, input, extra || undefined, {
      onChunk: (text: string) => {
        setOutput(prev => prev + text);
        if (outputRef.current) {
          requestAnimationFrame(() => {
            if (outputRef.current) outputRef.current.scrollTop = outputRef.current.scrollHeight;
          });
        }
      },
      onDone: () => {
        setGenerating(false);
        setStreaming(false);
      },
      onError: (msg: string) => {
        setOutput(msg);
        setGenerating(false);
        setStreaming(false);
      },
    });
  };

  const activeTool = active ? TOOLS.find(t => t.id === active) : null;
  const activeColors = activeTool ? (colorMap[activeTool.color] || colorMap.teal) : colorMap.teal;
  const showExtra = active === 'market-analysis' || active === 'tech-route' || active === 'resource-match'
    || active === 'pitch-deck' || active === 'swot-analysis' || active === 'advisor' || active === 'study-plan';
  const extraLabels: Record<string, string> = {
    'market-analysis': '目标市场（选填）',
    'tech-route': '团队技术栈（选填）',
    'resource-match': '项目需求（选填）',
    'pitch-deck': '答辩时长，如 10分钟（选填）',
    'swot-analysis': '竞争对手信息（选填）',
    'advisor': '剩余时间（选填）',
    'study-plan': '团队情况描述（选填）',
  };

  return (
    <div className="forge-page" style={{ paddingBottom: 0, height: 'calc(100vh - var(--topbar-h))', overflowY: 'hidden', display: 'flex', flexDirection: 'column' }}>
      <div style={{ marginBottom: 20, flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
          <div style={{ width: 32, height: 32, borderRadius: 8, background: 'var(--teal-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--teal)' }}>
            <Icon name="sparkles" size={16}/>
          </div>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: 'var(--text)', letterSpacing: '-0.02em' }}>AI 工具箱</h1>
          <span className="badge badge-teal">RAG + LLM</span>
          {streaming && <span className="badge badge-green" style={{ animation: 'forge-spin 1.5s ease-in-out infinite' }}>⚡ 流式输出中</span>}
        </div>
        <p style={{ fontSize: 13, color: 'var(--text-3)' }}>{TOOLS.length} 个智能助手 · 基于往届项目知识库 · 实时流式生成</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', gap: 16, flex: 1, overflow: 'hidden' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8, overflowY: 'auto' }}>
          {TOOLS.map((tool, i) => {
            const colors = colorMap[tool.color] || colorMap.teal;
            const isActive = active === tool.id;
            return (
              <button key={tool.id} className={`anim-in d${i + 1}`} onClick={() => { setActive(tool.id); setOutput(''); setInput(''); setExtra(''); }} style={{
                padding: 16, borderRadius: 12, border: `1px solid ${isActive ? colors.border : 'var(--border)'}`,
                background: isActive ? colors.bg : 'var(--surface)', cursor: 'pointer', textAlign: 'left', transition: 'all 0.2s',
                boxShadow: isActive ? `0 0 0 1px ${colors.border}` : 'none',
              }}
                onMouseEnter={e => { if (!isActive) { e.currentTarget.style.borderColor = colors.accent; e.currentTarget.style.background = 'var(--surface-2)'; } }}
                onMouseLeave={e => { if (!isActive) { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.background = 'var(--surface)'; } }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
                  <span style={{ fontSize: 13, fontWeight: 700, color: isActive ? colors.accent : 'var(--text)' }}>{tool.name}</span>
                  {isActive && <div style={{ marginLeft: 'auto', width: 6, height: 6, borderRadius: '50%', background: colors.accent }}/>}
                </div>
                <p style={{ fontSize: 12, color: 'var(--text-3)', lineHeight: 1.5, margin: 0 }}>{tool.desc}</p>
                <div style={{ display: 'flex', gap: 5, marginTop: 8, flexWrap: 'wrap' }}>
                  {tool.tags.map(t => (
                    <span key={t} style={{ fontSize: 10, padding: '2px 7px', borderRadius: 10, background: `${colors.accent}18`, color: colors.accent, border: `1px solid ${colors.border}`, fontFamily: 'var(--font-mono)', fontWeight: 600 }}>{t}</span>
                  ))}
                </div>
              </button>
            );
          })}
        </div>

        <div className="card" style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
          {!activeTool ? (
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16, padding: 32 }}>
              <div style={{ width: 64, height: 64, borderRadius: 16, background: 'var(--teal-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--teal)' }}>
                <Icon name="sparkles" size={28}/>
              </div>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--text)', marginBottom: 6 }}>选择一个 AI 工具</div>
                <div style={{ fontSize: 13, color: 'var(--text-3)', lineHeight: 1.6 }}>从左侧选择工具，输入信息后点击生成</div>
              </div>
            </div>
          ) : (
            <>
              <div style={{ padding: '14px 20px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text)' }}>{activeTool.name}</div>
                  <div style={{ fontSize: 11, color: 'var(--text-3)' }}>{activeTool.desc}</div>
                </div>
                <button className="btn btn-ghost btn-sm" style={{ marginLeft: 'auto' }} onClick={() => { setActive(null); setOutput(''); }}>
                  <Icon name="x" size={14}/>
                </button>
              </div>
              <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                <div style={{ padding: 16, borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
                  <textarea className="forge-input" rows={3} placeholder={`描述你的项目，${activeTool.name} 将为你生成专属内容…`} value={input} onChange={e => setInput(e.target.value)} style={{ resize: 'none', marginBottom: showExtra ? 8 : 10 }}/>
                  {showExtra && (
                    <input className="forge-input" placeholder={extraLabels[active] || '附加信息（选填）'} value={extra} onChange={e => setExtra(e.target.value)} style={{ marginBottom: 10 }}/>
                  )}
                  <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                    <button className="btn btn-primary" onClick={generate} disabled={generating}
                      style={{ background: generating ? 'var(--surface-3)' : activeColors.accent, color: generating ? 'var(--text-3)' : '#0F1523', borderColor: 'transparent' }}>
                      {generating ? <><Spinner size={14} color="var(--text-3)"/> 生成中…</> : <><Icon name="sparkles" size={14}/> 立即生成</>}
                    </button>
                    {streaming && <span style={{ fontSize: 11, color: activeColors.accent, fontFamily: 'var(--font-mono)' }}>⚡ SSE 流式响应</span>}
                    {!streaming && <span style={{ fontSize: 11, color: 'var(--text-3)', marginLeft: 'auto', fontFamily: 'var(--font-mono)' }}>{activeTool.tags.join(' · ')}</span>}
                  </div>
                </div>
                <div ref={outputRef} style={{ flex: 1, overflowY: 'auto', padding: 20 }}>
                  {!output && !generating ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8, alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-3)' }}>
                      <Icon name="send" size={24}/>
                      <span style={{ fontSize: 13 }}>点击「立即生成」开始</span>
                    </div>
                  ) : (
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 12, lineHeight: 1.8, color: 'var(--text-2)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                      {output}
                      {streaming && <span style={{ display: 'inline-block', width: 8, height: 14, background: activeColors.accent, marginLeft: 2, verticalAlign: 'middle', borderRadius: 1, animation: 'forge-spin 1s step-end infinite' }}/>}
                    </div>
                  )}
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-vue/src/views/ssgl/aitools/index.vue
<template>
  <section class="ssgl-page aitools-page" data-page="AITools">
    <SSGLPageHeader title="AI 工具箱" subtitle="10 个智能助手 · 基于往届项目知识库 · 实时流式生成">
      <template #actions>
        <ElTag type="success" v-if="streaming" effect="dark">
          <ElIcon class="is-loading"><Loading /></ElIcon>
          流式输出中
        </ElTag>
        <ElTag effect="plain">RAG + LLM</ElTag>
      </template>
    </SSGLPageHeader>

    <div class="aitools-layout">
      <!-- Tool List -->
      <div class="aitools-sidebar">
        <button
          v-for="(tool, i) in TOOLS"
          :key="tool.id"
          class="tool-card"
          :class="{ active: active === tool.id, [`anim-in d${i + 1}`]: true }"
          :style="toolCardStyle(tool, active === tool.id)"
          @click="selectTool(tool.id)"
        >
          <div class="tool-card__header">
            <span class="tool-card__name" :style="{ color: active === tool.id ? getColor(tool.color).accent : 'var(--art-gray-900)' }">{{ tool.name }}</span>
            <span v-if="active === tool.id" class="tool-card__dot" :style="{ background: getColor(tool.color).accent }" />
          </div>
          <p class="tool-card__desc">{{ tool.desc }}</p>
          <div class="tool-card__tags">
            <span
              v-for="t in tool.tags"
              :key="t"
              class="tool-card__tag"
              :style="{ background: `${getColor(tool.color).accent}18`, color: getColor(tool.color).accent, borderColor: getColor(tool.color).border }"
            >{{ t }}</span>
          </div>
        </button>
      </div>

      <!-- Main Panel -->
      <div class="aitools-panel">
        <!-- Empty state -->
        <div v-if="!activeTool" class="aitools-empty">
          <ElIcon :size="48" color="var(--el-color-primary)"><MagicStick /></ElIcon>
          <div class="aitools-empty__title">选择一个 AI 工具</div>
          <div class="aitools-empty__desc">从左侧选择工具，输入信息后点击生成</div>
        </div>

        <!-- Active tool -->
        <template v-else>
          <div class="aitools-panel__header">
            <div>
              <div class="aitools-panel__title">{{ activeTool.name }}</div>
              <div class="aitools-panel__subtitle">{{ activeTool.desc }}</div>
            </div>
            <ElButton text @click="clearActive">
              <ElIcon><Close /></ElIcon>
            </ElButton>
          </div>

          <div class="aitools-panel__body">
            <div class="aitools-panel__input-area">
              <ElInput
                v-model="input"
                type="textarea"
                :rows="3"
                :placeholder="`描述你的项目，${activeTool.name} 将为你生成专属内容…`"
                resize="none"
              />
              <ElInput
                v-if="showExtra"
                v-model="extra"
                :placeholder="extraLabel"
                style="margin-top: 8px"
              />
              <div class="aitools-panel__actions">
                <ElButton
                  type="primary"
                  :disabled="generating"
                  :loading="generating"
                  @click="generate"
                >
                  <ElIcon v-if="!generating"><MagicStick /></ElIcon>
                  {{ generating ? '生成中…' : '立即生成' }}
                </ElButton>
                <ElTag v-if="streaming" type="success" effect="plain" size="small">
                  SSE 流式响应
                </ElTag>
                <span v-if="!streaming" class="aitools-panel__tags-label">{{ activeTool.tags.join(' · ') }}</span>
              </div>
            </div>

            <div ref="outputRef" class="aitools-panel__output">
              <template v-if="output">
                <SSGLStreamOutput :output="output" :loading="false" />
                <span v-if="streaming" class="cursor-blink" />
              </template>
              <div v-else-if="!generating" class="aitools-panel__output-empty">
                <ElIcon :size="24" color="var(--art-gray-400)"><Promotion /></ElIcon>
                <span>点击「立即生成」开始</span>
              </div>
              <SSGLStreamOutput v-else output="" :loading="true" />
            </div>
          </div>
        </template>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
  import { ref, computed, nextTick } from 'vue'
  import { ElMessage } from 'element-plus'
  import { Loading, Close, MagicStick, Promotion } from '@element-plus/icons-vue'
  import { aiToolsAPI } from '@/api/ai'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import SSGLStreamOutput from '@/components/ssgl/SSGLStreamOutput.vue'

  defineOptions({ name: 'SSGL_AITools' })

  interface Tool {
    id: string
    name: string
    desc: string
    tags: string[]
    color: string
  }

  const TOOLS: Tool[] = [
    { id: 'business-plan', name: '商业计划书生成', desc: '输入项目信息，自动生成结构完整的商业计划书草稿', tags: ['文档生成', 'GPT-4'], color: 'teal' },
    { id: 'market-analysis', name: '市场分析报告', desc: '深度分析目标市场规模、竞争格局与切入机会点', tags: ['市场分析', 'RAG'], color: 'amber' },
    { id: 'improvement', name: '项目改进建议', desc: '结合往届优秀项目 AI 对比，给出针对性改进方向', tags: ['AI 建议', '历史对比'], color: 'purple' },
    { id: 'tech-route', name: '技术路线规划', desc: '根据功能需求和团队能力生成技术架构建议', tags: ['技术规划', 'RAG'], color: 'green' },
    { id: 'resource-match', name: '资源整合建议', desc: '分析团队技能差距并推荐补充资源与合作方向', tags: ['资源匹配', 'AI'], color: 'amber' },
    { id: 'pitch-deck', name: '路演PPT大纲', desc: '根据项目信息和答辩时长，生成结构化路演PPT大纲与时间分配', tags: ['路演', '答辩教练'], color: 'purple' },
    { id: 'advisor', name: '赛事顾问', desc: '实时回答赛事规则、评审标准与参赛策略问题', tags: ['问答', 'RAG + LLM'], color: 'teal' },
    { id: 'swot-analysis', name: 'SWOT 分析', desc: '对项目进行优势/劣势/机会/威胁全面分析，含交叉策略矩阵', tags: ['战略分析', 'RAG'], color: 'green' },
    { id: 'competition-report', name: '赛事分析报告', desc: '深度分析赛事评审标准、参赛建议、时间规划与往届优秀项目特征', tags: ['赛事分析', 'RAG'], color: 'teal' },
    { id: 'study-plan', name: '备赛计划生成', desc: '根据赛事特点和团队情况，量身定制周密的备赛计划和学习路径', tags: ['备赛', '个性化'], color: 'green' },
  ]

  const COLOR_MAP: Record<string, { accent: string; bg: string; border: string }> = {
    teal:   { accent: '#0d9488', bg: 'rgba(13,148,136,0.08)', border: 'rgba(13,148,136,0.2)' },
    amber:  { accent: '#d97706', bg: 'rgba(217,119,6,0.08)', border: 'rgba(217,119,6,0.2)' },
    purple: { accent: '#7c3aed', bg: 'rgba(124,58,237,0.08)', border: 'rgba(124,58,237,0.2)' },
    green:  { accent: '#16a34a', bg: 'rgba(22,163,74,0.08)', border: 'rgba(22,163,74,0.2)' },
  }

  const EXTRA_LABELS: Record<string, string> = {
    'market-analysis': '目标市场（选填）',
    'tech-route': '团队技术栈（选填）',
    'resource-match': '项目需求（选填）',
    'pitch-deck': '答辩时长，如 10分钟（选填）',
    'swot-analysis': '竞争对手信息（选填）',
    'advisor': '剩余时间（选填）',
    'study-plan': '团队情况描述（选填）',
  }

  const active = ref<string | null>(null)
  const input = ref('')
  const extra = ref('')
  const output = ref('')
  const generating = ref(false)
  const streaming = ref(false)
  const outputRef = ref<HTMLElement | null>(null)

  const activeTool = computed(() => active.value ? TOOLS.find(t => t.id === active.value) : null)
  const showExtra = computed(() => active.value ? Object.prototype.hasOwnProperty.call(EXTRA_LABELS, active.value) : false)
  const extraLabel = computed(() => active.value ? (EXTRA_LABELS[active.value] || '附加信息（选填）') : '附加信息（选填）')

  function getColor(c: string) {
    return COLOR_MAP[c] || COLOR_MAP.teal
  }

  function toolCardStyle(tool: Tool, isActive: boolean) {
    const colors = getColor(tool.color)
    return {
      border: `1px solid ${isActive ? colors.border : 'var(--el-border-color-light)'}`,
      background: isActive ? colors.bg : 'var(--el-bg-color)',
      boxShadow: isActive ? `0 0 0 1px ${colors.border}` : 'none',
    }
  }

  function selectTool(id: string) {
    active.value = id
    output.value = ''
    input.value = ''
    extra.value = ''
  }

  function clearActive() {
    active.value = null
    output.value = ''
  }

  function scrollToBottom() {
    nextTick(() => {
      if (outputRef.value) {
        outputRef.value.scrollTop = outputRef.value.scrollHeight
      }
    })
  }

  async function generate() {
    if (!active.value || generating.value) return
    generating.value = true
    streaming.value = true
    output.value = ''

    await aiToolsAPI.callStream(active.value, input.value, extra.value || undefined, {
      onChunk(text: string) {
        output.value += text
        scrollToBottom()
      },
      onDone() {
        generating.value = false
        streaming.value = false
      },
      onError(msg: string) {
        ElMessage.error(msg)
        generating.value = false
        streaming.value = false
      },
    })
  }
</script>

<style scoped lang="scss">
  .aitools-page {
    display: flex;
    flex-direction: column;
    height: calc(100vh - var(--topbar-h, 60px));
    overflow: hidden;
  }

  .aitools-layout {
    display: grid;
    grid-template-columns: 300px 1fr;
    gap: 16px;
    flex: 1;
    overflow: hidden;
  }

  .aitools-sidebar {
    display: flex;
    flex-direction: column;
    gap: 8px;
    overflow-y: auto;
    padding-right: 4px;
  }

  .tool-card {
    padding: 16px;
    border-radius: 12px;
    cursor: pointer;
    text-align: left;
    transition: all 0.2s;
    font-family: inherit;

    &:hover:not(.active) {
      border-color: var(--el-color-primary) !important;
      background: var(--el-fill-color-light) !important;
    }

    &__header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 6px;
    }

    &__name {
      font-size: 13px;
      font-weight: 700;
    }

    &__dot {
      margin-left: auto;
      width: 6px;
      height: 6px;
      border-radius: 50%;
    }

    &__desc {
      font-size: 12px;
      color: var(--art-gray-500);
      line-height: 1.5;
      margin: 0;
    }

    &__tags {
      display: flex;
      gap: 5px;
      margin-top: 8px;
      flex-wrap: wrap;
    }

    &__tag {
      font-size: 10px;
      padding: 2px 7px;
      border-radius: 10px;
      border: 1px solid;
      font-family: var(--el-font-family-monospace, monospace);
      font-weight: 600;
    }
  }

  .aitools-panel {
    border: 1px solid var(--el-border-color-light);
    border-radius: 12px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
    background: var(--el-bg-color);
  }

  .aitools-empty {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 16px;
    padding: 32px;

    &__title {
      font-size: 16px;
      font-weight: 700;
      color: var(--art-gray-900);
    }

    &__desc {
      font-size: 13px;
      color: var(--art-gray-500);
    }
  }

  .aitools-panel__header {
    padding: 14px 20px;
    border-bottom: 1px solid var(--el-border-color-light);
    display: flex;
    align-items: center;
    gap: 12px;
    flex-shrink: 0;
  }

  .aitools-panel__title {
    font-size: 14px;
    font-weight: 700;
    color: var(--art-gray-900);
  }

  .aitools-panel__subtitle {
    font-size: 11px;
    color: var(--art-gray-500);
  }

  .aitools-panel__body {
    flex: 1;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .aitools-panel__input-area {
    padding: 16px;
    border-bottom: 1px solid var(--el-border-color-light);
    flex-shrink: 0;
  }

  .aitools-panel__actions {
    display: flex;
    gap: 8px;
    align-items: center;
    margin-top: 10px;
  }

  .aitools-panel__tags-label {
    font-size: 11px;
    color: var(--art-gray-500);
    margin-left: auto;
    font-family: var(--el-font-family-monospace, monospace);
  }

  .aitools-panel__output {
    flex: 1;
    overflow-y: auto;
    padding: 20px;
  }

  .aitools-panel__output-empty {
    display: flex;
    flex-direction: column;
    gap: 8px;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: var(--art-gray-400);
    font-size: 13px;
  }

  .cursor-blink {
    display: inline-block;
    width: 8px;
    height: 14px;
    background: var(--el-color-primary);
    margin-left: 2px;
    vertical-align: middle;
    border-radius: 1px;
    animation: blink 1s step-end infinite;
  }

  @keyframes blink {
    50% { opacity: 0; }
  }
</style>
