// frontend-vite/src/pages/audit-logs.tsx
import { useEffect, useState } from 'react';
import { auditAPI } from '@/services/api';
import { Icon } from '@/components/ui/icon';
import { Avatar, PageHeader } from '@/components/ui/page-helpers';
import { EmptyState } from '@/components/ui/empty-state';
import type { AuditLog, AuditStats } from '@/types';

const ACTION_LABELS: Record<string, { label: string; color: string }> = {
  login: { label: '登录', color: 'var(--amber)' },
  register: { label: '注册', color: 'var(--purple)' },
  create: { label: '创建', color: 'var(--green)' },
  read: { label: '查看', color: 'var(--text-3)' },
  update: { label: '更新', color: 'var(--teal)' },
  delete: { label: '删除', color: 'var(--red)' },
  approve: { label: '审批通过', color: 'var(--green)' },
  reject: { label: '驳回', color: 'var(--red)' },
};

export function AuditLogsPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]);
  const [stats, setStats] = useState<AuditStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [actionFilter, setActionFilter] = useState('all');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => {
    setLoading(true);
    Promise.all([
      auditAPI.list({ page, page_size: 20, action: actionFilter !== 'all' ? actionFilter : undefined }),
      auditAPI.stats(),
    ])
      .then(([logRes, statsRes]) => {
        setLogs(logRes.logs || []);
        setTotalPages(logRes.total_pages || 1);
        setStats(statsRes);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, [page, actionFilter]);

  const filtered = logs.filter(log => {
    if (search && !log.username.includes(search) && !log.action.includes(search) && !log.resource.includes(search)) return false;
    return true;
  });

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <PageHeader
        title="审计日志"
        subtitle="系统全量操作记录 · 不可篡改"
      />

      <div className="anim-in" style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 10, marginBottom: 16 }}>
        {[
          { label: '今日操作', val: stats?.today_logs ?? '-', color: 'var(--amber)' },
          { label: '总计日志', val: stats?.total_logs ?? '-', color: 'var(--teal)' },
          { label: '登录失败', val: stats?.failed_logins ?? '-', color: 'var(--red)' },
          { label: '操作类型', val: stats?.top_actions?.length ?? '-', color: 'var(--purple)' },
        ].map(({ label, val, color }) => (
          <div key={label} style={{ padding: '12px 16px', borderRadius: 10, background: 'var(--surface)', border: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 12 }}>
            <div style={{ fontFamily: 'var(--font-mono)', fontSize: 22, fontWeight: 700, color }}>{String(val)}</div>
            <div style={{ fontSize: 12, color: 'var(--text-3)' }}>{label}</div>
          </div>
        ))}
      </div>

      <div className="anim-in d2" style={{ display: 'flex', gap: 10, marginBottom: 14, alignItems: 'center' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, height: 34, padding: '0 12px', borderRadius: 8, background: 'var(--surface)', border: '1px solid var(--border)', flex: 1, maxWidth: 280 }}>
          <Icon name="search" size={13}/>
          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索用户、操作、对象…"
            style={{ border: 'none', outline: 'none', background: 'transparent', fontSize: 13, color: 'var(--text)', width: '100%' }}/>
        </div>
        <div style={{ display: 'flex', gap: 4, padding: 4, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)' }}>
          {[
            { k: 'all', l: '全部' }, { k: 'login', l: '登录' }, { k: 'create', l: '创建' }, { k: 'approve', l: '审批' },
          ].map(({ k, l }) => (
            <button key={k} onClick={() => { setActionFilter(k); setPage(1); }} style={{
              padding: '4px 10px', borderRadius: 7, fontSize: 12, fontWeight: 600,
              background: actionFilter === k ? 'var(--surface)' : 'transparent',
              color: actionFilter === k ? 'var(--text)' : 'var(--text-3)',
              border: actionFilter === k ? '1px solid var(--border)' : '1px solid transparent',
              cursor: 'pointer', transition: 'all 0.15s',
            }}>{l}</button>
          ))}
        </div>
      </div>

      <div className="card anim-in d3" style={{ overflow: 'hidden' }}>
        <table className="forge-table">
          <thead><tr><th>时间</th><th>用户</th><th>操作</th><th>资源</th><th>IP 地址</th></tr></thead>
          <tbody>
            {filtered.map((log, i) => {
              const meta = ACTION_LABELS[log.action] || { label: log.action, color: 'var(--text-3)' };
              return (
                <tr key={log.id}>
                  <td><span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-3)' }}>{new Date(log.created_at).toLocaleString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span></td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <Avatar name={log.username} size={24} index={i}/>
                      <div style={{ fontWeight: 600, fontSize: 13 }}>{log.username || '-'}</div>
                    </div>
                  </td>
                  <td><span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700, color: meta.color, padding: '3px 8px', borderRadius: 6, background: `${meta.color}14` }}>{meta.label}</span></td>
                  <td style={{ color: 'var(--text-2)', maxWidth: 200 }}><span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', display: 'block' }}>{log.resource || log.path}</span></td>
                  <td><span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-3)' }}>{log.ip}</span></td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {filtered.length === 0 && <EmptyState icon="shield" title="暂无匹配的日志"/>}
      </div>

      {totalPages > 1 && (
        <div className="anim-in d4" style={{ display: 'flex', justifyContent: 'center', gap: 8, marginTop: 16 }}>
          <button className="btn btn-outline btn-sm" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>上一页</button>
          <span style={{ fontSize: 13, color: 'var(--text-3)', padding: '4px 12px' }}>{page} / {totalPages}</span>
          <button className="btn btn-outline btn-sm" disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>下一页</button>
        </div>
      )}
    </div>
  );
}

// frontend-vue/src/views/ssgl/audit-logs/index.vue
<template>
  <section class="ssgl-page" data-page="AuditLogs">
    <SSGLPageHeader title="审计日志" subtitle="系统全量操作记录 · 不可篡改" />

    <!-- Stats Cards -->
    <ElRow :gutter="12" class="mb-4">
      <ElCol :span="6" v-for="item in statCards" :key="item.label">
        <div class="stat-card">
          <div class="stat-card__value" :style="{ color: item.color }">{{ item.value }}</div>
          <div class="stat-card__label">{{ item.label }}</div>
        </div>
      </ElCol>
    </ElRow>

    <!-- Filters -->
    <div class="filter-bar mb-4">
      <ElInput
        v-model="search"
        placeholder="搜索用户、操作、对象…"
        :prefix-icon="Search"
        clearable
        style="max-width: 280px"
      />
      <ElRadioGroup v-model="actionFilter" size="small" @change="handleFilterChange">
        <ElRadioButton label="all">全部</ElRadioButton>
        <ElRadioButton label="login">登录</ElRadioButton>
        <ElRadioButton label="create">创建</ElRadioButton>
        <ElRadioButton label="approve">审批</ElRadioButton>
      </ElRadioGroup>
    </div>

    <!-- Table -->
    <ElTable :data="filtered" v-loading="loading" stripe style="width: 100%">
      <ElTableColumn label="时间" width="160">
        <template #default="{ row }">
          <span class="mono-text">{{ formatTime(row.created_at) }}</span>
        </template>
      </ElTableColumn>
      <ElTableColumn label="用户" width="140">
        <template #default="{ row, $index }">
          <div class="user-cell">
            <ElAvatar :size="24" :style="{ background: avatarColor($index) }">
              {{ (row.username || '-').charAt(0).toUpperCase() }}
            </ElAvatar>
            <span class="user-cell__name">{{ row.username || '-' }}</span>
          </div>
        </template>
      </ElTableColumn>
      <ElTableColumn label="操作" width="120">
        <template #default="{ row }">
          <ElTag :color="getActionMeta(row.action).color" effect="dark" size="small" round>
            {{ getActionMeta(row.action).label }}
          </ElTag>
        </template>
      </ElTableColumn>
      <ElTableColumn label="资源" min-width="200">
        <template #default="{ row }">
          <span class="ellipsis-cell">{{ row.resource || row.path }}</span>
        </template>
      </ElTableColumn>
      <ElTableColumn label="IP 地址" width="140">
        <template #default="{ row }">
          <span class="mono-text">{{ row.ip }}</span>
        </template>
      </ElTableColumn>
    </ElTable>

    <!-- Pagination -->
    <div v-if="totalPages > 1" class="pagination-wrap">
      <ElPagination
        v-model:current-page="page"
        :page-size="20"
        :total="totalPages * 20"
        layout="prev, pager, next"
        background
        @current-change="fetchData"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
  import { Search } from '@element-plus/icons-vue'
  import { auditAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import type { AuditLog, AuditStats } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_AuditLogs' })

  const ACTION_LABELS: Record<string, { label: string; color: string }> = {
    login: { label: '登录', color: '#f59e0b' },
    register: { label: '注册', color: '#a78bfa' },
    create: { label: '创建', color: '#4ade80' },
    read: { label: '查看', color: '#94a3b8' },
    update: { label: '更新', color: '#2dd4bf' },
    delete: { label: '删除', color: '#f87171' },
    approve: { label: '审批通过', color: '#4ade80' },
    reject: { label: '驳回', color: '#f87171' },
  }

  const AVATAR_COLORS = ['#f59e0b', '#4a9eff', '#a78bfa', '#4ade80', '#f87171', '#2dd4bf']

  const logs = ref<AuditLog[]>([])
  const stats = ref<AuditStats | null>(null)
  const loading = ref(true)
  const search = ref('')
  const actionFilter = ref('all')
  const page = ref(1)
  const totalPages = ref(1)

  const statCards = computed(() => [
    { label: '今日操作', value: stats.value?.today_logs ?? '-', color: '#f59e0b' },
    { label: '总计日志', value: stats.value?.total_logs ?? '-', color: '#2dd4bf' },
    { label: '登录失败', value: stats.value?.failed_logins ?? '-', color: '#f87171' },
    { label: '操作类型', value: stats.value?.top_actions?.length ?? '-', color: '#a78bfa' },
  ])

  const filtered = computed(() => {
    if (!search.value) return logs.value
    const q = search.value.toLowerCase()
    return logs.value.filter(
      log =>
        log.username?.toLowerCase().includes(q) ||
        log.action?.toLowerCase().includes(q) ||
        log.resource?.toLowerCase().includes(q)
    )
  })

  function getActionMeta(action: string) {
    return ACTION_LABELS[action] ?? { label: action, color: '#94a3b8' }
  }

  function avatarColor(index: number) {
    return AVATAR_COLORS[index % AVATAR_COLORS.length]
  }

  function formatTime(dateStr: string) {
    if (!dateStr) return '-'
    const d = new Date(dateStr)
    return d.toLocaleString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
  }

  function handleFilterChange() {
    page.value = 1
    fetchData()
  }

  async function fetchData() {
    loading.value = true
    try {
      const [logRes, statsRes] = await Promise.all([
        auditAPI.list({
          page: page.value,
          page_size: 20,
          action: actionFilter.value !== 'all' ? actionFilter.value : undefined,
        }),
        auditAPI.stats(),
      ])
      logs.value = logRes.logs || []
      totalPages.value = logRes.total_pages || 1
      stats.value = statsRes
    } catch (e) {
      console.error('Failed to fetch audit logs:', e)
    } finally {
      loading.value = false
    }
  }

  onMounted(fetchData)
</script>

<style scoped lang="scss">
  .mb-4 {
    margin-bottom: 16px;
  }

  .stat-card {
    padding: 12px 16px;
    border-radius: 10px;
    background: var(--el-bg-color);
    border: 1px solid var(--el-border-color-lighter);
    display: flex;
    align-items: center;
    gap: 12px;

    &__value {
      font-family: var(--el-font-family);
      font-size: 22px;
      font-weight: 700;
    }

    &__label {
      font-size: 12px;
      color: var(--el-text-color-secondary);
    }
  }

  .filter-bar {
    display: flex;
    gap: 12px;
    align-items: center;
  }

  .user-cell {
    display: flex;
    align-items: center;
    gap: 8px;

    &__name {
      font-weight: 600;
      font-size: 13px;
    }
  }

  .mono-text {
    font-family: var(--el-font-family);
    font-size: 11px;
    color: var(--el-text-color-secondary);
  }

  .ellipsis-cell {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    display: block;
    max-width: 200px;
    color: var(--el-text-color-regular);
  }

  .pagination-wrap {
    display: flex;
    justify-content: center;
    margin-top: 16px;
  }
</style>
