// frontend-vite/src/pages/preplans.tsx
import { useEffect, useState } from 'react';
import { prePlansAPI, teamsAPI } from '@/services/api';
import { useRole } from '@/hooks/use-role';
import { StatusBadge } from '@/components/ui/badge';
import { ScoreGauge } from '@/components/ui/charts';
import { Icon } from '@/components/ui/icon';
import { ProgressBar, PageHeader, SectionLabel } from '@/components/ui/page-helpers';
import { Button } from '@/components/ui/button';
import { FormModal, Field, TextInput, TextArea, Select } from '@/components/ui/form';
import { toast } from '@/components/ui/toast';
import { getApiError } from '@/lib/form-utils';
import type { PrePlan, Team } from '@/types';

function AIReviewPanel({ plan, onRefresh }: { plan: PrePlan; onRefresh?: () => void }) {
  const [text, setText] = useState('');
  const [typing, setTyping] = useState(false);
  const [reviewing, setReviewing] = useState(false);
  const fullText = plan.ai_review_notes || '';

  useEffect(() => {
    if (!fullText) return;
    let i = 0;
    setTyping(true);
    setText('');
    const interval = setInterval(() => {
      i++;
      setText(fullText.slice(0, i));
      if (i >= fullText.length) { clearInterval(interval); setTyping(false); }
    }, 14);
    return () => clearInterval(interval);
  }, [plan.id]);

  const triggerReview = async () => {
    setReviewing(true);
    try {
      await prePlansAPI.review(plan.id);
      toast.success('AI 评审完成');
      onRefresh?.();
    } catch (e: unknown) {
      toast.error(getApiError(e, 'AI 评审失败'));
    } finally {
      setReviewing(false);
    }
  };

  if (!plan.ai_review_score) {
    return (
      <div style={{ padding: 24, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 12 }}>
        <div style={{ width: 48, height: 48, borderRadius: 12, background: 'var(--teal-bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--teal)' }}>
          <Icon name="sparkles" size={22}/>
        </div>
        <div style={{ fontSize: 14, fontWeight: 600, color: 'var(--text-2)', textAlign: 'center' }}>
          {reviewing ? 'AI 正在评审中，请稍候…' : '点击下方按钮，获取 AI 智能评审报告'}
        </div>
        <Button
          onClick={triggerReview}
          disabled={reviewing}
          variant="primary"
          style={{ marginTop: 8 }}
        >
          {reviewing ? '评审中…' : <><Icon name="sparkles" size={14} /> 请求 AI 评审</>}
        </Button>
      </div>
    );
  }

  const dimensions = plan.ai_dimensions;

  return (
    <div style={{ padding: 24, overflowY: 'auto', height: '100%' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 20, padding: '10px 14px', borderRadius: 10, background: 'var(--teal-bg)', border: '1px solid var(--teal-border)' }}>
        <div style={{ width: 32, height: 32, borderRadius: 8, background: 'var(--teal)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
          <Icon name="sparkles" size={15}/>
        </div>
        <div>
          <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--teal)', letterSpacing: '0.06em' }}>AI REVIEW · RAG + LLM</div>
          <div style={{ fontSize: 11, color: 'var(--text-3)' }}>基于往届项目综合评估</div>
        </div>
      </div>

      <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 24 }}>
        <ScoreGauge score={plan.ai_review_score} size={160}/>
      </div>

      {dimensions && (
        <div style={{ marginBottom: 24 }}>
          <SectionLabel label="分项评分"/>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {dimensions.map(({ label, score }) => {
              const color = score >= 80 ? 'var(--green)' : score >= 65 ? 'var(--amber)' : 'var(--red)';
              return (
                <div key={label}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 5, alignItems: 'center' }}>
                    <span style={{ fontSize: 13, color: 'var(--text-2)', fontWeight: 500 }}>{label}</span>
                    <span style={{ fontFamily: 'var(--font-mono)', fontSize: 13, fontWeight: 700, color }}>{score}/100</span>
                  </div>
                  <ProgressBar value={score} max={100} color={color} height={7}/>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div>
        <SectionLabel label="AI 综合意见"/>
        <div style={{ padding: 14, borderRadius: 10, background: 'var(--surface-2)', border: '1px solid var(--border)', fontSize: 13, color: 'var(--text-2)', lineHeight: 1.75, minHeight: 80 }}>
          {text}
          {typing && <span style={{ display: 'inline-block', width: 2, height: 14, background: 'var(--teal)', marginLeft: 2, animation: 'forge-spin 1s step-end infinite', verticalAlign: 'middle' }}/>}
        </div>
      </div>
    </div>
  );
}

type PrePlanFormState = {
  team_id: string; title: string; tech_stack: string; target_audience: string;
  market_analysis: string; innovation: string; expected_outcome: string; timeline: string;
};
function emptyPrePlanForm(): PrePlanFormState {
  return { team_id: '', title: '', tech_stack: '', target_audience: '', market_analysis: '', innovation: '', expected_outcome: '', timeline: '' };
}

function PrePlanForm({ onClose, teams, onCreated }: {
  onClose: () => void;
  teams: Team[];
  onCreated: (plan: PrePlan) => void;
}) {
  const [form, setForm] = useState<PrePlanFormState>(emptyPrePlanForm);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const set = (k: keyof PrePlanFormState) => (v: string) => setForm((f) => ({ ...f, [k]: v }));
  const teamOptions = teams.map((t) => ({ value: String(t.id), label: t.competition?.title ? `${t.name} · ${t.competition.title}` : t.name }));

  const submit = async () => {
    if (!form.team_id) { setError('请选择团队'); return; }
    if (!form.title.trim()) { setError('请填写方案标题'); return; }
    const team = teams.find((t) => String(t.id) === form.team_id);
    if (!team) { setError('团队无效'); return; }
    setSubmitting(true); setError(null);
    try {
      const res = await prePlansAPI.create({
        competition_id: team.competition_id,
        team_id: team.id,
        title: form.title.trim(),
        tech_stack: form.tech_stack,
        target_audience: form.target_audience,
        market_analysis: form.market_analysis,
        innovation: form.innovation,
        expected_outcome: form.expected_outcome,
        timeline: form.timeline,
      });
      toast.success('预计划已提交');
      onCreated(res.pre_plan);
      onClose();
    } catch (err) {
      setError(getApiError(err, '提交失败'));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <FormModal open={true} onClose={onClose} title="新建预计划" onSubmit={submit} submitting={submitting} error={error} submitLabel="提交" width={640}>
      {teams.length === 0 ? (
        <div style={{ fontSize: 13, color: 'var(--text-3)', padding: '12px 0' }}>你还没有团队，请先到「团队管理」创建团队。</div>
      ) : (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
            <Field label="团队" required><Select value={form.team_id} onChange={set('team_id')} options={teamOptions} placeholder="选择团队" /></Field>
            <Field label="方案标题" required><TextInput value={form.title} onChange={(e) => set('title')(e.target.value)} placeholder="项目名称" /></Field>
          </div>
          <Field label="技术栈"><TextArea value={form.tech_stack} onChange={(e) => set('tech_stack')(e.target.value)} /></Field>
          <Field label="目标用户"><TextArea value={form.target_audience} onChange={(e) => set('target_audience')(e.target.value)} /></Field>
          <Field label="市场分析"><TextArea value={form.market_analysis} onChange={(e) => set('market_analysis')(e.target.value)} /></Field>
          <Field label="创新点"><TextArea value={form.innovation} onChange={(e) => set('innovation')(e.target.value)} /></Field>
          <Field label="预期成果"><TextArea value={form.expected_outcome} onChange={(e) => set('expected_outcome')(e.target.value)} /></Field>
          <Field label="时间规划"><TextArea value={form.timeline} onChange={(e) => set('timeline')(e.target.value)} /></Field>
        </>
      )}
    </FormModal>
  );
}

export function PrePlansPage() {
  const role = useRole();
  const [preplans, setPreplans] = useState<PrePlan[]>([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<PrePlan | null>(null);
  const [tab, setTab] = useState('detail');

  useEffect(() => {
    prePlansAPI.list().then(res => {
      const plans = res.pre_plans || [];
      setPreplans(plans);
      if (plans.length > 0) setSelected(plans[0]);
    }).catch(console.error).finally(() => setLoading(false));
  }, []);

  const [myTeams, setMyTeams] = useState<Team[]>([]);
  const [createOpen, setCreateOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  useEffect(() => { teamsAPI.list().then((r) => setMyTeams(r.teams || [])).catch(() => {}); }, []);

  const onCreated = (plan: PrePlan) => {
    setPreplans((prev) => [plan, ...prev]);
    setSelected(plan);
    setTab('detail');
  };

  const refreshSelected = async () => {
    if (!selected) return;
    try {
      const res = await prePlansAPI.get(selected.id);
      const updated = res.pre_plan;
      setPreplans(prev => prev.map(p => p.id === updated.id ? updated : p));
      setSelected(updated);
    } catch { /* ignore */ }
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', height: '100%', alignItems: 'center', justifyContent: 'center' }}>
        <svg width={32} height={32} viewBox="0 0 24 24" style={{ animation: 'forge-spin 0.7s linear infinite' }}>
          <circle cx="12" cy="12" r="10" fill="none" stroke="var(--border-2)" strokeWidth="2.5"/>
          <path d="M12 2a10 10 0 0110 10" fill="none" stroke="var(--amber)" strokeWidth="2.5" strokeLinecap="round"/>
        </svg>
      </div>
    );
  }

  return (
    <div className="forge-page">
      <PageHeader
        title="预计划管理"
        subtitle="提交预计划，获取 AI 智能评审报告"
        actions={role === 'student' ? <Button variant="primary" icon={<Icon name="plus" size={13}/>} onClick={() => setCreateOpen(true)}>新建预计划</Button> : undefined}
      />

      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 16, height: 'calc(100vh - 180px)', overflow: 'hidden' }}>
        <div className="card anim-in" style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--border)', fontSize: 12, fontWeight: 700, color: 'var(--text-3)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
            预计划列表 ({preplans.length})
          </div>
          <div style={{ overflowY: 'auto', flex: 1 }}>
            {preplans.map((plan) => (
              <div key={plan.id} onClick={() => { setSelected(plan); setTab('detail'); }} style={{
                padding: '14px 16px', borderBottom: '1px solid var(--border)', cursor: 'pointer',
                background: selected?.id === plan.id ? 'var(--amber-bg)' : 'transparent',
                borderLeft: selected?.id === plan.id ? '3px solid var(--amber)' : '3px solid transparent',
                transition: 'all 0.15s',
              }}
                onMouseEnter={e => { if (selected?.id !== plan.id) e.currentTarget.style.background = 'var(--surface-2)'; }}
                onMouseLeave={e => { if (selected?.id !== plan.id) e.currentTarget.style.background = 'transparent'; }}
              >
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 6, lineHeight: 1.3 }}>{plan.title}</div>
                <div style={{ display: 'flex', gap: 6, alignItems: 'center', flexWrap: 'wrap' }}>
                  <StatusBadge status={plan.status}/>
                  {plan.team?.name && <span style={{ fontSize: 11, color: 'var(--text-3)' }}>{plan.team.name}</span>}
                  {plan.ai_review_score && (
                    <span style={{ marginLeft: 'auto', fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700, color: 'var(--teal)' }}>AI {plan.ai_review_score}</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        {selected && (
          <div className="card anim-in d2" style={{ overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
            <div style={{ display: 'flex', gap: 0, borderBottom: '1px solid var(--border)', padding: '0 20px', flexShrink: 0 }}>
              {[
                { k: 'detail', l: '方案详情' },
                { k: 'ai', l: 'AI 评审报告', highlight: !!selected.ai_review_score },
              ].map(({ k, l, highlight }) => (
                <button key={k} onClick={() => setTab(k)} style={{
                  padding: '14px 16px', fontSize: 13, fontWeight: 600, border: 'none', background: 'transparent',
                  color: tab === k ? (highlight ? 'var(--teal)' : 'var(--amber)') : 'var(--text-3)',
                  borderBottom: tab === k ? `2px solid ${highlight ? 'var(--teal)' : 'var(--amber)'}` : '2px solid transparent',
                  cursor: 'pointer', transition: 'all 0.15s', display: 'flex', alignItems: 'center', gap: 6,
                }}>
                  {highlight && k === 'ai' && <span style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--teal)' }}/>}
                  {l}
                </button>
              ))}
            </div>
            <div style={{ flex: 1, overflow: 'hidden' }}>
              {tab === 'detail' ? (
                <div style={{ padding: 24, overflowY: 'auto', height: '100%' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
                    <h3 style={{ fontSize: 18, fontWeight: 700, color: 'var(--text)', flex: 1 }}>{selected.title}</h3>
                    <StatusBadge status={selected.status}/>
                    {role === 'student' && (selected.status === 'draft' || selected.status === 'reviewed') && (
                      <Button variant="outline" size="sm" icon={<Icon name="edit" size={12}/>} onClick={() => setEditOpen(true)}>编辑</Button>
                    )}
                  </div>
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 20 }}>
                    {[
                      { label: '团队', value: selected.team?.name || '—' },
                      { label: '提交时间', value: selected.submitted_at ? new Date(selected.submitted_at).toLocaleDateString('zh-CN') : '未提交' },
                    ].map(({ label, value }) => (
                      <div key={label} style={{ padding: '10px 12px', borderRadius: 8, background: 'var(--surface-2)' }}>
                        <div style={{ fontSize: 11, color: 'var(--text-3)', marginBottom: 3 }}>{label}</div>
                        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>{value}</div>
                      </div>
                    ))}
                  </div>
                  {[
                    { label: '技术栈', value: selected.tech_stack },
                    { label: '目标用户', value: selected.target_audience },
                    { label: '市场分析', value: selected.market_analysis },
                    { label: '创新点', value: selected.innovation },
                    { label: '预期成果', value: selected.expected_outcome },
                  ].filter(f => f.value).map(({ label, value }) => (
                    <div key={label} style={{ marginBottom: 14 }}>
                      <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-3)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 6 }}>{label}</div>
                      <div style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.7, padding: '10px 14px', borderRadius: 8, background: 'var(--surface-2)', border: '1px solid var(--border)' }}>{value}</div>
                    </div>
                  ))}
                </div>
              ) : (
                <AIReviewPanel plan={selected} onRefresh={refreshSelected}/>
              )}
            </div>
          </div>
        )}
      </div>
      {createOpen && <PrePlanForm onClose={() => setCreateOpen(false)} teams={myTeams} onCreated={onCreated} />}
      {editOpen && selected && (
        <PrePlanEditForm
          plan={selected}
          onClose={() => setEditOpen(false)}
          onSaved={(updated) => {
            setPreplans(prev => prev.map(p => p.id === updated.id ? updated : p));
            setSelected(updated);
            setEditOpen(false);
          }}
        />
      )}
    </div>
  );
}

/** 编辑预计划表单 */
function PrePlanEditForm({ plan, onClose, onSaved }: {
  plan: PrePlan;
  onClose: () => void;
  onSaved: (plan: PrePlan) => void;
}) {
  const [form, setForm] = useState({
    title: plan.title || '',
    tech_stack: plan.tech_stack || '',
    target_audience: plan.target_audience || '',
    market_analysis: plan.market_analysis || '',
    innovation: plan.innovation || '',
    expected_outcome: plan.expected_outcome || '',
    timeline: plan.timeline || '',
  });
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const set = (key: string) => (val: string) => setForm(f => ({ ...f, [key]: val }));

  const submit = async () => {
    if (!form.title.trim()) { setError('请填写方案标题'); return; }
    setSubmitting(true); setError(null);
    try {
      const res = await prePlansAPI.update(plan.id, {
        title: form.title.trim(),
        tech_stack: form.tech_stack,
        target_audience: form.target_audience,
        market_analysis: form.market_analysis,
        innovation: form.innovation,
        expected_outcome: form.expected_outcome,
        timeline: form.timeline,
      });
      toast.success('预计划已更新');
      onSaved(res.pre_plan);
    } catch (err) {
      setError(getApiError(err, '更新失败'));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <FormModal open={true} onClose={onClose} title="编辑预计划" onSubmit={submit} submitting={submitting} error={error} submitLabel="保存" width={640}>
      <Field label="方案标题" required><TextInput value={form.title} onChange={(e) => set('title')(e.target.value)} placeholder="项目名称" /></Field>
      <Field label="技术栈"><TextArea value={form.tech_stack} onChange={(e) => set('tech_stack')(e.target.value)} /></Field>
      <Field label="目标用户"><TextArea value={form.target_audience} onChange={(e) => set('target_audience')(e.target.value)} /></Field>
      <Field label="市场分析"><TextArea value={form.market_analysis} onChange={(e) => set('market_analysis')(e.target.value)} /></Field>
      <Field label="创新点"><TextArea value={form.innovation} onChange={(e) => set('innovation')(e.target.value)} /></Field>
      <Field label="预期成果"><TextArea value={form.expected_outcome} onChange={(e) => set('expected_outcome')(e.target.value)} /></Field>
      <Field label="时间规划"><TextArea value={form.timeline} onChange={(e) => set('timeline')(e.target.value)} /></Field>
    </FormModal>
  );
}

// frontend-vue/src/views/ssgl/preplans/index.vue
<template>
  <section class="ssgl-page" data-page="Preplans">
    <SSGLPageHeader title="预计划管理" subtitle="提交预计划，获取 AI 智能评审报告">
      <template #actions>
        <ElButton type="primary" @click="openCreate">
          <ElIcon><Plus /></ElIcon>
          新建预计划
        </ElButton>
      </template>
    </SSGLPageHeader>

    <ElRow :gutter="16" style="height: calc(100vh - 220px)">
      <!-- Left: Plan List -->
      <ElCol :span="8" style="height: 100%">
        <ElCard shadow="never" v-loading="loading" style="height: 100%; display: flex; flex-direction: column">
          <template #header>
            <span class="font-semibold">预计划列表 ({{ preplans.length }})</span>
          </template>
          <div class="flex-1 overflow-auto">
            <div
              v-for="plan in preplans"
              :key="plan.id"
              class="p-3 border-b cursor-pointer transition-colors"
              :class="selected?.id === plan.id
                ? 'bg-amber-50 dark:bg-amber-900/20 border-l-2 border-l-amber-500'
                : 'hover:bg-gray-50 dark:hover:bg-gray-800 border-l-2 border-l-transparent'"
              @click="selectPlan(plan)"
            >
              <div class="font-semibold text-sm mb-1 line-clamp-1">{{ plan.title }}</div>
              <div class="flex items-center gap-2 flex-wrap">
                <SSGLStatusTag :status="plan.status" />
                <span v-if="plan.team?.name" class="text-xs text-gray-400">{{ plan.team.name }}</span>
                <span v-if="plan.ai_review_score" class="ml-auto font-mono font-bold text-sm text-teal-500">
                  AI {{ plan.ai_review_score }}
                </span>
              </div>
            </div>
            <div v-if="preplans.length === 0" class="py-12 text-center text-gray-400">
              暂无预计划
            </div>
          </div>
        </ElCard>
      </ElCol>

      <!-- Right: Detail -->
      <ElCol :span="16" style="height: 100%">
        <ElCard v-if="selected" shadow="never" style="height: 100%; display: flex; flex-direction: column">
          <template #header>
            <ElTabs v-model="activeTab" class="-mb-4">
              <ElTabPane label="方案详情" name="detail" />
              <ElTabPane name="ai">
                <template #label>
                  <span class="flex items-center gap-1">
                    <span v-if="selected.ai_review_score" class="w-2 h-2 rounded-full bg-teal-500" />
                    AI 评审报告
                  </span>
                </template>
              </ElTabPane>
            </ElTabs>
          </template>

          <div class="flex-1 overflow-auto">
            <!-- Detail Tab -->
            <div v-if="activeTab === 'detail'" class="p-2">
              <div class="flex items-center gap-3 mb-4">
                <h3 class="text-lg font-bold flex-1">{{ selected.title }}</h3>
                <SSGLStatusTag :status="selected.status" />
                <ElButton
                  v-if="selected.status === 'draft' || selected.status === 'reviewed'"
                  size="small"
                  @click="openEdit"
                >
                  编辑
                </ElButton>
              </div>

              <ElRow :gutter="12" class="mb-4">
                <ElCol :span="12">
                  <div class="p-3 rounded-lg bg-gray-50 dark:bg-gray-800">
                    <div class="text-xs text-gray-400 mb-1">团队</div>
                    <div class="font-semibold">{{ selected.team?.name || '—' }}</div>
                  </div>
                </ElCol>
                <ElCol :span="12">
                  <div class="p-3 rounded-lg bg-gray-50 dark:bg-gray-800">
                    <div class="text-xs text-gray-400 mb-1">提交时间</div>
                    <div class="font-semibold">{{ selected.submitted_at ? formatDate(selected.submitted_at) : '未提交' }}</div>
                  </div>
                </ElCol>
              </ElRow>

              <div v-for="field in planFields" :key="field.key" class="mb-4">
                <div class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">{{ field.label }}</div>
                <div class="text-sm leading-relaxed p-3 rounded-lg bg-gray-50 dark:bg-gray-800 border">
                  {{ field.value || '—' }}
                </div>
              </div>
            </div>

            <!-- AI Review Tab -->
            <div v-if="activeTab === 'ai'" class="p-2">
              <!-- No AI review yet -->
              <div v-if="!selected.ai_review_score" class="flex flex-col items-center justify-center py-12 gap-4">
                <div class="w-12 h-12 rounded-xl bg-teal-50 dark:bg-teal-900/30 flex items-center justify-center text-teal-500">
                  <ElIcon :size="24"><MagicStick /></ElIcon>
                </div>
                <div class="text-sm font-semibold text-gray-500">
                  {{ reviewing ? 'AI 正在评审中，请稍候...' : '点击下方按钮，获取 AI 智能评审报告' }}
                </div>
                <ElButton type="primary" :loading="reviewing" @click="triggerReview">
                  <ElIcon v-if="!reviewing"><MagicStick /></ElIcon>
                  {{ reviewing ? '评审中...' : '请求 AI 评审' }}
                </ElButton>
              </div>

              <!-- Has AI review -->
              <div v-else>
                <div class="flex items-center gap-3 mb-5 p-3 rounded-lg bg-teal-50 dark:bg-teal-900/20 border border-teal-200 dark:border-teal-800">
                  <div class="w-8 h-8 rounded-lg bg-teal-500 text-white flex items-center justify-center flex-shrink-0">
                    <ElIcon><MagicStick /></ElIcon>
                  </div>
                  <div>
                    <div class="text-xs font-bold text-teal-600 dark:text-teal-400 tracking-wider">AI REVIEW</div>
                    <div class="text-xs text-gray-400">基于往届项目综合评估</div>
                  </div>
                </div>

                <!-- Score gauge -->
                <div class="flex justify-center mb-6">
                  <div class="relative w-36 h-36">
                    <ElProgress
                      type="circle"
                      :percentage="selected.ai_review_score"
                      :width="144"
                      :stroke-width="10"
                      :color="scoreColor(selected.ai_review_score)"
                    />
                  </div>
                </div>

                <!-- Dimensions -->
                <div v-if="selected.ai_dimensions?.length" class="mb-6">
                  <div class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">分项评分</div>
                  <div class="space-y-3">
                    <div v-for="dim in selected.ai_dimensions" :key="dim.label">
                      <div class="flex justify-between items-center mb-1">
                        <span class="text-sm font-medium">{{ dim.label }}</span>
                        <span class="font-mono font-bold text-sm" :style="{ color: scoreColor(dim.score) }">
                          {{ dim.score }}/100
                        </span>
                      </div>
                      <ElProgress
                        :percentage="dim.score"
                        :stroke-width="7"
                        :show-text="false"
                        :color="scoreColor(dim.score)"
                      />
                    </div>
                  </div>
                </div>

                <!-- AI Notes -->
                <div>
                  <div class="text-xs font-bold text-gray-400 uppercase tracking-wider mb-3">AI 综合意见</div>
                  <div class="p-4 rounded-lg bg-gray-50 dark:bg-gray-800 border text-sm leading-relaxed min-h-[80px]">
                    {{ selected.ai_review_notes || '—' }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </ElCard>

        <ElCard v-else shadow="never" style="height: 100%">
          <div class="flex flex-col items-center justify-center h-full text-gray-400">
            <ElIcon :size="48"><Document /></ElIcon>
            <div class="mt-3 text-sm">选择一项预计划查看详情</div>
          </div>
        </ElCard>
      </ElCol>
    </ElRow>

    <!-- Create Dialog -->
    <ElDialog v-model="showCreate" title="新建预计划" width="660px" destroy-on-close>
      <ElForm :model="createForm" label-width="100px" @submit.prevent="handleCreate">
        <ElRow :gutter="16">
          <ElCol :span="12">
            <ElFormItem label="团队" required>
              <ElSelect v-model="createForm.team_id" placeholder="选择团队" style="width: 100%">
                <ElOption
                  v-for="t in myTeams"
                  :key="t.id"
                  :label="t.competition?.title ? `${t.name} · ${t.competition.title}` : t.name"
                  :value="t.id"
                />
              </ElSelect>
            </ElFormItem>
          </ElCol>
          <ElCol :span="12">
            <ElFormItem label="方案标题" required>
              <ElInput v-model="createForm.title" placeholder="项目名称" />
            </ElFormItem>
          </ElCol>
        </ElRow>
        <ElFormItem label="技术栈">
          <ElInput v-model="createForm.tech_stack" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="目标用户">
          <ElInput v-model="createForm.target_audience" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="市场分析">
          <ElInput v-model="createForm.market_analysis" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="创新点">
          <ElInput v-model="createForm.innovation" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="预期成果">
          <ElInput v-model="createForm.expected_outcome" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="时间规划">
          <ElInput v-model="createForm.timeline" type="textarea" :rows="2" />
        </ElFormItem>
      </ElForm>
      <template #footer>
        <ElButton @click="showCreate = false">取消</ElButton>
        <ElButton type="primary" :loading="submitting" @click="handleCreate">提交</ElButton>
      </template>
    </ElDialog>

    <!-- Edit Dialog -->
    <ElDialog v-model="showEdit" title="编辑预计划" width="660px" destroy-on-close>
      <ElForm :model="editForm" label-width="100px" @submit.prevent="handleEdit">
        <ElFormItem label="方案标题" required>
          <ElInput v-model="editForm.title" placeholder="项目名称" />
        </ElFormItem>
        <ElFormItem label="技术栈">
          <ElInput v-model="editForm.tech_stack" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="目标用户">
          <ElInput v-model="editForm.target_audience" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="市场分析">
          <ElInput v-model="editForm.market_analysis" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="创新点">
          <ElInput v-model="editForm.innovation" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="预期成果">
          <ElInput v-model="editForm.expected_outcome" type="textarea" :rows="2" />
        </ElFormItem>
        <ElFormItem label="时间规划">
          <ElInput v-model="editForm.timeline" type="textarea" :rows="2" />
        </ElFormItem>
      </ElForm>
      <template #footer>
        <ElButton @click="showEdit = false">取消</ElButton>
        <ElButton type="primary" :loading="submitting" @click="handleEdit">保存</ElButton>
      </template>
    </ElDialog>
  </section>
</template>

<script setup lang="ts">
  import { Plus, MagicStick, Document } from '@element-plus/icons-vue'
  import { prePlansAPI, teamsAPI } from '@/api/ssgl'
  import SSGLPageHeader from '@/components/ssgl/SSGLPageHeader.vue'
  import SSGLStatusTag from '@/components/ssgl/SSGLStatusTag.vue'
  import type { PrePlan, Team } from '@/types/ssgl'

  defineOptions({ name: 'SSGL_Preplans' })

  const loading = ref(false)
  const preplans = ref<PrePlan[]>([])
  const selected = ref<PrePlan | null>(null)
  const activeTab = ref('detail')
  const reviewing = ref(false)
  const submitting = ref(false)

  // Teams for create
  const myTeams = ref<Team[]>([])

  // Create dialog
  const showCreate = ref(false)
  const createForm = reactive({
    team_id: null as number | null,
    title: '',
    tech_stack: '',
    target_audience: '',
    market_analysis: '',
    innovation: '',
    expected_outcome: '',
    timeline: '',
  })

  // Edit dialog
  const showEdit = ref(false)
  const editForm = reactive({
    title: '',
    tech_stack: '',
    target_audience: '',
    market_analysis: '',
    innovation: '',
    expected_outcome: '',
    timeline: '',
  })

  const planFields = computed(() => {
    if (!selected.value) return []
    return [
      { key: 'tech_stack', label: '技术栈', value: selected.value.tech_stack },
      { key: 'target_audience', label: '目标用户', value: selected.value.target_audience },
      { key: 'market_analysis', label: '市场分析', value: selected.value.market_analysis },
      { key: 'innovation', label: '创新点', value: selected.value.innovation },
      { key: 'expected_outcome', label: '预期成果', value: selected.value.expected_outcome },
    ].filter(f => f.value)
  })

  const scoreColor = (score: number) => {
    if (score >= 80) return '#10b981'
    if (score >= 65) return '#f59e0b'
    return '#ef4444'
  }

  const formatDate = (d: string) => {
    if (!d) return '—'
    return new Date(d).toLocaleDateString('zh-CN')
  }

  const loadPreplans = async () => {
    loading.value = true
    try {
      const res = await prePlansAPI.list()
      const plans = res.pre_plans || []
      preplans.value = plans
      if (plans.length > 0 && !selected.value) {
        selectPlan(plans[0])
      }
    } catch {
      ElMessage.error('加载预计划数据失败')
    } finally {
      loading.value = false
    }
  }

  const loadTeams = async () => {
    try {
      const res = await teamsAPI.list()
      myTeams.value = res.teams || []
    } catch { /* ignore */ }
  }

  const selectPlan = (plan: PrePlan) => {
    selected.value = plan
    activeTab.value = 'detail'
  }

  const openCreate = () => {
    createForm.team_id = null
    createForm.title = ''
    createForm.tech_stack = ''
    createForm.target_audience = ''
    createForm.market_analysis = ''
    createForm.innovation = ''
    createForm.expected_outcome = ''
    createForm.timeline = ''
    showCreate.value = true
  }

  const openEdit = () => {
    if (!selected.value) return
    editForm.title = selected.value.title || ''
    editForm.tech_stack = selected.value.tech_stack || ''
    editForm.target_audience = selected.value.target_audience || ''
    editForm.market_analysis = selected.value.market_analysis || ''
    editForm.innovation = selected.value.innovation || ''
    editForm.expected_outcome = selected.value.expected_outcome || ''
    editForm.timeline = selected.value.timeline || ''
    showEdit.value = true
  }

  const handleCreate = async () => {
    if (!createForm.team_id) return ElMessage.warning('请选择团队')
    if (!createForm.title.trim()) return ElMessage.warning('请填写方案标题')

    const team = myTeams.value.find(t => t.id === createForm.team_id)
    if (!team) return ElMessage.warning('团队无效')

    submitting.value = true
    try {
      const res = await prePlansAPI.create({
        competition_id: team.competition_id,
        team_id: team.id,
        title: createForm.title.trim(),
        tech_stack: createForm.tech_stack,
        target_audience: createForm.target_audience,
        market_analysis: createForm.market_analysis,
        innovation: createForm.innovation,
        expected_outcome: createForm.expected_outcome,
        timeline: createForm.timeline,
      })
      ElMessage.success('预计划已提交')
      preplans.value = [res.pre_plan, ...preplans.value]
      selected.value = res.pre_plan
      activeTab.value = 'detail'
      showCreate.value = false
    } catch {
      ElMessage.error('提交失败')
    } finally {
      submitting.value = false
    }
  }

  const handleEdit = async () => {
    if (!selected.value) return
    if (!editForm.title.trim()) return ElMessage.warning('请填写方案标题')

    submitting.value = true
    try {
      const res = await prePlansAPI.update(selected.value.id, {
        title: editForm.title.trim(),
        tech_stack: editForm.tech_stack,
        target_audience: editForm.target_audience,
        market_analysis: editForm.market_analysis,
        innovation: editForm.innovation,
        expected_outcome: editForm.expected_outcome,
        timeline: editForm.timeline,
      })
      ElMessage.success('预计划已更新')
      preplans.value = preplans.value.map(p => p.id === res.pre_plan.id ? res.pre_plan : p)
      selected.value = res.pre_plan
      showEdit.value = false
    } catch {
      ElMessage.error('更新失败')
    } finally {
      submitting.value = false
    }
  }

  const triggerReview = async () => {
    if (!selected.value) return
    reviewing.value = true
    try {
      const res = await prePlansAPI.review(selected.value.id)
      ElMessage.success('AI 评审完成')
      const updated = res.pre_plan
      preplans.value = preplans.value.map(p => p.id === updated.id ? updated : p)
      selected.value = updated
    } catch {
      ElMessage.error('AI 评审失败')
    } finally {
      reviewing.value = false
    }
  }

  onMounted(() => {
    loadPreplans()
    loadTeams()
  })
</script>
